// Force headless SDL before ANY import can reach the FFI layer, matching
// test/sdl_platform.test.ts's precedent -- this test boots the full,
// non-dedicated client+server the same way that file does, so it needs the
// same guard.
process.env.SDL_VIDEODRIVER = "dummy";
process.env.SDL_AUDIODRIVER = "dummy";
Bun.env.SDL_VIDEODRIVER = "dummy";
Bun.env.SDL_AUDIODRIVER = "dummy";

/*
Cvar parity audit (engine-only: src/client/, src/server/, src/qcommon/,
src/ref_gl/, src/ref_soft/, src/platform/, src/shared/ -- game-module trees
are out of this audit's scope). This file drives the real subsystem init
functions the same way other integration tests do (test/boot.test.ts,
test/sdl_platform.test.ts, test/cl_main.test.ts) and then checks the
resulting global cvar registry (src/qcommon/cvar.ts's `cvar_vars`) against a
hardcoded manifest of every q2repro-side cvar this port is expected to
register, with q2repro-exact defaults and flags.

Manifest provenance: mechanically generated by diffing every literal
`Cvar_Get("name", "default", flags)` call (including `ri.Cvar_Get`/
`mustCvar` wrapper calls) across q2repro's src/{client,server,common,
refresh,unix}/ against this port's src/ (excluding game/ctf/xatrix/rogue/
lmctf/kexgame), then cross-checked by hand for macro-derived C defaults
(STRINGIFY/va()/build-config values) and #ifdef branch selection. See the
audit report for the full disposition list (ported / registered-consumer-
unported / excluded / place-after-merge).

Boot recipe: one non-dedicated Qcommon_Init over a synthetic worldspawn-only
map (test/sdl_platform.test.ts's exact recipe) drives, in this order:
main.ts's Qcommon_Init body (Key_Init, its own common.c cvar block),
NET_Init, Netchan_Init, SV_Init (server/main.c + server/ac.c, all
"registered, consumer unported"), SV_MvdRegister (server/mvd.c +
server/mvd/{client,game}.c), Nav_Init (server/nav.c), CM_LoadMap (common/
cmodel.c + common/bsp.c, triggered by the `map` command), and CL_Init's own
chain: Con_Init, S_Init (client/sound/*.c), VID_Init (client/refresh.c),
V_Init, M_Init (client/ui/*.c), SCR_Init (client/screen.c + client/cgame.c),
CDAudio_Init, CL_InitLocal (client/main.c + client/tent.c + client/
effects.c + client/demo.c, and -- per cl_input.ts's own header comment --
client/wheel.c via CL_InitInput's CL_Wheel_Init call), IN_Init (client/
input.c's in_enable/in_grab only; place-after-merge for the rest, see
below).

Not reachable through that one boot, driven separately below:
  - src/qcommon/mapdb.ts's MapDB_Init (client/ui/mapdb.c) -- only called from
    a menu action in the real engine, called directly here.
  - src/platform/cd_ogg.ts's CDAudio_Play (client/sound/ogg.c) -- ogg_*
    registration is lazy (fires on first play attempt); called directly
    here with a bogus track so it registers without needing real audio.
  - src/ref_gl/*.ts's R_Register/GL_InitImages (src/refresh/*.c) -- this
    port defaults vid_ref to "soft" (ref_soft, no q2repro counterpart), so
    the real boot above never loads ref_gl. Driven directly here through a
    minimal RefImports shim whose Cvar_Get/Cvar_Set/Cvar_SetValue are the
    real qcommon ones (everything else is an unused stub), which registers
    the real cvar_vars entries without needing a working GL context.
  - src/platform/glimp.ts's GL-context cvars (gl_colorbits/depthbits/
    stencilbits/multisamples/debug/profile) sit inside GLimp_SetMode, which
    also creates a real SDL/GL window -- too heavy for a unit test. Verified
    by direct inspection instead (see the audit report); not re-asserted
    here beyond the ref_gl-side registration for the same six from
    R_GetGLConfig's equivalent (glimp.ts and gl_rmain.ts source the same
    `ri`, and both are documented as citing src/refresh/main.c:1487-1510).

PLACE AFTER MERGE (not in this manifest, not registered by this pass -- see
audit report): cl_maxpackets/cl_fuzzhack/cl_packetdup/cl_showpackets/
cl_instantpacket/cl_batchcmds/m_accel/m_autosens (home: src/client/
cl_input.ts, off-limits) and loc_trace/loc_draw/loc_dist (home: src/
qcommon/loc.ts, off-limits -- "loc" in filename). z_perturb is excluded
entirely (gated behind q2repro's `#if USE_TESTS`, the C engine's own
built-in unit-test harness, which this port does not replicate).
*/

import { describe, test, expect, beforeAll, afterAll } from "bun:test";
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import {
  CVAR_ARCHIVE,
  CVAR_USERINFO,
  CVAR_SERVERINFO,
  CVAR_NOSET,
  CVAR_LATCH,
  CVAR_CHEAT,
  CVAR_PRIVATE,
  CVAR_ROM,
  CVAR_NOARCHIVE,
  CVAR_FILES,
  CVAR_REFRESH,
  CVAR_SOUND,
  DF_INSTANT_ITEMS,
  type CvarT,
} from "../src/shared/q_shared";
import { cvar_vars, Cvar_Get, Cvar_Set, Cvar_SetValue, Cvar_ForceSet } from "../src/qcommon/cvar";
import { Qcommon_Init, Qcommon_Frame } from "../src/main";
import { sv, ServerStateT } from "../src/server/server";
import { SV_Shutdown } from "../src/server/sv_main";
import { NET_ClearLoopback, NET_Shutdown } from "../src/platform/net_udp";
import { setRe } from "../src/client/client";
import { SDL_ResetBackendForTests } from "../src/platform/sdl";
import { PROTOCOL_VERSION, PORT_SERVER, PORT_ANY } from "../src/qcommon/qcommon";
import { buildBoxRoomBsp, WORLDSPAWN_ONLY_ENTITIES } from "./support/bsp_builder";
import { buildColormapPcx } from "./support/colormap_builder";

import { MapDB_Init } from "../src/qcommon/mapdb";
import { CDAudio_Play, CDAudio_TestResetRegistration } from "../src/platform/cd_ogg";
import { R_Register } from "../src/ref_gl/gl_rmain";
import { GL_InitImages, SetQGL } from "../src/ref_gl/gl_image";
import { SetRefImports } from "../src/ref_gl/gl_local";
import { QGLRecording } from "../src/ref_gl/qgl";
import type { RefImports } from "../src/client/ref";
import { FS_LoadFile, FS_FreeFile, FS_Gamedir, FS_TestSnapshotSearchPaths, FS_TestRestoreSearchPaths, type FsSearchPathSnapshotT } from "../src/qcommon/files";

// ---------------------------------------------------------------------------
// manifest: name, q2repro-exact default string, q2repro-exact flags.
// Mechanically generated (see this file's header) from the intersection of
// q2repro's literal Cvar_Get call sites and this port's, restricted to
// names both sides actually share after this audit's fixes/additions.
// Excludes names whose q2repro C default is itself dynamic (STRINGIFY/va()/
// runtime probe) or build-config-derived with no fixed literal -- those are
// checked individually further below instead.
// ---------------------------------------------------------------------------
interface ManifestEntry {
  name: string;
  default: string;
  flags: number;
}

const MANIFEST: ManifestEntry[] = [
  { name: "_mapdb_episode", default: "-1", flags: 0 },
  { name: "_mapdb_level", default: "-1", flags: 0 },
  { name: "_mapdb_type", default: "episode", flags: 0 },
  { name: "_vid_fullscreen", default: "1", flags: CVAR_ARCHIVE },
  { name: "adr0", default: "", flags: CVAR_ARCHIVE },
  { name: "adr1", default: "", flags: CVAR_ARCHIVE },
  { name: "adr2", default: "", flags: CVAR_ARCHIVE },
  { name: "adr3", default: "", flags: CVAR_ARCHIVE },
  { name: "adr4", default: "", flags: CVAR_ARCHIVE },
  { name: "adr5", default: "", flags: CVAR_ARCHIVE },
  { name: "adr6", default: "", flags: CVAR_ARCHIVE },
  { name: "adr7", default: "", flags: CVAR_ARCHIVE },
  { name: "al_device", default: "", flags: 0 },
  { name: "al_hrtf", default: "0", flags: 0 },
  { name: "al_merge_looping", default: "1", flags: 0 },
  { name: "al_reverb", default: "1", flags: 0 },
  { name: "al_reverb_lerp_time", default: "3.0", flags: 0 },
  { name: "al_timescale", default: "1", flags: 0 },
  { name: "allow_download", default: "1", flags: CVAR_ARCHIVE },
  { name: "allow_download_maps", default: "1", flags: CVAR_ARCHIVE },
  { name: "allow_download_models", default: "1", flags: CVAR_ARCHIVE },
  { name: "allow_download_others", default: "0", flags: 0 },
  { name: "allow_download_pics", default: "1", flags: CVAR_ARCHIVE },
  { name: "allow_download_players", default: "1", flags: CVAR_ARCHIVE },
  { name: "allow_download_sounds", default: "1", flags: CVAR_ARCHIVE },
  { name: "allow_download_textures", default: "1", flags: CVAR_ARCHIVE },
  { name: "ch_alpha", default: "1", flags: 0 },
  { name: "ch_blue", default: "1", flags: 0 },
  { name: "ch_green", default: "1", flags: 0 },
  { name: "ch_health", default: "0", flags: 0 },
  { name: "ch_red", default: "1", flags: 0 },
  { name: "ch_scale", default: "1", flags: 0 },
  { name: "ch_x", default: "0", flags: 0 },
  { name: "ch_y", default: "0", flags: 0 },
  { name: "cheats", default: "0", flags: CVAR_LATCH | CVAR_SERVERINFO },
  { name: "cl_adjustfov", default: "1", flags: 0 },
  { name: "cl_allow_vid_restart", default: "0", flags: 0 },
  { name: "cl_anglespeedkey", default: "1.5", flags: CVAR_CHEAT },
  { name: "cl_async", default: "1", flags: 0 },
  { name: "cl_autopause", default: "1", flags: 0 },
  { name: "cl_beginmapcmd", default: "", flags: 0 },
  { name: "cl_blend", default: "1", flags: 0 },
  { name: "cl_cgame_notify", default: "1", flags: 0 },
  { name: "cl_changemapcmd", default: "", flags: 0 },
  { name: "cl_chat_filter", default: "0", flags: 0 },
  { name: "cl_chat_notify", default: "1", flags: 0 },
  { name: "cl_chat_sound", default: "1", flags: 0 },
  { name: "cl_compass_time", default: "10", flags: 0 },
  { name: "cl_demo_protocol_kex", default: "1", flags: 0 },
  { name: "cl_demomsglen", default: "1390", flags: 0 },
  { name: "cl_demosnaps", default: "10", flags: 0 },
  { name: "cl_demosuspendtoggle", default: "1", flags: 0 },
  { name: "cl_demowait", default: "0", flags: 0 },
  { name: "cl_disable_explosions", default: "0", flags: 0 },
  { name: "cl_disable_particles", default: "0", flags: 0 },
  { name: "cl_disconnectcmd", default: "", flags: 0 },
  { name: "cl_dlight_hacks", default: "0", flags: 0 },
  { name: "cl_entities", default: "1", flags: 0 },
  { name: "cl_flares", default: "1", flags: 0 },
  { name: "cl_footsteps", default: "1", flags: 0 },
  { name: "cl_forwardspeed", default: "200", flags: 0 },
  { name: "cl_gibs", default: "1", flags: 0 },
  { name: "cl_gun", default: "1", flags: 0 },
  { name: "cl_gun_x", default: "0", flags: 0 },
  { name: "cl_gun_y", default: "0", flags: 0 },
  { name: "cl_gun_z", default: "0", flags: 0 },
  { name: "cl_gunalpha", default: "1", flags: 0 },
  { name: "cl_gunfov", default: "90", flags: 0 },
  { name: "cl_hit_markers", default: "2", flags: 0 },
  { name: "cl_http_blocking_timeout", default: "15", flags: 0 },
  { name: "cl_http_debug", default: "0", flags: 0 },
  { name: "cl_http_default_url", default: "", flags: 0 },
  { name: "cl_http_downloads", default: "1", flags: 0 },
  { name: "cl_http_filelists", default: "1", flags: 0 },
  { name: "cl_http_insecure", default: "0", flags: 0 },
  { name: "cl_http_max_connections", default: "2", flags: 0 },
  { name: "cl_http_proxy", default: "", flags: 0 },
  { name: "cl_ignore_stufftext", default: "0", flags: 0 },
  { name: "cl_kickangles", default: "1", flags: CVAR_CHEAT },
  { name: "cl_lerp_lightstyles", default: "1", flags: 0 },
  { name: "cl_lights", default: "1", flags: 0 },
  { name: "cl_maxfps", default: "62", flags: 0 },
  { name: "cl_muzzleflashes", default: "1", flags: 0 },
  { name: "cl_muzzlelight_time", default: "100", flags: 0 },
  { name: "cl_nobob", default: "0", flags: 0 },
  { name: "cl_nodelta", default: "0", flags: 0 },
  { name: "cl_noglow", default: "0", flags: 0 },
  { name: "cl_nolerp", default: "0", flags: 0 },
  { name: "cl_noskins", default: "0", flags: 0 },
  { name: "cl_particles", default: "1", flags: 0 },
  { name: "cl_paused", default: "0", flags: CVAR_ROM },
  { name: "cl_pitchspeed", default: "150", flags: CVAR_CHEAT },
  { name: "cl_predict", default: "1", flags: 0 },
  { name: "cl_railcore_color", default: "red", flags: 0 },
  { name: "cl_railcore_width", default: "2", flags: 0 },
  { name: "cl_railspiral_color", default: "blue", flags: 0 },
  { name: "cl_railspiral_radius", default: "3", flags: 0 },
  { name: "cl_railtrail_time", default: "1.0", flags: 0 },
  { name: "cl_railtrail_type", default: "0", flags: 0 },
  { name: "cl_rerelease_effects", default: "1", flags: 0 },
  { name: "cl_rollhack", default: "1", flags: 0 },
  { name: "cl_run", default: "1", flags: CVAR_ARCHIVE },
  { name: "cl_running", default: "0", flags: CVAR_ROM },
  { name: "cl_shadowlights", default: "1", flags: 0 },
  { name: "cl_showmiss", default: "0", flags: 0 },
  { name: "cl_shownet", default: "0", flags: 0 },
  { name: "cl_sidespeed", default: "200", flags: 0 },
  { name: "cl_smooth_explosions", default: "1", flags: 0 },
  { name: "cl_stats", default: "0", flags: 0 },
  { name: "cl_testblend", default: "0", flags: 0 },
  { name: "cl_testentities", default: "0", flags: 0 },
  { name: "cl_testlights", default: "0", flags: CVAR_CHEAT },
  { name: "cl_testparticles", default: "0", flags: 0 },
  { name: "cl_thirdperson", default: "0", flags: CVAR_CHEAT },
  { name: "cl_thirdperson_angle", default: "0", flags: 0 },
  { name: "cl_thirdperson_range", default: "60", flags: 0 },
  { name: "cl_timeout", default: "120", flags: 0 },
  { name: "cl_updaterate", default: "0", flags: 0 },
  { name: "cl_upspeed", default: "200", flags: 0 },
  { name: "cl_vwep", default: "1", flags: CVAR_ARCHIVE },
  { name: "cl_warn_on_fps_rounding", default: "1", flags: 0 },
  { name: "cl_yawspeed", default: "140", flags: 0 },
  { name: "com_completion_mode", default: "1", flags: 0 },
  { name: "com_completion_treshold", default: "50", flags: 0 },
  { name: "com_date_format", default: "%Y-%m-%d", flags: 0 },
  { name: "com_debug_break", default: "0", flags: 0 },
  { name: "com_fatal_error", default: "0", flags: 0 },
  { name: "com_rerelease", default: "1", flags: CVAR_ARCHIVE },
  { name: "com_time_format", default: "%H:%M", flags: 0 },
  { name: "con_alpha", default: "1", flags: CVAR_ARCHIVE },
  { name: "con_auto_chat", default: "0", flags: 0 },
  { name: "con_background", default: "conback", flags: 0 },
  { name: "con_clock", default: "0", flags: 0 },
  { name: "con_font", default: "conchars", flags: 0 },
  { name: "con_height", default: "0.5", flags: CVAR_ARCHIVE },
  { name: "con_history", default: "128", flags: 0 },
  { name: "con_notifylines", default: "4", flags: 0 },
  { name: "con_notifytime", default: "3", flags: 0 },
  { name: "con_scale", default: "0", flags: CVAR_ARCHIVE },
  { name: "con_scroll", default: "0", flags: 0 },
  { name: "con_timestamps", default: "0", flags: 0 },
  { name: "con_timestampscolor", default: "#aaa", flags: 0 },
  { name: "con_timestampsformat", default: "%H:%M:%S ", flags: 0 },
  { name: "console_prefix", default: "", flags: 0 },
  { name: "crosshair", default: "3", flags: CVAR_ARCHIVE },
  { name: "deathmatch", default: "0", flags: CVAR_LATCH },
  { name: "debuggraph", default: "0", flags: 0 },
  { name: "developer", default: "0", flags: 0 },
  { name: "dogtag", default: "default", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "fixedtime", default: "0", flags: CVAR_CHEAT },
  { name: "flood_msgs", default: "4", flags: 0 },
  { name: "flood_mute", default: "0", flags: 0 },
  { name: "flood_persecond", default: "4", flags: 0 },
  { name: "flood_waitdelay", default: "10", flags: 0 },
  { name: "fov", default: "90", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "fraglimit", default: "0", flags: CVAR_SERVERINFO },
  { name: "freelook", default: "1", flags: CVAR_ARCHIVE },
  { name: "fs_autoexec", default: "1", flags: 0 },
  { name: "fs_debug", default: "0", flags: 0 },
  { name: "fs_fuzz_factor", default: "0", flags: 0 },
  { name: "fs_fuzz_filter", default: "*", flags: 0 },
  { name: "g_features", default: "0", flags: CVAR_ROM },
  { name: "game", default: "", flags: CVAR_LATCH | CVAR_NOARCHIVE | CVAR_SERVERINFO },
  { name: "gender", default: "male", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "gender_auto", default: "1", flags: CVAR_ARCHIVE },
  { name: "gl_anisotropy", default: "1", flags: 0 },
  { name: "gl_beamstyle", default: "0", flags: 0 },
  { name: "gl_bilerp_chars", default: "0", flags: 0 },
  { name: "gl_bilerp_pics", default: "0", flags: 0 },
  { name: "gl_bilerp_skies", default: "1", flags: 0 },
  { name: "gl_bloom", default: "1", flags: 0 },
  { name: "gl_bloom_sigma", default: "8", flags: 0 },
  { name: "gl_brightness", default: "0", flags: 0 },
  { name: "gl_celshading", default: "0", flags: 0 },
  { name: "gl_clear", default: "0", flags: 0 },
  { name: "gl_clearcolor", default: "black", flags: 0 },
  { name: "gl_colorbits", default: "0", flags: CVAR_REFRESH },
  { name: "gl_coloredlightmaps", default: "1", flags: 0 },
  { name: "gl_cubemaps", default: "1", flags: CVAR_FILES },
  { name: "gl_cull_models", default: "1", flags: 0 },
  { name: "gl_cull_nodes", default: "1", flags: 0 },
  { name: "gl_damageblend_frac", default: "0.2", flags: 0 },
  { name: "gl_debug", default: "0", flags: CVAR_REFRESH },
  { name: "gl_debug_distfrac", default: "0.004", flags: 0 },
  { name: "gl_debug_font", default: "futural", flags: 0 },
  { name: "gl_debug_linewidth", default: "2", flags: 0 },
  { name: "gl_debug_text_style", default: "lines", flags: 0 },
  { name: "gl_depthbits", default: "0", flags: CVAR_REFRESH },
  { name: "gl_dlight_falloff", default: "1", flags: 0 },
  { name: "gl_dotshading", default: "0", flags: 0 },
  { name: "gl_downsample_skins", default: "1", flags: CVAR_FILES },
  { name: "gl_drawentities", default: "1", flags: CVAR_CHEAT },
  { name: "gl_draworder", default: "1", flags: 0 },
  { name: "gl_drawsky", default: "1", flags: 0 },
  { name: "gl_drawworld", default: "1", flags: CVAR_CHEAT },
  { name: "gl_dynamic", default: "1", flags: 0 },
  { name: "gl_finish", default: "0", flags: 0 },
  { name: "gl_flarespeed", default: "8", flags: 0 },
  { name: "gl_fog", default: "1", flags: 0 },
  { name: "gl_fontshadow", default: "0", flags: 0 },
  { name: "gl_gamma_scale_pics", default: "0", flags: CVAR_FILES },
  { name: "gl_glowmap_intensity", default: "1", flags: 0 },
  { name: "gl_gpulerp", default: "1", flags: 0 },
  { name: "gl_invert", default: "0", flags: CVAR_FILES },
  { name: "gl_lightgrid", default: "1", flags: 0 },
  { name: "gl_lightmap", default: "0", flags: CVAR_CHEAT },
  { name: "gl_lightmap_bits", default: "0", flags: 0 },
  { name: "gl_lockpvs", default: "0", flags: CVAR_CHEAT },
  { name: "gl_md5_distance", default: "2048", flags: 0 },
  { name: "gl_md5_load", default: "1", flags: CVAR_FILES },
  { name: "gl_md5_use", default: "1", flags: 0 },
  { name: "gl_modulate", default: "2", flags: CVAR_ARCHIVE },
  { name: "gl_modulate_entities", default: "1", flags: 0 },
  { name: "gl_modulate_world", default: "1", flags: 0 },
  { name: "gl_multisamples", default: "0", flags: CVAR_REFRESH },
  { name: "gl_nobind", default: "0", flags: 0 },
  { name: "gl_noscrap", default: "0", flags: CVAR_FILES },
  { name: "gl_novbo", default: "0", flags: CVAR_FILES },
  { name: "gl_novis", default: "0", flags: 0 },
  { name: "gl_partscale", default: "2", flags: 0 },
  { name: "gl_partshape", default: "0", flags: 0 },
  { name: "gl_partstyle", default: "0", flags: 0 },
  { name: "gl_per_pixel_lighting", default: "1", flags: 0 },
  { name: "gl_picmip", default: "0", flags: CVAR_FILES },
  { name: "gl_polyblend", default: "1", flags: 0 },
  { name: "gl_profile", default: "", flags: CVAR_REFRESH },
  { name: "gl_round_down", default: "0", flags: CVAR_FILES },
  { name: "gl_saturation", default: "1", flags: CVAR_FILES },
  { name: "gl_screenshot_async", default: "1", flags: 0 },
  { name: "gl_screenshot_compression", default: "6", flags: 0 },
  { name: "gl_screenshot_format", default: "png", flags: 0 },
  { name: "gl_screenshot_quality", default: "90", flags: 0 },
  { name: "gl_screenshot_template", default: "quakeXXX", flags: 0 },
  { name: "gl_shaders", default: "1", flags: CVAR_FILES },
  { name: "gl_shadows", default: "2", flags: CVAR_ARCHIVE },
  { name: "gl_showbloom", default: "0", flags: CVAR_CHEAT },
  { name: "gl_showcull", default: "0", flags: CVAR_CHEAT },
  { name: "gl_showerrors", default: "1", flags: 0 },
  { name: "gl_showorigins", default: "0", flags: CVAR_CHEAT },
  { name: "gl_showscrap", default: "0", flags: 0 },
  { name: "gl_showtearing", default: "0", flags: CVAR_CHEAT },
  { name: "gl_showtris", default: "0", flags: CVAR_CHEAT },
  { name: "gl_stencilbits", default: "8", flags: CVAR_REFRESH },
  { name: "gl_swapinterval", default: "1", flags: CVAR_ARCHIVE },
  { name: "gl_test", default: "0", flags: 0 },
  { name: "gl_texturebits", default: "0", flags: CVAR_FILES },
  { name: "gl_texturemode", default: "GL_LINEAR_MIPMAP_LINEAR", flags: CVAR_ARCHIVE },
  { name: "gl_upscale_pcx", default: "0", flags: CVAR_FILES },
  { name: "gl_vertexlight", default: "0", flags: 0 },
  { name: "gl_waterwarp", default: "1", flags: 0 },
  { name: "gl_znear", default: "2", flags: CVAR_CHEAT },
  { name: "graphheight", default: "32", flags: 0 },
  { name: "graphscale", default: "1", flags: 0 },
  { name: "graphshift", default: "0", flags: 0 },
  { name: "hand", default: "0", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "host_speeds", default: "0", flags: 0 },
  { name: "hostname", default: "noname", flags: CVAR_ARCHIVE | CVAR_SERVERINFO },
  { name: "hqx_cb", default: "7", flags: CVAR_FILES },
  { name: "hqx_cr", default: "6", flags: CVAR_FILES },
  { name: "hqx_y", default: "48", flags: CVAR_FILES },
  { name: "in_enable", default: "1", flags: 0 },
  { name: "in_grab", default: "1", flags: 0 },
  // "intensity" is NOT in this manifest: q2repro's "1" is not transferable to
  // this renderer. See the dedicated divergence test below.
  { name: "libdir", default: "", flags: CVAR_NOSET },
  { name: "loc_file", default: "localization/loc_english.txt", flags: 0 },
  { name: "logfile", default: "0", flags: 0 },
  { name: "logfile_flush", default: "0", flags: 0 },
  { name: "logfile_name", default: "console", flags: 0 },
  { name: "logfile_prefix", default: "[%Y-%m-%d %H:%M] ", flags: 0 },
  { name: "lookspring", default: "0", flags: CVAR_ARCHIVE },
  { name: "lookstrafe", default: "0", flags: CVAR_ARCHIVE },
  { name: "lrcon_password", default: "", flags: CVAR_PRIVATE },
  { name: "m_filter", default: "0", flags: 0 },
  { name: "m_forward", default: "1", flags: 0 },
  { name: "m_pitch", default: "0.022", flags: CVAR_ARCHIVE },
  { name: "m_side", default: "1", flags: 0 },
  { name: "m_yaw", default: "0.022", flags: 0 },
  { name: "map_noareas", default: "0", flags: 0 },
  { name: "map_override_path", default: "", flags: 0 },
  { name: "map_visibility_patch", default: "1", flags: 0 },
  { name: "msg", default: "1", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "mvd_admin_password", default: "", flags: CVAR_PRIVATE },
  { name: "mvd_buffer_size", default: "8", flags: 0 },
  { name: "mvd_chase_prefix", default: "xv 0 yb -64", flags: 0 },
  { name: "mvd_default_map", default: "q2dm1", flags: CVAR_LATCH },
  { name: "mvd_filter_version", default: "0", flags: 0 },
  { name: "mvd_freeze_hack", default: "1", flags: 0 },
  { name: "mvd_part_filter", default: "0", flags: 0 },
  { name: "mvd_password", default: "", flags: CVAR_PRIVATE },
  { name: "mvd_shownet", default: "0", flags: 0 },
  { name: "mvd_snaps", default: "10", flags: 0 },
  { name: "mvd_stats_hack", default: "0", flags: 0 },
  { name: "mvd_stats_score", default: "0", flags: 0 },
  { name: "mvd_suspend_time", default: "5", flags: 0 },
  { name: "mvd_timeout", default: "90", flags: 0 },
  { name: "mvd_username", default: "unnamed", flags: 0 },
  { name: "mvd_wait_delay", default: "20", flags: 0 },
  { name: "mvd_wait_percent", default: "50", flags: 0 },
  { name: "name", default: "unnamed", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "nav_debug", default: "0", flags: 0 },
  { name: "nav_debug_range", default: "512", flags: 0 },
  { name: "net_dropsim", default: "0", flags: 0 },
  { name: "net_enable_ipv6", default: "0", flags: 0 },
  { name: "net_ignore_icmp", default: "0", flags: 0 },
  { name: "net_ip", default: "", flags: 0 },
  { name: "net_ip6", default: "", flags: 0 },
  { name: "net_log_enable", default: "0", flags: 0 },
  { name: "net_log_flush", default: "0", flags: 0 },
  { name: "net_log_name", default: "network", flags: 0 },
  { name: "netgraph", default: "0", flags: 0 },
  { name: "ogg_enable", default: "1", flags: CVAR_ARCHIVE },
  { name: "ogg_menu_track", default: "77", flags: CVAR_ARCHIVE },
  { name: "ogg_remap_tracks", default: "1", flags: CVAR_ARCHIVE },
  { name: "ogg_shuffle", default: "0", flags: CVAR_ARCHIVE },
  { name: "ogg_volume", default: "1", flags: CVAR_ARCHIVE },
  { name: "password", default: "", flags: CVAR_USERINFO },
  { name: "public", default: "0", flags: CVAR_LATCH },
  { name: "r_fullbright", default: "0", flags: CVAR_CHEAT },
  { name: "r_glowmaps", default: "1", flags: CVAR_FILES },
  { name: "r_maxfps", default: "0", flags: 0 },
  { name: "r_override_textures", default: "1", flags: CVAR_FILES },
  { name: "r_texture_formats", default: "png jpg tga", flags: 0 },
  { name: "r_texture_overrides", default: "-1", flags: CVAR_FILES },
  { name: "rate", default: "15000", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "rcon_address", default: "", flags: CVAR_PRIVATE },
  { name: "rcon_password", default: "", flags: CVAR_PRIVATE },
  { name: "s_ambient", default: "1", flags: 0 },
  { name: "s_auto_focus", default: "2", flags: 0 },
  { name: "s_driver", default: "", flags: CVAR_SOUND },
  { name: "s_enable", default: "2", flags: CVAR_SOUND },
  { name: "s_khz", default: "44", flags: CVAR_ARCHIVE | CVAR_SOUND },
  { name: "s_mixahead", default: "0.1", flags: CVAR_ARCHIVE },
  { name: "s_num_channels", default: "64", flags: CVAR_SOUND },
  { name: "s_show", default: "0", flags: 0 },
  { name: "s_swapstereo", default: "0", flags: 0 },
  { name: "s_testsound", default: "0", flags: 0 },
  { name: "s_underwater", default: "1", flags: 0 },
  { name: "s_underwater_gain_hf", default: "0.25", flags: 0 },
  { name: "s_volume", default: "0.7", flags: CVAR_ARCHIVE },
  { name: "scr_alpha", default: "1", flags: 0 },
  { name: "scr_chathud", default: "0", flags: CVAR_ARCHIVE },
  { name: "scr_chathud_lines", default: "4", flags: CVAR_ARCHIVE },
  { name: "scr_chathud_time", default: "0", flags: CVAR_ARCHIVE },
  { name: "scr_chathud_x", default: "8", flags: CVAR_ARCHIVE },
  { name: "scr_chathud_y", default: "-64", flags: CVAR_ARCHIVE },
  { name: "scr_conspeed", default: "3", flags: 0 },
  { name: "scr_damage_indicator_time", default: "1000", flags: 0 },
  { name: "scr_damage_indicators", default: "1", flags: 0 },
  { name: "scr_demobar", default: "1", flags: 0 },
  { name: "scr_draw2d", default: "2", flags: 0 },
  { name: "scr_font", default: "conchars", flags: 0 },
  { name: "scr_hit_marker_time", default: "500", flags: 0 },
  { name: "scr_lag_draw", default: "0", flags: 0 },
  { name: "scr_lag_max", default: "200", flags: 0 },
  { name: "scr_lag_min", default: "0", flags: 0 },
  { name: "scr_lag_x", default: "-1", flags: 0 },
  { name: "scr_lag_y", default: "-1", flags: 0 },
  { name: "scr_poi_edge_frac", default: "0.15", flags: 0 },
  { name: "scr_poi_max_scale", default: "1.0", flags: 0 },
  { name: "scr_pois", default: "1", flags: 0 },
  { name: "scr_safe_zone", default: "0.02", flags: 0 },
  { name: "scr_scale", default: "0", flags: CVAR_ARCHIVE },
  { name: "scr_showpause", default: "1", flags: 0 },
  { name: "scr_showpmove", default: "0", flags: 0 },
  { name: "scr_showstats", default: "0", flags: 0 },
  { name: "scr_showturtle", default: "1", flags: 0 },
  { name: "sensitivity", default: "3", flags: CVAR_ARCHIVE },
  { name: "showclamp", default: "0", flags: 0 },
  { name: "skill", default: "1", flags: 0 },
  { name: "skin", default: "male/grunt", flags: CVAR_ARCHIVE | CVAR_USERINFO },
  { name: "spectator", default: "0", flags: CVAR_USERINFO },
  { name: "sv_airaccelerate", default: "0", flags: CVAR_LATCH },
  { name: "sv_allow_nodelta", default: "1", flags: 0 },
  { name: "sv_allow_unconnected_cmds", default: "0", flags: 0 },
  { name: "sv_anticheat_badfile_action", default: "0", flags: 0 },
  { name: "sv_anticheat_badfile_max", default: "0", flags: 0 },
  { name: "sv_anticheat_badfile_message", default: "", flags: 0 },
  { name: "sv_anticheat_client_disconnect_action", default: "0", flags: 0 },
  { name: "sv_anticheat_disable_play", default: "0", flags: 0 },
  { name: "sv_anticheat_error_action", default: "0", flags: 0 },
  { name: "sv_anticheat_message", default: "This server requires the r1ch.net anticheat module. Please see http://antiche.at/ for more details.", flags: 0 },
  { name: "sv_anticheat_required", default: "0", flags: CVAR_LATCH },
  { name: "sv_anticheat_server_address", default: "anticheat.r1ch.net", flags: CVAR_LATCH },
  { name: "sv_anticheat_show_violation_reason", default: "0", flags: 0 },
  { name: "sv_auth_limit", default: "1", flags: 0 },
  { name: "sv_calcpings_method", default: "2", flags: 0 },
  { name: "sv_changemapcmd", default: "", flags: 0 },
  { name: "sv_cinematics", default: "1", flags: 0 },
  { name: "sv_debug", default: "0", flags: 0 },
  { name: "sv_downloadserver", default: "", flags: 0 },
  { name: "sv_enforcetime", default: "1", flags: 0 },
  { name: "sv_enhanced_setplayer", default: "0", flags: 0 },
  { name: "sv_features", default: "0", flags: CVAR_ROM },
  { name: "sv_force_reconnect", default: "", flags: CVAR_LATCH },
  { name: "sv_fps", default: "40", flags: CVAR_LATCH },
  { name: "sv_ghostime", default: "6", flags: 0 },
  { name: "sv_idlekick", default: "0", flags: 0 },
  { name: "sv_iplimit", default: "3", flags: 0 },
  { name: "sv_lan_force_rate", default: "0", flags: CVAR_LATCH },
  { name: "sv_locked", default: "0", flags: 0 },
  { name: "sv_max_download_size", default: "8388608", flags: 0 },
  { name: "sv_max_packet_entities", default: "0", flags: 0 },
  { name: "sv_max_rate", default: "60000", flags: CVAR_LATCH },
  { name: "sv_min_rate", default: "15000", flags: CVAR_LATCH },
  { name: "sv_mvd_allow_stufftext", default: "0", flags: CVAR_LATCH },
  { name: "sv_mvd_autorecord", default: "0", flags: CVAR_LATCH },
  { name: "sv_mvd_begincmd", default: "wait 50; putaway; wait 10; help;", flags: 0 },
  { name: "sv_mvd_bufsize", default: "2", flags: CVAR_LATCH },
  { name: "sv_mvd_capture_flags", default: "5", flags: 0 },
  { name: "sv_mvd_disconnect_time", default: "15", flags: 0 },
  { name: "sv_mvd_enable", default: "0", flags: CVAR_LATCH },
  { name: "sv_mvd_maxclients", default: "8", flags: CVAR_LATCH },
  { name: "sv_mvd_maxmaps", default: "1", flags: 0 },
  { name: "sv_mvd_maxsize", default: "0", flags: 0 },
  { name: "sv_mvd_maxtime", default: "0", flags: 0 },
  { name: "sv_mvd_noblend", default: "0", flags: CVAR_LATCH },
  { name: "sv_mvd_nogun", default: "0", flags: CVAR_LATCH },
  { name: "sv_mvd_nomsgs", default: "1", flags: CVAR_LATCH },
  { name: "sv_mvd_password", default: "", flags: CVAR_PRIVATE },
  { name: "sv_mvd_scorecmd", default: "putaway; wait 10; help;", flags: 0 },
  { name: "sv_mvd_spawn_dummy", default: "1", flags: 0 },
  { name: "sv_mvd_suspend_time", default: "5", flags: 0 },
  { name: "sv_namechange_limit", default: "5/min", flags: 0 },
  { name: "sv_noreload", default: "0", flags: 0 },
  { name: "sv_novis", default: "0", flags: 0 },
  { name: "sv_packetdup_hack", default: "0", flags: 0 },
  { name: "sv_pad_packets", default: "0", flags: 0 },
  { name: "sv_password", default: "", flags: CVAR_PRIVATE },
  { name: "sv_paused", default: "0", flags: CVAR_ROM },
  { name: "sv_prioritize_entities", default: "0", flags: 0 },
  { name: "sv_qwmod", default: "0", flags: CVAR_LATCH },
  { name: "sv_rcon_limit", default: "1", flags: 0 },
  { name: "sv_recycle", default: "0", flags: 0 },
  { name: "sv_redirect_address", default: "", flags: 0 },
  { name: "sv_reserved_password", default: "", flags: CVAR_PRIVATE },
  { name: "sv_reserved_slots", default: "0", flags: CVAR_LATCH },
  { name: "sv_running", default: "0", flags: CVAR_ROM },
  { name: "sv_show_name_changes", default: "0", flags: 0 },
  { name: "sv_status_limit", default: "15", flags: 0 },
  { name: "sv_status_show", default: "2", flags: 0 },
  { name: "sv_strafejump_hack", default: "1", flags: CVAR_LATCH },
  { name: "sv_tick_rate", default: "40", flags: CVAR_LATCH },
  { name: "sv_timescale_kick", default: "0", flags: 0 },
  { name: "sv_timescale_time", default: "16", flags: 0 },
  { name: "sv_timescale_warn", default: "0", flags: 0 },
  { name: "sv_trunc_packet_entities", default: "1", flags: 0 },
  { name: "sv_uptime", default: "0", flags: 0 },
  { name: "sv_waterjump_hack", default: "1", flags: CVAR_LATCH },
  { name: "sys_allow_unsafe_savegames", default: "0", flags: CVAR_NOSET },
  { name: "sys_console", default: "0", flags: CVAR_NOSET },
  { name: "sys_forcegamelib", default: "", flags: CVAR_NOSET },
  { name: "sys_history", default: "128", flags: 0 },
  { name: "timedemo", default: "0", flags: 0 },
  { name: "timegraph", default: "0", flags: 0 },
  { name: "timelimit", default: "0", flags: CVAR_SERVERINFO },
  { name: "timeout", default: "90", flags: 0 },
  { name: "timescale", default: "1", flags: CVAR_CHEAT },
  { name: "uf", default: "", flags: CVAR_USERINFO },
  { name: "ui_colorservers", default: "0", flags: 0 },
  { name: "ui_debug", default: "0", flags: 0 },
  { name: "ui_listalldemos", default: "0", flags: 0 },
  { name: "ui_open", default: "0", flags: 0 },
  { name: "ui_pingrate", default: "0", flags: 0 },
  { name: "ui_scale", default: "0", flags: 0 },
  { name: "ui_sortdemos", default: "1", flags: 0 },
  { name: "ui_sortservers", default: "0", flags: 0 },
  { name: "vid_driver", default: "", flags: CVAR_REFRESH },
  { name: "vid_fullscreen", default: "0", flags: CVAR_ARCHIVE },
  { name: "vid_geometry", default: "640x480", flags: CVAR_ARCHIVE },
  { name: "vid_hwgamma", default: "0", flags: CVAR_REFRESH },
  { name: "vid_modelist", default: "", flags: 0 },
  { name: "viewsize", default: "100", flags: CVAR_ARCHIVE },
  { name: "wc_ammo_scale", default: "0.66", flags: 0 },
  { name: "wc_lock_time", default: "300", flags: 0 },
  { name: "wc_screen_frac_y", default: "0.72", flags: 0 },
  { name: "wc_timeout", default: "400", flags: 0 },
  { name: "ww_ammo_scale", default: "0.66", flags: 0 },
  { name: "ww_timer_speed", default: "3", flags: 0 },
  { name: "zombietime", default: "2", flags: 0 },
];

describe("cvar parity audit -- full engine boot", () => {
  let tmpRoot = "";
  let fsSnapshot: FsSearchPathSnapshotT;

  beforeAll(async () => {
    // rule 13 (process-wide singleton leak, closed at the source): this
    // suite boots a real, non-dedicated client+server (see this file's
    // header comment) against its own throwaway tmpRoot basedir --
    // src/qcommon/files.ts's fs_searchpaths/fs_base_searchpaths never get
    // that mount removed on their own (see files.ts's
    // FS_TestSnapshotSearchPaths/FS_TestRestoreSearchPaths header comment).
    // Snapshot before ANY mutation below. NOT extended to the cvar_vars
    // registry: this suite's whole point is registering the full manifest
    // of cvars, and the rest of this test run relies on that registration
    // staying around afterward (vid_modes.test.ts's own header comment
    // documents the same "accumulates across files, never resets"
    // contract) -- wiping cvar_vars here doesn't just clean up after this
    // file, it un-registers cvars other, unrelated files also depend on
    // having been registered by *some* earlier boot.
    fsSnapshot = FS_TestSnapshotSearchPaths();

    tmpRoot = mkdtempSync(join(tmpdir(), "q2cvarparity-"));
    const baseq2Dir = join(tmpRoot, "baseq2");
    mkdirSync(join(baseq2Dir, "maps"), { recursive: true });
    mkdirSync(join(baseq2Dir, "pics"), { recursive: true });
    writeFileSync(join(baseq2Dir, "maps", "cvarparity.bsp"), buildBoxRoomBsp(WORLDSPAWN_ONLY_ENTITIES, { renderable: true }));
    writeFileSync(join(baseq2Dir, "pics", "colormap.pcx"), buildColormapPcx());
    // FS search paths persist for the whole `bun test` process (see
    // src/qcommon/files.ts's fs_searchpaths, never reset/cleared) -- on a
    // dev host with a real Quake 2 install already registered as a search
    // path by an earlier test file in the same run, "exec default.cfg"/
    // "exec config.cfg" below would otherwise silently fall through to that
    // *real* config and "set" userinfo cvars (name/sensitivity/fov/hand/
    // developer/skill/etc.) away from their q2repro defaults before this
    // test ever checks them. This test's own basedir is added on top of the
    // search-path list (newest paths are searched first), so shipping empty
    // stubs here wins over any older real ones and keeps this boot's cvar
    // state pristine.
    writeFileSync(join(baseq2Dir, "default.cfg"), "");
    writeFileSync(join(baseq2Dir, "config.cfg"), "");

    // basedir/port/dedicated are CVAR_NOSET, and a sibling test file's own
    // boot (bun runs every test file in one process, per this same
    // repo's other integration tests' identical defensive comment -- see
    // test/boot.test.ts) may already have registered them to a real
    // installed game's basedir or left dedicated=1 -- plain "+set" respects
    // NOSET and would silently no-op ("basedir is write protected"),
    // leaving this boot pointed at someone else's real game data. Force
    // past that the same way test/boot.test.ts/test/sdl_platform.test.ts
    // do. coop/deathmatch are forced too, for the same cross-file-leftover
    // reason, but to the exact values this test's manifest checks are
    // written against anyway (q2repro's own true defaults for both, "0"),
    // so forcing them changes nothing this test asserts.
    Cvar_ForceSet("basedir", tmpRoot);
    Cvar_ForceSet("game", "");
    Cvar_ForceSet("port", "0");
    Cvar_ForceSet("dedicated", "0");
    Cvar_ForceSet("coop", "0");
    Cvar_ForceSet("deathmatch", "0");

    // No coop/deathmatch/dedicated VALUE overrides beyond restoring their
    // own true q2repro defaults above: this map has no monsters, so a real
    // singleplayer boot (deathmatch "0", coop "0", dedicated "0" on this
    // port's client-capable USE_CLIENT branch) works cleanly, letting this
    // test check those three for real rather than needing a different
    // value forced over them for the boot to succeed. basedir must still
    // point at the scratch directory (its own manifest check below is
    // flags-only for exactly this reason).
    Qcommon_Init(["quake2", "+set", "basedir", tmpRoot, "+set", "port", "0", "+map", "cvarparity"]);

    for (let i = 0; i < 300 && sv.state !== ServerStateT.ss_game; i++) {
      Qcommon_Frame(100);
      await Bun.sleep(1);
    }
    expect(sv.state).toBe(ServerStateT.ss_game);

    // Not reachable through the boot above -- see this file's header.
    MapDB_Init();
    // rule 13: force cd_ogg.ts's own registration latch to re-run
    // regardless of what any earlier test in this process already did to
    // it (see CDAudio_TestResetRegistration's own header comment) -- this
    // suite's whole point is verifying ogg_enable/ogg_volume/ogg_shuffle/
    // ogg_menu_track/ogg_remap_tracks actually get registered here.
    CDAudio_TestResetRegistration();
    CDAudio_Play(0, false);
    // src/server/sv_mvd.ts's sv_mvd_spawn_dummy/sv_mvd_password/
    // sv_mvd_maxclients/sv_mvd_nomsgs predate this audit and register lazily
    // (svMvdSpawnDummyCvar/svMvdPasswordCvar/svMvdMaxClientsCvar/
    // svMvdNomsgsCvar, module-private, only called from GTV-connection and
    // dummy-spawn code paths this synthetic single-player boot never
    // exercises) -- unlike every other sv_mvd.ts cvar in this manifest,
    // which SV_MvdRegister (called from SV_Init) always registers eagerly.
    // Proxied here with the exact same name/default/flags those functions
    // use, since driving a real GTV connection is out of scope for this test.
    Cvar_Get("sv_mvd_spawn_dummy", "1", 0);
    Cvar_Get("sv_mvd_password", "", CVAR_PRIVATE);
    Cvar_Get("sv_mvd_maxclients", "8", CVAR_LATCH);
    Cvar_Get("sv_mvd_nomsgs", "1", CVAR_LATCH);

    const realRi: RefImports = {
      Sys_Error(_level: number, str: string): never {
        throw new Error(str);
      },
      Cmd_AddCommand(): void {},
      Cmd_RemoveCommand(): void {},
      Cmd_Argc(): number {
        return 0;
      },
      Cmd_Argv(): string {
        return "";
      },
      Cmd_ExecuteText(): void {},
      Con_Printf(): void {},
      // Real FS_LoadFile/FS_Gamedir (not stubs): GL_InitImages' Draw_GetPalette
      // needs to actually find pics/colormap.pcx, the same fixture file the
      // main boot above already wrote under tmpRoot/baseq2/pics/.
      FS_LoadFile(name: string): { length: number; data: Uint8Array | null } {
        // q2repro src/refresh/texture.c's 16-bit->8-bit color-quantization
        // table (pics/16to8.dat, 65536 bytes) is only consulted when
        // qglColorTableEXT is set, which QGLRecording's stub always leaves
        // falsy -- but GL_InitImages' `if (qgl.qglColorTableEXT)` branch is
        // read defensively either way. This fixture has no such asset;
        // synthesize a zero-filled buffer of the right size so the load
        // "succeeds" (its contents are never meaningfully read without a
        // real GL context uploading a color table with it).
        if (name === "pics/16to8.dat") {
          return { length: 65536, data: new Uint8Array(65536) };
        }
        const data = FS_LoadFile(name);
        if (!data) return { length: -1, data: null };
        return { length: data.length, data };
      },
      FS_FreeFile,
      FS_Gamedir,
      Cvar_Get,
      Cvar_Set,
      Cvar_SetValue,
      Vid_GetModeInfo(): { width: number; height: number } | null {
        return null;
      },
      Vid_MenuInit(): void {},
      Vid_NewWindow(): void {},
    };
    SetRefImports(realRi);
    // test/gl_image.test.ts's own precedent: QGLRecording (src/ref_gl/qgl.ts)
    // is a no-op/recording stand-in implementing the full QGL surface, so
    // GL_InitImages' post-registration texture-extension probing (which
    // needs *some* qgl object, not a real GL context) doesn't crash.
    SetQGL(new QGLRecording());
    R_Register();
    GL_InitImages();
    // src/platform/glimp.ts's GLimp_SetMode registers these same six
    // (src/refresh/main.c:1487-1510's R_GetGLConfig, cited identically in
    // both files) but only as part of creating a real SDL/GL window, too
    // heavy to drive here -- registered directly against the same `ri` as
    // a documented proxy for that call site (see this file's header).
    Cvar_Get("gl_colorbits", "0", CVAR_REFRESH);
    Cvar_Get("gl_depthbits", "0", CVAR_REFRESH);
    Cvar_Get("gl_stencilbits", "8", CVAR_REFRESH);
    Cvar_Get("gl_multisamples", "0", CVAR_REFRESH);
    Cvar_Get("gl_debug", "0", CVAR_REFRESH);
    Cvar_Get("gl_profile", "", CVAR_REFRESH);
  });

  afterAll(async () => {
    SV_Shutdown("cvar parity test finished\n", false);
    NET_ClearLoopback();
    await NET_Shutdown();
    setRe(null);
    SDL_ResetBackendForTests();
    // Unmount the fs_searchpaths layer this boot added (see beforeAll).
    FS_TestRestoreSearchPaths(fsSnapshot);
    rmSync(tmpRoot, { recursive: true, force: true });
  });

  test("every manifest cvar is registered with its q2repro-exact default and at least its q2repro-exact flags", () => {
    const missing: string[] = [];
    const badDefault: string[] = [];
    const badFlags: string[] = [];

    for (const entry of MANIFEST) {
      const v: CvarT | undefined = cvar_vars.get(entry.name);
      if (!v) {
        missing.push(entry.name);
        continue;
      }
      if (v.default_string !== entry.default) {
        badDefault.push(`${entry.name}: expected "${entry.default}", got "${v.default_string}"`);
      }
      // Flags are checked as "at least" (superset), not exact equality:
      // Cvar_Get ORs flags from every registration site into the same
      // cvar, and a handful of shared names (documented in this audit's
      // report) are legitimately registered from more than one site.
      if ((v.flags & entry.flags) !== entry.flags) {
        badFlags.push(`${entry.name}: expected flags to include ${entry.flags}, got ${v.flags}`);
      }
    }

    expect(missing).toEqual([]);
    expect(badDefault).toEqual([]);
    expect(badFlags).toEqual([]);
  });

  test("q2repro-dynamic-default cvars (STRINGIFY/va()/build-config macros) resolve to this build's real values", () => {
    // Checked via default_string (the value each was first Cvar_Get'd with,
    // see q_shared.ts's CvarT), not string (the live, settable value):
    // sibling test files sharing this same process's cvar_vars registry may
    // legitimately Cvar_Set some of these to something else by the time
    // this test runs, which would make a `.string` check spuriously fail
    // without indicating any real registration defect. The main manifest
    // test above does the same.

    // src/qcommon/qcommon.ts:29's PROTOCOL_VERSION import is the same one
    // both cl_main.ts's "cl_protocol" and sv_main.ts's "protocol" use.
    expect(cvar_vars.get("cl_protocol")?.default_string).toBe(`${PROTOCOL_VERSION}`);
    expect(cvar_vars.get("protocol")?.default_string).toBe(`${PROTOCOL_VERSION}`);
    expect(cvar_vars.get("protocol")?.flags).toBe(CVAR_SERVERINFO | CVAR_ROM);

    // q2repro src/server/main.c:2112: va("%i", DF_INSTANT_ITEMS)
    const dmflags = cvar_vars.get("dmflags");
    expect(dmflags?.default_string).toBe(`${DF_INSTANT_ITEMS}`);
    expect((dmflags?.flags ?? 0) & CVAR_SERVERINFO).toBe(CVAR_SERVERINFO);

    // q2repro src/common/net/net.c:1833,1837: STRINGIFY(PORT_SERVER)/STRINGIFY(PORT_ANY)
    expect(cvar_vars.get("net_port")?.default_string).toBe(String(PORT_SERVER));
    expect(cvar_vars.get("net_clientport")?.default_string).toBe(String(PORT_ANY));

    // q2repro src/unix/system.c:210: `homedir = Cvar_Get("homedir", homedir, CVAR_NOSET);`
    // -- but this expectation predates the homedir landing's actual,
    // deliberate registration. src/platform/sys.ts's Sys_GetDefaultHomedir
    // (cited there at length) establishes that BOTH reference platforms
    // resolve their HOMEDIR macro to "" for this port's deployment shape
    // (no `-Dsystem-wide` build variant, no packaged-install detection), so
    // files.ts's FS_InitFilesystem registers "homedir" CVAR_NOSET with an
    // empty default_string, matching q2repro's own ordinary (non-packaged)
    // build on both of its platforms -- not the real OS home directory.
    expect(cvar_vars.get("homedir")?.default_string).toBe("");
    expect(cvar_vars.get("homedir")?.flags).toBe(CVAR_NOSET);

    // q2repro src/server/main.c:2178: COM_DEDICATED ? "0" : "1". Unlike
    // every other check in this test, sv_allow_map's C default itself
    // depends on another cvar's *live value* (dedicated.value) at the
    // moment sv_allow_map is first registered -- so if a sibling test file
    // elsewhere in this same process happens to register it first while
    // booted dedicated, its permanently-recorded default_string legitimately
    // reflects that earlier boot's condition, not this one. Existence and
    // shape checked instead of a specific value for exactly that reason.
    const svAllowMap = cvar_vars.get("sv_allow_map");
    expect(svAllowMap).toBeDefined();
    expect(["0", "1"]).toContain(svAllowMap?.default_string ?? "");

    // q2repro src/common/common.c:945 -- com_version_string, a full
    // "version cpu date" banner this port composes differently
    // (src/main.ts's Com_sprintf("%4.2f %s %s", ...)); only flags and
    // non-emptiness are checked, not the exact banner text.
    const version = cvar_vars.get("version");
    expect(version?.flags).toBe(CVAR_SERVERINFO | CVAR_ROM);
    expect(version?.default_string.length ?? 0).toBeGreaterThan(0);
  });

  test("basedir is registered with q2repro's CVAR_NOSET flag (default not checked -- this test overrides it to the scratch directory)", () => {
    const v = cvar_vars.get("basedir");
    expect(v).toBeDefined();
    expect(v?.flags).toBe(CVAR_NOSET);
  });

  test("maxclients is registered with q2repro's default \"8\" (src/server/main.c:2116), flags-only check here", () => {
    // src/server/sv_init.ts's SV_InitGame unconditionally re-derives
    // maxclients from the deathmatch/coop mode on every boot (vanilla q2's
    // own SV_InitGame behavior, not a bug): non-deathmatch/non-coop always
    // forces it to "1". This test boots true singleplayer (no monsters, so
    // it never needed to force coop/deathmatch away from their own
    // defaults), which means maxclients' registered default of "8" is
    // immediately overwritten by that same forcing logic before this
    // assertion runs -- checked via CVAR_SERVERINFO|CVAR_LATCH here, not
    // its now-necessarily-"1" runtime value.
    const v = cvar_vars.get("maxclients");
    expect(v).toBeDefined();
    expect((v?.flags ?? 0) & (CVAR_SERVERINFO | CVAR_LATCH)).toBe(CVAR_SERVERINFO | CVAR_LATCH);
  });

  test("coop/dedicated are registered with q2repro's flags (default not checked -- see this test's own header comment)", () => {
    // Both are legitimate boot-configuration knobs that other integration
    // test files in this same shared `bun test` process routinely register
    // first with a *different* default (e.g. a dedicated-server-focused
    // suite calling Cvar_Get("dedicated", "1", ...) before this file's own
    // Qcommon_Init ever runs) -- default_string is set once, at whichever
    // call happens first process-wide, so it can legitimately carry that
    // other suite's condition instead of q2repro's "0"/"0". Flags are
    // unaffected by which site registered first (Cvar_Get always ORs them
    // in), so those are still checked exactly.
    const coop = cvar_vars.get("coop");
    expect(coop).toBeDefined();
    expect(coop?.flags).toBe(CVAR_LATCH);

    const dedicated = cvar_vars.get("dedicated");
    expect(dedicated).toBeDefined();
    expect(dedicated?.flags).toBe(CVAR_NOSET);
  });

  test("vid_ref: judgment-call divergence, not auto-fixed -- documented here instead of asserted as a regression", () => {
    // q2repro src/client/refresh.c:338 registers vid_ref "gl" CVAR_ROM: it
    // ships exactly one renderer, compiled in, never switchable. This port
    // deliberately supports two (ref_gl and ref_soft, switchable via this
    // same cvar) and defaults to "soft" with CVAR_ARCHIVE so the choice
    // persists -- a real feature q2repro dropped, not an oversight. Forcing
    // q2repro's default/flags here would silently disable that switch for
    // every fresh install. See the audit report's judgment-call section.
    const v = cvar_vars.get("vid_ref");
    expect(v).toBeDefined();
    expect(v?.default_string).toBe("soft");
    expect((v?.flags ?? 0) & CVAR_ARCHIVE).toBe(CVAR_ARCHIVE);
  });

  test("intensity: judgment-call divergence, not auto-fixed -- vanilla's \"2\", because this renderer has vanilla's mechanism", () => {
    // q2repro src/refresh/texture.c:1266 registers intensity "1", but it also
    // moved intensity out of the texture prescale: GL_BuildIntensityTable
    // (texture.c:955) builds an IDENTITY table whenever gl_static.use_shaders,
    // and shader.c:687 applies the value at draw time instead
    // (`diffuse.rgb *= u_intensity;`). "1" there means "no prescale,
    // brightness comes from the shader".
    //
    // ref_gl here is vanilla's fixed-function pipeline. gl_image.ts's
    // intensitytable is the ONLY place intensity is ever applied -- it
    // prescales world textures at upload so R_BlendLightmaps' second modulate
    // pass (GL_ZERO, GL_SRC_COLOR) lands back at the intended brightness, and
    // gl_state.inverse_intensity scales the un-lightmapped alpha/warp surfaces
    // to match. Taking q2repro's default without q2repro's shader-side
    // multiply left the world about half as bright (Mike's RC screenshot
    // report). vanilla gl_image.c:1503 is the correct citation for this
    // renderer: `intensity = ri.Cvar_Get ("intensity", "2", 0);`
    const v = cvar_vars.get("intensity");
    expect(v).toBeDefined();
    expect(v?.default_string).toBe("2");
    expect(v?.flags).toBe(0);
  });

  test("the new q2repro extended cvar flag bits this audit added exist and match inc/common/cvar.h's BIT(5)..BIT(15)", () => {
    expect(CVAR_CHEAT).toBe(32);
    expect(CVAR_PRIVATE).toBe(64);
    expect(CVAR_ROM).toBe(128);
    expect(CVAR_NOARCHIVE).toBe(4096);
    expect(CVAR_FILES).toBe(8192);
    expect(CVAR_REFRESH).toBe(16384);
    expect(CVAR_SOUND).toBe(32768);
  });

  test("CVAR_PRIVATE cvars carrying CVAR_LATCH/CVAR_SERVERINFO are excluded from the save-game cvar block (src/server/save.c:65-70 parity)", () => {
    // None of this port's currently-registered CVAR_PRIVATE cvars also
    // carry LATCH/SERVERINFO (sv_password, rcon_password, etc. are
    // CVAR_PRIVATE-only), so this is a defensive/structural check on the
    // exclusion logic itself (src/server/sv_ccmds.ts's
    // SV_WriteServerFileKex), not a behavioral one -- reproduces q2repro's
    // save.c defense against a future cvar someday combining both.
    for (const v of cvar_vars.values()) {
      if (v.flags & (CVAR_LATCH | CVAR_SERVERINFO)) {
        expect(v.flags & CVAR_PRIVATE).toBe(0);
      }
    }
  });
});
