// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
//
// m_berserk.c -- the BERSERK monster (2023 Quake II re-release / "KEX"
// engine). Ported from ~/Projects/quake2-rerelease-dll/rerelease/
// m_berserk.cpp (836 lines, C++17) + m_berserk.h (266 lines, frame index
// constants only -- "This file generated by ModelGen - Do NOT Modify").
// Every mframe_t table, every think/attack/pain/die handler, and
// SP_monster_berserk. Behavioral code, ported bug-for-bug per
// m_gladiator.ts's already-landed sibling conventions (import shape, local
// `cachedSoundindex`/`assignSound` helpers, `mkframe`, throwing-stub style).
//
// ============================================================================
// EXTERNAL DEPENDENCIES NOT YET PORTED (throwing stubs, cited)
// ============================================================================
// The KEX rerelease folded the ROGUE mission-pack's "new AI" blocking/dodge/
// duck/jump-prediction system into the BASE game monster set (soldier,
// infantry, gunner, berserk, gladiator all call into it now -- confirmed by
// grepping every m_*.cpp in the source tree), but that whole file,
// rogue/g_rogue_newai.cpp, is out of this porting round's scope (this unit
// is five monster files + a test file only; no src/kexgame/g_rogue_newai.ts
// exists yet). Every symbol below is declared in g_local.h but DEFINED only
// in rogue/g_rogue_newai.cpp -- confirmed by grepping every .cpp in the
// rerelease tree for each definition. Local throwing stubs, matching
// m_gladiator.ts's own `blocked_checkplat` stub precedent exactly:
// - `blocked_checkplat` (rogue/g_rogue_newai.cpp:14) -- identical stub to
//   m_gladiator.ts's own copy.
// - `monster_jump_finished` (rogue/g_rogue_newai.cpp:101)
// - `blocked_checkjump` + `blocked_jump_result_t` enum (g_local.h:2546-2554,
//   rogue/g_rogue_newai.cpp:123)
// - `PredictAim` (rogue/g_rogue_newai.cpp:1083)
// - `M_MonsterDodge` (rogue/g_rogue_newai.cpp:1304, a MONSTERINFO_DODGE
//   handler -- signature matches `MonsterinfoDodgeFn` so `self.monsterinfo.
//   dodge = M_MonsterDodge` still type-checks, same treatment g_turret.ts
//   gives its own `infantry_pain`/`infantry_stand` stubs)
// - `monster_duck_down`/`monster_duck_hold` (rogue/g_rogue_newai.cpp:1424,
//   1434)
// - `monster_duck_up` (rogue/g_rogue_newai.cpp:1442, a MONSTERINFO_UNDUCK
//   handler -- signature matches `MonsterinfoUnduckFn`)
// `monster_done_dodge` is ALSO a throwing stub here, for the same reason
// g_ai.ts already carries its own non-exported local stub for it (pending
// rogue/g_rogue_monster.cpp:98, a DIFFERENT rogue file than the newai one
// above) -- g_ai.ts's copy is not exported, so it can't be imported; this
// file needs its own copy of the identical stub.
//
// ============================================================================
// PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY -- see m_gladiator.ts header
// ============================================================================
// - `monster_footstep` (g_local.h:3282, `inline`) and `M_CheckGib`
//   (g_local.h:3521, `inline`) are trivial header-only helpers with no
//   rogue dependency -- reimplemented locally, exactly m_gladiator.ts's own
//   copies.
// - `giTraceline(start, end, passent, mask)` (g_local.h:136-139): the same
//   trivial `game_import_t::traceline` wrapper g_monster.ts's own local
//   (non-exported) copy documents; needed here by `berserk_attack_slam`.
//
// ============================================================================
// DEVIATIONS
// ============================================================================
// - `cached_soundindex` fields port as `{ index: 0 }` mutable boxes assigned
//   via a local `assignSound` helper -- m_gladiator.ts's own precedent.
// - `T_SlamRadiusDamage` (m_berserk.cpp:212-255): the C++ `point` parameter
//   is passed BY VALUE (`vec3_t point`, not `vec3_t &point`), so each call
//   gets one local copy that survives across the whole `while` loop --
//   `point[2] = ent->absmin[2]` on iteration N is NOT undone before
//   iteration N+1, so every subsequent entity's `v`/`dir` calculation in
//   the SAME call uses the PREVIOUS entity's absmin.z, not the original
//   impact point's z. Ported as one local mutable `point` copied once at
//   entry (`vec3(pointIn[0], pointIn[1], pointIn[2])`, matching this
//   codebase's established "Vec3 copy" idiom since a bare `=` would alias
//   the caller's array instead), then genuinely mutated in place across
//   loop iterations -- bug-for-bug, not a fresh copy per entity.
// - `blocked_jump_result_t` (g_local.h:2546-2551, `enum class`) is declared
//   locally as a plain object + type alias (this file's only consumer is
//   `berserk_jump`/`berserk_blocked`, both throwing-stub call sites today),
//   matching `GibTypeT`'s established object-enum idiom in this codebase
//   rather than a TS `enum`.
// - C++ `self->velocity = {}` (zero-init) -> `self.velocity = vec3(0, 0,
//   0)`, a genuinely fresh zeroed vector (not the shared `vec3_origin`
//   constant, which this codebase treats as a read-only default elsewhere).
// - Anonymous C++ lambdas inside `berserk_frames_run_attack1`'s thinkfunc
//   slots (m_berserk.cpp:425, 427, 428) become named local closures
//   (`berserk_run_attack1_frame1/3/4`) -- TS has no inline-lambda-as-table-
//   cell readability issue C++ doesn't already have, but named closures
//   keep this table's row count/structure diffable against the source.
// - `st.health_multiplier` -> `import { st } from "./g_spawn"` (the real,
//   shared spawn_temp_t global; g_spawn.ts already landed).
// - Frame index constants and `MODEL_SCALE` are local (non-exported) `const`s,
//   matching m_gladiator.ts's own precedent (not referenced elsewhere in
//   this porting batch, unlike m_player.ts/m_rider.ts's header-only ports).
//   Tests needing frame numbers read them off the exported `mmove_t`
//   objects' `firstframe`/`lastframe` fields instead.

import { vec3, type Vec3 } from "../shared/math";
import {
  type EdictT,
  type ModT,
  type PainFn,
  type DieFn,
  CombatStyleT,
  DamageflagsT,
  EntFlagsT,
  GibTypeT,
  ModIdT,
  MonsterAiFlagsT,
  MonsterAttackStateT,
  MovetypeT,
} from "./g_local";
import { ATTN_IDLE, ATTN_NORM, ContentsT, KexEntityEventT, KexMulticastT, KexTempEventT, type KexTraceT, MASK_SOLID, ServerCommandT, SolidT, SoundchanT, SvflagsT } from "../kexapi/game";
import { MELEE_DISTANCE, RANGE_NEAR, BlockedJumpResultT } from "./g_local";
import { MframeT, MmoveT } from "./g_local_types";
import { gi, level } from "./g_main_globals";
import {
  RegisterDie,
  RegisterMmove,
  RegisterMonsterinfoAttack,
  RegisterMonsterinfoBlocked,
  RegisterMonsterinfoDuck,
  RegisterMonsterinfoMelee,
  RegisterMonsterinfoRun,
  RegisterMonsterinfoSearch,
  RegisterMonsterinfoSetskin,
  RegisterMonsterinfoSidestep,
  RegisterMonsterinfoSight,
  RegisterMonsterinfoStand,
  RegisterMonsterinfoWalk,
  RegisterPain,
  RegisterThink,
  RegisterTouch,
} from "./g_save_registry";
import { ai_charge, ai_move, ai_run, ai_stand, ai_walk, range_to } from "./g_ai";
import { M_AllowSpawn, M_ProjectFlashSource, M_SetAnimation, M_ShouldReactToPain, monster_dead, walkmonster_start } from "./g_monster";
import { M_MonsterDodge, monster_duck_down, monster_duck_hold, monster_duck_up, monster_done_dodge } from "./m_soldier";
import { blocked_checkjump, monster_jump_finished } from "./rogue/g_rogue_newai";
import { blocked_checkplat, PredictAim } from "./m_supertank";
import { fire_hit } from "./g_weapon";
import { G_FreeEdict, findradius } from "./g_utils";
import { T_Damage, CanDamage } from "./g_combat";
import { ThrowGibs } from "./g_misc";
import { brandom, frandom, irandom } from "./q_std";
import { GTIME_ZERO, Gtime_add, Gtime_from_sec, type GTime } from "./gtime";
import { st } from "./g_spawn";
import { AngleVectors, closest_point_to_box, vec3_add, vec3_length, vec3_muls, vec3_normalized, vec3_sub, vectoyaw } from "./q_vec3";
import { type SpawnFlags, SpawnFlags_from, SpawnFlags_has } from "./spawnflags";

// ---------------------------------------------------------------------------
// m_berserk.h frame index constants (253 entries, FRAME_stand1 = 0). Pure
// data -- local to this file, matching m_gladiator.ts's precedent.
// ---------------------------------------------------------------------------

const FRAME_stand1 = 0;
const FRAME_stand5 = 4;
const FRAME_standb1 = 5;
const FRAME_standb20 = 24;
const FRAME_walkc1 = 25;
const FRAME_walkc11 = 35;
const FRAME_run1 = 36;
const FRAME_run6 = 41;
const FRAME_att_c1 = 76;
const FRAME_att_c8 = 83;
const FRAME_att_c9 = 84;
const FRAME_att_c20 = 95;
const FRAME_r_att1 = 110;
const FRAME_r_att13 = 122;
const FRAME_r_att18 = 127;
const FRAME_slam1 = 146;
const FRAME_slam3 = 148;
const FRAME_slam5 = 150;
const FRAME_slam18 = 163;
const FRAME_slam23 = 168;
const FRAME_duck1 = 169;
const FRAME_duck10 = 178;
const FRAME_fall2 = 180;
const FRAME_fall18 = 196;
const FRAME_painc1 = 199;
const FRAME_painc4 = 202;
const FRAME_painb1 = 203;
const FRAME_painb20 = 222;
const FRAME_death1 = 223;
const FRAME_death13 = 235;
const FRAME_deathc1 = 236;
const FRAME_deathc8 = 243;
// PGM
const FRAME_jump1 = 244;
const FRAME_jump9 = 252;
// PGM

const MODEL_SCALE = 1.0;

const SPAWNFLAG_BERSERK_NOJUMPING: SpawnFlags = SpawnFlags_from(8);

// ---------------------------------------------------------------------------
// EXTERNAL DEPENDENCIES NOT YET PORTED -- see file header
// ---------------------------------------------------------------------------

// BlockedJumpResultT / blocked_checkplat / blocked_checkjump /
// monster_jump_finished / PredictAim are now real imports from
// "./g_local" / "./rogue/g_rogue_newai" -- see file header for the swap
// note. (This file previously defined its own local, structurally-matching
// `BlockedJumpResultT` mock rather than importing the real enum from
// g_local.ts; that mock is deleted along with the throwing stubs.)

// `M_MonsterDodge`/`monster_duck_down`/`monster_duck_hold`/`monster_duck_up`/
// `monster_done_dodge` were ALL local throwing stubs here despite being
// genuinely reachable (self.monsterinfo.dodge/unduck wired below, and
// monster_duck_down/hold used directly as berserk_frames_duck thinkfuncs,
// monster_done_dodge called from berserk_run/berserk_melee/berserk_attack):
// every spawned berserk monster would crash the instant any of these paths
// fired. m_soldier.ts ported all five for real (monster-agnostic rogue-newai
// infrastructure, not soldier-specific) and exports them; imported here
// instead. This also avoids a duplicate "M_MonsterDodge"/"monster_duck_up"
// registration in g_save_registry.ts's global, name-keyed
// monsterinfo_dodge/monsterinfo_unduck registries, which would otherwise
// throw the instant this file and m_soldier.ts load together (as
// g_spawn.ts's real monster table does). See m_soldier.ts's own comments on
// these exports.

// ---------------------------------------------------------------------------
// PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY -- see file header
// ---------------------------------------------------------------------------

function monster_footstep(self: EdictT): void {
  if (self.groundentity !== null) self.s.event = KexEntityEventT.EV_OTHER_FOOTSTEP;
}

function M_CheckGib(self: EdictT, mod: ModT): boolean {
  if (self.deadflag) {
    if (mod.id === ModIdT.MOD_CRUSH) return true;
  }
  return self.health <= self.gib_health;
}

function giTraceline(start: Vec3, end: Vec3, passent: EdictT | null, mask: ContentsT): KexTraceT {
  return gi.trace(start, null, null, end, passent, mask);
}

const MOD_UNKNOWN: ModT = { id: ModIdT.MOD_UNKNOWN, friendly_fire: false, no_point_loss: false };

// ---------------------------------------------------------------------------
// small local helpers -- duplicated per-file, see m_gladiator.ts header
// ---------------------------------------------------------------------------

interface CachedSoundindex {
  index: number;
}
function cachedSoundindex(): CachedSoundindex {
  return { index: 0 };
}
function assignSound(cached: CachedSoundindex, name: string): void {
  cached.index = gi.soundindex(name);
}
function mkframe(aifunc: MframeT["aifunc"], dist = 0, thinkfunc: MframeT["thinkfunc"] = null): MframeT {
  return { aifunc, dist, thinkfunc, lerp_frame: -1 };
}
function angleVectorsFR(angles: Vec3): { forward: Vec3; right: Vec3 } {
  const forward = vec3(0, 0, 0);
  const right = vec3(0, 0, 0);
  AngleVectors(angles, forward, right, null);
  return { forward, right };
}

const sound_pain = cachedSoundindex();
const sound_die = cachedSoundindex();
const sound_idle = cachedSoundindex();
const sound_idle2 = cachedSoundindex();
const sound_punch = cachedSoundindex();
const sound_sight = cachedSoundindex();
const sound_search = cachedSoundindex();
const sound_thud = cachedSoundindex();
const sound_explod = cachedSoundindex();
const sound_jump = cachedSoundindex();

// ---------------------------------------------------------------------------
// sight / search
// ---------------------------------------------------------------------------

export const berserk_sight = RegisterMonsterinfoSight("berserk_sight", (self: EdictT, _other: EdictT): void => {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_sight.index, 1, ATTN_NORM, 0);
});

export const berserk_search = RegisterMonsterinfoSearch("berserk_search", (self: EdictT): void => {
  if (brandom()) gi.sound(self, SoundchanT.CHAN_VOICE, sound_idle2.index, 1, ATTN_NORM, 0);
  else gi.sound(self, SoundchanT.CHAN_VOICE, sound_search.index, 1, ATTN_NORM, 0);
});

// ---------------------------------------------------------------------------
// stand
// ---------------------------------------------------------------------------

const berserk_frames_stand: MframeT[] = [
  mkframe(ai_stand, 0, (self) => berserk_fidget(self)),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
];
export const berserk_move_stand = RegisterMmove(
  "berserk_move_stand",
  Object.assign(new MmoveT(), { firstframe: FRAME_stand1, lastframe: FRAME_stand5, frame: berserk_frames_stand, endfunc: null }),
);

export const berserk_stand = RegisterMonsterinfoStand("berserk_stand", (self: EdictT): void => {
  M_SetAnimation(self, berserk_move_stand, false);
});

const berserk_frames_stand_fidget: MframeT[] = Array.from({ length: 20 }, () => mkframe(ai_stand));
export const berserk_move_stand_fidget = RegisterMmove(
  "berserk_move_stand_fidget",
  Object.assign(new MmoveT(), { firstframe: FRAME_standb1, lastframe: FRAME_standb20, frame: berserk_frames_stand_fidget, endfunc: berserk_stand }),
);

function berserk_fidget(self: EdictT): void {
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) !== 0n) return;
  else if (self.enemy !== null) return;
  if (frandom() > 0.15) return;

  M_SetAnimation(self, berserk_move_stand_fidget, false);
  gi.sound(self, SoundchanT.CHAN_WEAPON, sound_idle.index, 1, ATTN_IDLE, 0);
}

// ---------------------------------------------------------------------------
// walk
// ---------------------------------------------------------------------------

const berserk_frames_walk: MframeT[] = [
  mkframe(ai_walk, 9.1),
  mkframe(ai_walk, 6.3),
  mkframe(ai_walk, 4.9),
  mkframe(ai_walk, 6.7, monster_footstep),
  mkframe(ai_walk, 6.0),
  mkframe(ai_walk, 8.2),
  mkframe(ai_walk, 7.2),
  mkframe(ai_walk, 6.1),
  mkframe(ai_walk, 4.9),
  mkframe(ai_walk, 4.7, monster_footstep),
  mkframe(ai_walk, 4.7),
];
export const berserk_move_walk = RegisterMmove(
  "berserk_move_walk",
  Object.assign(new MmoveT(), { firstframe: FRAME_walkc1, lastframe: FRAME_walkc11, frame: berserk_frames_walk, endfunc: null }),
);

export const berserk_walk = RegisterMonsterinfoWalk("berserk_walk", (self: EdictT): void => {
  M_SetAnimation(self, berserk_move_walk, false);
});

// ---------------------------------------------------------------------------
// run (m_berserk.cpp:113-135's "arm raised in air" alternate run is commented
// out in the C++ source itself -- "SKIPPED THIS FOR NOW!" -- not ported)
// ---------------------------------------------------------------------------

const berserk_frames_run1: MframeT[] = [
  mkframe(ai_run, 21),
  mkframe(ai_run, 11, monster_footstep),
  mkframe(ai_run, 21),
  mkframe(ai_run, 25, monster_done_dodge),
  mkframe(ai_run, 18, monster_footstep),
  mkframe(ai_run, 19),
];
export const berserk_move_run1 = RegisterMmove(
  "berserk_move_run1",
  Object.assign(new MmoveT(), { firstframe: FRAME_run1, lastframe: FRAME_run6, frame: berserk_frames_run1, endfunc: null }),
);

export const berserk_run = RegisterMonsterinfoRun("berserk_run", (self: EdictT): void => {
  monster_done_dodge(self);

  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) !== 0n) M_SetAnimation(self, berserk_move_stand, false);
  else M_SetAnimation(self, berserk_move_run1, false);
});

// ---------------------------------------------------------------------------
// melee attacks: spike (fast) and club (slow)
// ---------------------------------------------------------------------------

function berserk_attack_spike(self: EdictT): void {
  const aim: Vec3 = vec3(MELEE_DISTANCE, 0, -24);

  if (!fire_hit(self, aim, irandom(5, 11), 80)) {
    // Faster attack -- upwards and backwards
    self.monsterinfo.melee_debounce_time = Gtime_add(level.time, Gtime_from_sec(1.2));
  }
}

function berserk_swing(self: EdictT): void {
  gi.sound(self, SoundchanT.CHAN_WEAPON, sound_punch.index, 1, ATTN_NORM, 0);
}

const berserk_frames_attack_spike: MframeT[] = [
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, berserk_swing),
  mkframe(ai_charge, 0, berserk_attack_spike),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
];
export const berserk_move_attack_spike = RegisterMmove(
  "berserk_move_attack_spike",
  Object.assign(new MmoveT(), { firstframe: FRAME_att_c1, lastframe: FRAME_att_c8, frame: berserk_frames_attack_spike, endfunc: berserk_run }),
);

function berserk_attack_club(self: EdictT): void {
  const aim: Vec3 = vec3(MELEE_DISTANCE, self.mins[0], -4);

  if (!fire_hit(self, aim, irandom(15, 21), 400)) {
    // Slower attack
    self.monsterinfo.melee_debounce_time = Gtime_add(level.time, Gtime_from_sec(2.5));
  }
}

const berserk_frames_attack_club: MframeT[] = [
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, monster_footstep),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, berserk_swing),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, berserk_attack_club),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
];
export const berserk_move_attack_club = RegisterMmove(
  "berserk_move_attack_club",
  Object.assign(new MmoveT(), { firstframe: FRAME_att_c9, lastframe: FRAME_att_c20, frame: berserk_frames_attack_club, endfunc: berserk_run }),
);

// ---------------------------------------------------------------------------
// slam (jump attack) -- m_berserk.cpp:212-377
// ---------------------------------------------------------------------------

/** m_berserk.cpp:212-255 -- see file header's DEVIATIONS note on the
 *  persisting-mutation bug-for-bug behavior of `point`. */
function T_SlamRadiusDamage(pointIn: Vec3, inflictor: EdictT, attacker: EdictT, damage: number, kick: number, ignore: EdictT, radius: number, mod: ModT): void {
  const point = vec3(pointIn[0], pointIn[1], pointIn[2]); // by-value copy -- C++ mutates its own local across iterations
  let ent: EdictT | null = null;

  while ((ent = findradius(ent, inflictor.s.origin, radius * 2.0)) !== null) {
    if (ent === ignore) continue;
    if (!ent.takedamage) continue;
    if (!CanDamage(ent, inflictor)) continue;
    // don't hit players in mid air
    if (ent.client !== null && ent.groundentity === null) continue;

    const v = vec3_sub(closest_point_to_box(point, vec3_add(ent.s.origin, ent.mins), vec3_add(ent.s.origin, ent.maxs)), point);

    // calculate contribution amount
    const amount0 = Math.min(1.0, 1.0 - vec3_length(v) / radius);

    // too far away
    if (amount0 <= 0.0) continue;

    const amount = amount0 * amount0;

    // damage & kick are exponentially scaled
    const points = Math.max(1.0, damage * amount);

    const dir = vec3_normalized(vec3_sub(ent.s.origin, point));

    // keep the point at their feet so they always get knocked up -- mutates
    // `point` for THIS and every subsequent iteration, see file header
    point[2] = ent.absmin[2];

    T_Damage(ent, inflictor, attacker, dir, point, dir, Math.trunc(points), Math.trunc(kick * amount), DamageflagsT.DAMAGE_RADIUS, mod);

    if (ent.client !== null) ent.velocity[2] = Math.max(270.0, ent.velocity[2]);
  }
}

function berserk_attack_slam(self: EdictT): void {
  gi.sound(self, SoundchanT.CHAN_WEAPON, sound_thud.index, 1, ATTN_NORM, 0);
  gi.sound(self, SoundchanT.CHAN_AUTO, sound_explod.index, 0.75, ATTN_NORM, 0);
  gi.WriteByte(ServerCommandT.svc_temp_entity);
  gi.WriteByte(KexTempEventT.TE_BERSERK_SLAM);
  const { forward: f, right: r } = angleVectorsFR(self.s.angles);
  const start = M_ProjectFlashSource(self, vec3(20.0, -14.3, -21.0), f, r);
  const tr = giTraceline(self.s.origin, start, self, MASK_SOLID);
  gi.WritePosition(tr.endpos);
  gi.WriteDir(vec3(0.0, 0.0, 1.0));
  gi.multicast(tr.endpos, KexMulticastT.MULTICAST_PHS, false);
  self.gravity = 1.0;
  self.velocity = vec3(0, 0, 0);
  self.flags |= EntFlagsT.FL_KILL_VELOCITY;

  T_SlamRadiusDamage(tr.endpos, self, self, 8, 300.0, self, 165, MOD_UNKNOWN);
}

const berserk_jump_touch = RegisterTouch("berserk_jump_touch", (self: EdictT, _other: EdictT, _tr: KexTraceT, _otherTouchingSelf: boolean): void => {
  if (self.health <= 0) {
    self.touch = null;
    return;
  }

  if (self.groundentity !== null) {
    self.s.frame = FRAME_slam18;

    if (self.touch !== null) berserk_attack_slam(self);

    self.touch = null;
  }
});

function berserk_high_gravity(self: EdictT): void {
  if (self.velocity[2] < 0) self.gravity = 2.25 * (800.0 / level.gravity);
  else self.gravity = 5.25 * (800.0 / level.gravity);
}

function berserk_jump_takeoff(self: EdictT): void {
  if (self.enemy === null) return;

  // immediately turn to where we need to go
  const length = vec3_length(vec3_sub(self.s.origin, self.enemy.s.origin));
  const fwd_speed = length * 1.95;
  const dirOut: Vec3 = vec3(0, 0, 0);
  PredictAim(self, self.enemy, self.s.origin, fwd_speed, false, 0.0, dirOut, null);
  self.s.angles[1] = vectoyaw(dirOut);
  const forward = vec3(0, 0, 0);
  AngleVectors(self.s.angles, forward, null, null);
  self.s.origin[2] += 1;
  self.velocity = vec3_muls(forward, fwd_speed);
  self.velocity[2] = 450;
  self.groundentity = null;
  self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_DUCKED;
  self.monsterinfo.attack_finished = Gtime_add(level.time, Gtime_from_sec(3));
  self.touch = berserk_jump_touch;
  berserk_high_gravity(self);
}

function berserk_check_landing(self: EdictT): void {
  berserk_high_gravity(self);

  if (self.groundentity !== null) {
    self.monsterinfo.attack_finished = GTIME_ZERO;
    if (self.monsterinfo.unduck !== null) self.monsterinfo.unduck(self);
    self.s.frame = FRAME_slam18;
    if (self.touch !== null) {
      berserk_attack_slam(self);
      self.touch = null;
    }
    self.flags &= ~EntFlagsT.FL_KILL_VELOCITY;
    return;
  }

  if (level.time > self.monsterinfo.attack_finished) self.monsterinfo.nextframe = FRAME_slam3;
  else self.monsterinfo.nextframe = FRAME_slam5;
}

const berserk_frames_attack_strike: MframeT[] = [
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_move, 0, berserk_jump_takeoff),
  mkframe(ai_move, 0, berserk_high_gravity),
  mkframe(ai_move, 0, berserk_check_landing),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
];
export const berserk_move_attack_strike = RegisterMmove(
  "berserk_move_attack_strike",
  Object.assign(new MmoveT(), { firstframe: FRAME_slam1, lastframe: FRAME_slam23, frame: berserk_frames_attack_strike, endfunc: berserk_run }),
);

// ---------------------------------------------------------------------------
// melee dispatch + run-attack (charge-while-running) chain
// ---------------------------------------------------------------------------

export const berserk_melee = RegisterMonsterinfoMelee("berserk_melee", (self: EdictT): void => {
  if (self.monsterinfo.melee_debounce_time > level.time) {
    return;
    // if we're *almost* ready to land down the hammer from run-attack
    // don't switch us
  } else if (self.monsterinfo.active_move === berserk_move_run_attack1 && self.s.frame >= FRAME_r_att13) {
    self.monsterinfo.attack_state = MonsterAttackStateT.AS_STRAIGHT;
    self.monsterinfo.attack_finished = GTIME_ZERO;
    return;
  }

  monster_done_dodge(self);

  if (brandom()) M_SetAnimation(self, berserk_move_attack_spike, false);
  else M_SetAnimation(self, berserk_move_attack_club, false);
});

function berserk_run_attack_speed(self: EdictT): void {
  if (self.enemy !== null && range_to(self, self.enemy) < MELEE_DISTANCE) {
    self.monsterinfo.nextframe = self.s.frame + 6;
    monster_done_dodge(self);
  }
}

function berserk_run_swing(self: EdictT): void {
  berserk_swing(self);
  self.monsterinfo.melee_debounce_time = Gtime_add(level.time, Gtime_from_sec(0.6));

  if (self.monsterinfo.attack_state === MonsterAttackStateT.AS_SLIDING) {
    self.monsterinfo.attack_state = MonsterAttackStateT.AS_STRAIGHT;
    monster_done_dodge(self);
  }
}

function berserk_run_attack1_frame1(self: EdictT): void {
  berserk_run_attack_speed(self);
  monster_footstep(self);
}
function berserk_run_attack1_frame3(self: EdictT): void {
  berserk_run_attack_speed(self);
  monster_done_dodge(self);
}
function berserk_run_attack1_frame4(self: EdictT): void {
  berserk_run_attack_speed(self);
  monster_footstep(self);
}

const berserk_frames_run_attack1: MframeT[] = [
  mkframe(ai_run, 21, berserk_run_attack_speed),
  mkframe(ai_run, 11, berserk_run_attack1_frame1),
  mkframe(ai_run, 21, berserk_run_attack_speed),
  mkframe(ai_run, 25, berserk_run_attack1_frame3),
  mkframe(ai_run, 18, berserk_run_attack1_frame4),
  mkframe(ai_run, 19, berserk_run_attack_speed),
  mkframe(ai_run, 21),
  mkframe(ai_run, 11, monster_footstep),
  mkframe(ai_run, 21),
  mkframe(ai_run, 25),
  mkframe(ai_run, 18, monster_footstep),
  mkframe(ai_run, 19),
  mkframe(ai_run, 21, berserk_run_swing),
  mkframe(ai_run, 11, monster_footstep),
  mkframe(ai_run, 21),
  mkframe(ai_run, 25),
  mkframe(ai_run, 18, monster_footstep),
  mkframe(ai_run, 19, berserk_attack_club),
];
export const berserk_move_run_attack1 = RegisterMmove(
  "berserk_move_run_attack1",
  Object.assign(new MmoveT(), { firstframe: FRAME_r_att1, lastframe: FRAME_r_att18, frame: berserk_frames_run_attack1, endfunc: berserk_run }),
);

export const berserk_attack = RegisterMonsterinfoAttack("berserk_attack", (self: EdictT): void => {
  if (self.enemy === null) return;

  if (self.monsterinfo.melee_debounce_time <= level.time && range_to(self, self.enemy) < MELEE_DISTANCE) {
    berserk_melee(self);
    // only jump if they are far enough away for it to make sense (otherwise
    // it gets annoying to have them keep hopping over and over again)
  } else if (!SpawnFlags_has(self.spawnflags, SPAWNFLAG_BERSERK_NOJUMPING) && self.timestamp < level.time && brandom() && range_to(self, self.enemy) > 150.0) {
    M_SetAnimation(self, berserk_move_attack_strike, false);
    // don't do this for a while, otherwise we just keep doing it
    gi.sound(self, SoundchanT.CHAN_WEAPON, sound_jump.index, 1, ATTN_NORM, 0);
    self.timestamp = Gtime_add(level.time, Gtime_from_sec(5));
  } else if (self.monsterinfo.active_move === berserk_move_run1 && range_to(self, self.enemy) <= RANGE_NEAR) {
    M_SetAnimation(self, berserk_move_run_attack1, false);
    self.monsterinfo.nextframe = FRAME_r_att1 + (self.s.frame - FRAME_run1) + 1;
  }
});

// ---------------------------------------------------------------------------
// pain
// ---------------------------------------------------------------------------

const berserk_frames_pain1: MframeT[] = [mkframe(ai_move), mkframe(ai_move), mkframe(ai_move), mkframe(ai_move)];
export const berserk_move_pain1 = RegisterMmove(
  "berserk_move_pain1",
  Object.assign(new MmoveT(), { firstframe: FRAME_painc1, lastframe: FRAME_painc4, frame: berserk_frames_pain1, endfunc: berserk_run }),
);

const berserk_frames_pain2: MframeT[] = [
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
];
export const berserk_move_pain2 = RegisterMmove(
  "berserk_move_pain2",
  Object.assign(new MmoveT(), { firstframe: FRAME_painb1, lastframe: FRAME_painb20, frame: berserk_frames_pain2, endfunc: berserk_run }),
);

export const berserk_pain: PainFn = RegisterPain("berserk_pain", (self: EdictT, _other: EdictT, _kick: number, damage: number, mod: ModT): void => {
  // if we're jumping, don't pain
  if (self.monsterinfo.active_move === berserk_move_jump || self.monsterinfo.active_move === berserk_move_jump2 || self.monsterinfo.active_move === berserk_move_attack_strike) {
    return;
  }

  if (level.time < self.pain_debounce_time) return;

  self.pain_debounce_time = Gtime_add(level.time, Gtime_from_sec(3));
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_pain.index, 1, ATTN_NORM, 0);

  if (!M_ShouldReactToPain(self, mod)) return; // no pain anims in nightmare

  monster_done_dodge(self);

  if (damage <= 50 || frandom() < 0.5) M_SetAnimation(self, berserk_move_pain1, false);
  else M_SetAnimation(self, berserk_move_pain2, false);
});

export const berserk_setskin = RegisterMonsterinfoSetskin("berserk_setskin", (self: EdictT): void => {
  if (self.health < self.max_health / 2) self.s.skinnum = 1;
  else self.s.skinnum = 0;
});

// ---------------------------------------------------------------------------
// death
// ---------------------------------------------------------------------------

export function berserk_dead(self: EdictT): void {
  self.mins = vec3(-16, -16, -24);
  self.maxs = vec3(16, 16, -8);
  monster_dead(self);
}

const berserk_shrink = RegisterThink("berserk_shrink", (self: EdictT): void => {
  self.maxs[2] = 0;
  self.svflags |= SvflagsT.SVF_DEADMONSTER;
  gi.linkentity(self);
});

const berserk_frames_death1: MframeT[] = [
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move, 0, berserk_shrink),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const berserk_move_death1 = RegisterMmove(
  "berserk_move_death1",
  Object.assign(new MmoveT(), { firstframe: FRAME_death1, lastframe: FRAME_death13, frame: berserk_frames_death1, endfunc: berserk_dead }),
);

const berserk_frames_death2: MframeT[] = [
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, berserk_shrink),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const berserk_move_death2 = RegisterMmove(
  "berserk_move_death2",
  Object.assign(new MmoveT(), { firstframe: FRAME_deathc1, lastframe: FRAME_deathc8, frame: berserk_frames_death2, endfunc: berserk_dead }),
);

export const berserk_die: DieFn = RegisterDie("berserk_die", (self: EdictT, _inflictor: EdictT, _attacker: EdictT, damage: number, _point: Vec3, mod: ModT): void => {
  if (M_CheckGib(self, mod)) {
    gi.sound(self, SoundchanT.CHAN_VOICE, gi.soundindex("misc/udeath.wav"), 1, ATTN_NORM, 0);

    self.s.skinnum = 0;

    ThrowGibs(self, damage, [
      { count: 2, gibname: "models/objects/gibs/bone/tris.md2" },
      { count: 3, gibname: "models/objects/gibs/sm_meat/tris.md2" },
      { count: 1, gibname: "models/objects/gibs/gear/tris.md2" },
      { gibname: "models/monsters/berserk/gibs/chest.md2", type: GibTypeT.GIB_SKINNED },
      { gibname: "models/monsters/berserk/gibs/hammer.md2", type: GibTypeT.GIB_SKINNED | GibTypeT.GIB_UPRIGHT },
      { gibname: "models/monsters/berserk/gibs/thigh.md2", type: GibTypeT.GIB_SKINNED },
      { gibname: "models/monsters/berserk/gibs/head.md2", type: GibTypeT.GIB_HEAD | GibTypeT.GIB_SKINNED },
    ]);
    self.deadflag = true;
    return;
  }

  if (self.deadflag) return;

  gi.sound(self, SoundchanT.CHAN_VOICE, sound_die.index, 1, ATTN_NORM, 0);
  self.deadflag = true;
  self.takedamage = true;

  if (damage >= 50) M_SetAnimation(self, berserk_move_death1, false);
  else M_SetAnimation(self, berserk_move_death2, false);
});

// ---------------------------------------------------------------------------
// PGM: jump-over-obstacle + blocked/sidestep/duck
// ---------------------------------------------------------------------------

function berserk_jump_now(self: EdictT): void {
  const forward = vec3(0, 0, 0);
  const up = vec3(0, 0, 0);
  AngleVectors(self.s.angles, forward, null, up);
  self.velocity = vec3_add(self.velocity, vec3_muls(forward, 100));
  self.velocity = vec3_add(self.velocity, vec3_muls(up, 300));
}

function berserk_jump2_now(self: EdictT): void {
  const forward = vec3(0, 0, 0);
  const up = vec3(0, 0, 0);
  AngleVectors(self.s.angles, forward, null, up);
  self.velocity = vec3_add(self.velocity, vec3_muls(forward, 150));
  self.velocity = vec3_add(self.velocity, vec3_muls(up, 400));
}

function berserk_jump_wait_land(self: EdictT): void {
  if (self.groundentity === null) {
    self.monsterinfo.nextframe = self.s.frame;

    if (monster_jump_finished(self)) self.monsterinfo.nextframe = self.s.frame + 1;
  } else {
    self.monsterinfo.nextframe = self.s.frame + 1;
  }
}

const berserk_frames_jump: MframeT[] = [
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, berserk_jump_now),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, berserk_jump_wait_land),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const berserk_move_jump = RegisterMmove(
  "berserk_move_jump",
  Object.assign(new MmoveT(), { firstframe: FRAME_jump1, lastframe: FRAME_jump9, frame: berserk_frames_jump, endfunc: berserk_run }),
);

const berserk_frames_jump2: MframeT[] = [
  mkframe(ai_move, -8),
  mkframe(ai_move, -4),
  mkframe(ai_move, -4),
  mkframe(ai_move, 0, berserk_jump2_now),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, berserk_jump_wait_land),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const berserk_move_jump2 = RegisterMmove(
  "berserk_move_jump2",
  Object.assign(new MmoveT(), { firstframe: FRAME_jump1, lastframe: FRAME_jump9, frame: berserk_frames_jump2, endfunc: berserk_run }),
);

function berserk_jump(self: EdictT, result: BlockedJumpResultT): void {
  if (self.enemy === null) return;

  if (result === BlockedJumpResultT.JUMP_JUMP_UP) M_SetAnimation(self, berserk_move_jump2, false);
  else M_SetAnimation(self, berserk_move_jump, false);
}

export const berserk_blocked = RegisterMonsterinfoBlocked("berserk_blocked", (self: EdictT, dist: number): boolean => {
  const result = blocked_checkjump(self, dist);
  if (result !== BlockedJumpResultT.NO_JUMP) {
    if (result !== BlockedJumpResultT.JUMP_TURN) berserk_jump(self, result);

    return true;
  }

  if (blocked_checkplat(self, dist)) return true;

  return false;
});

export const berserk_sidestep = RegisterMonsterinfoSidestep("berserk_sidestep", (self: EdictT): boolean => {
  // if we're jumping or in long pain, don't dodge
  if (
    self.monsterinfo.active_move === berserk_move_jump ||
    self.monsterinfo.active_move === berserk_move_jump2 ||
    self.monsterinfo.active_move === berserk_move_attack_strike ||
    self.monsterinfo.active_move === berserk_move_pain2
  ) {
    return false;
  }

  if (self.monsterinfo.active_move !== berserk_move_run1) M_SetAnimation(self, berserk_move_run1, false);

  return true;
});

const berserk_frames_duck: MframeT[] = [
  mkframe(ai_move, 0, monster_duck_down),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_duck_hold),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_duck_up),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const berserk_move_duck = RegisterMmove(
  "berserk_move_duck",
  Object.assign(new MmoveT(), { firstframe: FRAME_duck1, lastframe: FRAME_duck10, frame: berserk_frames_duck, endfunc: berserk_run }),
);

const berserk_frames_duck2: MframeT[] = [
  mkframe(ai_move, 21, monster_duck_down),
  mkframe(ai_move, 28),
  mkframe(ai_move, 20),
  mkframe(ai_move, 12, monster_footstep),
  mkframe(ai_move, 7),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_duck_hold),
  mkframe(ai_move, 0),
  mkframe(ai_move, 0),
  mkframe(ai_move, 0),
  mkframe(ai_move, 0),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move, 0, monster_duck_up),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
];
export const berserk_move_duck2 = RegisterMmove(
  "berserk_move_duck2",
  Object.assign(new MmoveT(), { firstframe: FRAME_fall2, lastframe: FRAME_fall18, frame: berserk_frames_duck2, endfunc: berserk_run }),
);

export const berserk_duck = RegisterMonsterinfoDuck("berserk_duck", (self: EdictT, _eta: GTime): boolean => {
  // berserk only dives forward, and very rarely
  if (frandom() >= 0.05) return false;

  // if we're jumping, don't dodge
  if (self.monsterinfo.active_move === berserk_move_jump || self.monsterinfo.active_move === berserk_move_jump2) return false;

  M_SetAnimation(self, berserk_move_duck2, false);

  return true;
});

// ---------------------------------------------------------------------------
// SP_monster_berserk (m_berserk.cpp:769-836)
// ---------------------------------------------------------------------------

/*QUAKED monster_berserk (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
 */
export function SP_monster_berserk(self: EdictT): void {
  if (!M_AllowSpawn(self)) {
    G_FreeEdict(self);
    return;
  }

  // pre-caches
  assignSound(sound_pain, "berserk/berpain2.wav");
  assignSound(sound_die, "berserk/berdeth2.wav");
  assignSound(sound_idle, "berserk/beridle1.wav");
  assignSound(sound_idle2, "berserk/idle.wav");
  assignSound(sound_punch, "berserk/attack.wav");
  assignSound(sound_search, "berserk/bersrch1.wav");
  assignSound(sound_sight, "berserk/sight.wav");
  assignSound(sound_thud, "mutant/thud1.wav");
  assignSound(sound_explod, "world/explod2.wav");
  assignSound(sound_jump, "berserk/jump.wav");

  self.s.modelindex = gi.modelindex("models/monsters/berserk/tris.md2");

  gi.modelindex("models/monsters/berserk/gibs/head.md2");
  gi.modelindex("models/monsters/berserk/gibs/chest.md2");
  gi.modelindex("models/monsters/berserk/gibs/hammer.md2");
  gi.modelindex("models/monsters/berserk/gibs/thigh.md2");

  self.mins = vec3(-16, -16, -24);
  self.maxs = vec3(16, 16, 32);
  self.movetype = MovetypeT.MOVETYPE_STEP;
  self.solid = SolidT.SOLID_BBOX;

  self.health = Math.trunc(240 * st.health_multiplier);
  self.gib_health = -60;
  self.mass = 250;

  self.pain = berserk_pain;
  self.die = berserk_die;

  self.monsterinfo.stand = berserk_stand;
  self.monsterinfo.walk = berserk_walk;
  self.monsterinfo.run = berserk_run;
  // pmm
  self.monsterinfo.dodge = M_MonsterDodge;
  self.monsterinfo.duck = berserk_duck;
  self.monsterinfo.unduck = monster_duck_up;
  self.monsterinfo.sidestep = berserk_sidestep;
  self.monsterinfo.blocked = berserk_blocked; // PGM
  // pmm
  self.monsterinfo.attack = berserk_attack;
  self.monsterinfo.melee = berserk_melee;
  self.monsterinfo.sight = berserk_sight;
  self.monsterinfo.search = berserk_search;
  self.monsterinfo.setskin = berserk_setskin;

  M_SetAnimation(self, berserk_move_stand, false);
  self.monsterinfo.scale = MODEL_SCALE;

  self.monsterinfo.combat_style = CombatStyleT.COMBAT_MELEE;
  self.monsterinfo.can_jump = !SpawnFlags_has(self.spawnflags, SPAWNFLAG_BERSERK_NOJUMPING);
  self.monsterinfo.drop_height = 256;
  self.monsterinfo.jump_height = 40;

  gi.linkentity(self);

  walkmonster_start(self);
}
