// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
//
// m_gladiator.c -- the GLADIATOR monster (2023 Quake II re-release / "KEX"
// engine). Ported from ~/Projects/quake2-rerelease-dll/rerelease/
// m_gladiator.cpp (488 lines, C++17) + m_gladiator.h (101 lines, frame index
// constants, "This file generated by ModelGen - Do NOT Modify"): the full
// stand/walk/run/melee(cleaver)/railgun-attack/pain/death frame-animation
// system, gladiator_pain/gladiator_die/gladiator_setskin/gladiator_blocked,
// and the RAFAEL (Ground Zero mission-pack) `monster_gladb` variant baked
// directly into this base-game file by KEX (distinct health/mass/skin/
// power-armor/weapon-sound stats, a `self->style` flag, and its own
// gladb-specific plasma-gun attack move). Behavioral code, ported bug-for-bug
// per PORTING.md.
//
// ============================================================================
// EXTERNAL DEPENDENCIES NOT YET PORTED (throwing stubs, cited)
// ============================================================================
// - `fire_plasma(self, start, dir, damage, speed, damage_radius,
//   radius_damage)`: declared in g_local.h:2339 but its ONLY body in the
//   whole rerelease source tree lives in
//   ~/Projects/quake2-rerelease-dll/rerelease/xatrix/g_xatrix_weapon.cpp:280
//   -- xatrix (Ground Zero's sibling mission pack) weapon content, out of
//   scope for this base-game monster porting round (no src/kexgame/
//   g_xatrix_weapon.ts exists). Only `gladbGun`/`gladbGun_check` (the
//   RAFAEL/gladb-only attack) reach this, so a base `monster_gladiator`
//   (self->style !== 1) never calls it. `monster_gladb` genuinely throws if
//   it ever fires its plasma gun today -- an honest gap, not a silent
//   behavior change, mirroring g_turret.ts's own `infantry_die`-family stub
//   precedent for the identical kind of missing-content-dir gap.
// - `blocked_checkplat(self, dist)`: declared in g_local.h:2544 but its ONLY
//   body in the whole rerelease source tree lives in
//   ~/Projects/quake2-rerelease-dll/rerelease/rogue/g_rogue_newai.cpp:14 --
//   rogue (Ground Zero) AI content, likewise out of scope here. Every
//   `monsterinfo.blocked` handler in the base game calls it (not
//   gladiator-specific), so `gladiator_blocked` genuinely throws if a plat
//   ever blocks this monster's path today.
//
// ============================================================================
// PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY
// ============================================================================
// - `monster_footstep(edict_t*)` (g_local.h:3282, `inline`, `[Paril-KEX]`):
//   `self->s.event = EV_OTHER_FOOTSTEP` if grounded. Trivial one-liner,
//   reimplemented locally rather than imported -- same treatment m_flipper.ts
//   gives `M_CheckGib` (see that file's header): declared in g_local.h, not
//   g_monster.cpp, so no earlier kexgame unit had a reason to port it yet.
// - `M_CheckGib(edict_t*, const mod_t&)` (g_local.h:3521, `inline`):
//   `self->deadflag && mod.id == MOD_CRUSH` short-circuits true, else
//   `self->health <= self->gib_health`. Reimplemented locally for the same
//   reason -- identical body to m_flipper.ts's own local copy.
//
// ============================================================================
// DEVIATIONS
// ============================================================================
// - `M_SetAnimation`'s C++ declaration (g_local.h:2211) defaults `instant` to
//   `true`; every call site in this file omits the arg, so every call here
//   passes `true` explicitly (TS has no default for this positional param
//   the way this codebase ports it elsewhere -- matching m_flipper.ts's own
//   `M_SetAnimation(self, move, true)` calls).
// - `cached_soundindex` fields port as plain per-file `let sound_x = 0`
//   module variables reassigned in `SP_monster_gladiator`, matching
//   m_flipper.ts's exact precedent (not g_trigger.ts's `{ index: 0 }` box,
//   which predates this simpler sibling convention).
// - `mframe_t`/`mmove_t` construction uses the local `frame()`/`move()`
//   helpers, matching m_flipper.ts's precedent exactly (MframeT is a plain
//   interface; MmoveT's frame-count validation happens in its `frame`
//   setter, so `move()` must assign `firstframe`/`lastframe` before `frame`).
// - Vec3 "copy" sites (`self->pos1 = self->enemy->s.origin`-shaped C++
//   value-semantics assignments) use `vec3(v[0], v[1], v[2])`, matching
//   g_turret.ts's own established idiom -- a `Vec3` is a mutable
//   `Float32Array`; a bare `=` would alias instead of copy.
// - `self->enemy` (nullable in `EdictT`) is narrowed via an explicit
//   `if (enemy === null) return` guard at the top of every function that
//   dereferences it, rather than a non-null assertion -- no casts anywhere
//   in this file besides `as const`.
// - `st` (spawn_temp_t) is the real, shared singleton imported from the
//   landed g_spawn.ts.

import { vec3, type Vec3 } from "../shared/math";
import {
  type EdictT,
  type ModT,
  type MframeAifuncFn,
  type MframeThinkfuncFn,
  type MmoveEndfuncFn,
  type PainFn,
  type DieFn,
  GibTypeT,
  ItemIdT,
  ModIdT,
  MonsterAiFlagsT,
  MovetypeT,
  MframeT,
  MmoveT,
  MELEE_DISTANCE,
} from "./g_local";
import { ATTN_IDLE, ATTN_NORM, KexEntityEventT, MonsterMuzzleflashIdT, SolidT, SoundchanT, SvflagsT } from "../kexapi/game";
import {
  RegisterMmove,
  RegisterThink,
  RegisterPain,
  RegisterDie,
  RegisterMonsterinfoStand,
  RegisterMonsterinfoWalk,
  RegisterMonsterinfoRun,
  RegisterMonsterinfoAttack,
  RegisterMonsterinfoMelee,
  RegisterMonsterinfoSight,
  RegisterMonsterinfoIdle,
  RegisterMonsterinfoSearch,
  RegisterMonsterinfoSetskin,
  RegisterMonsterinfoBlocked,
} from "./g_save_registry";
import { gi, level } from "./g_main_globals";
import { ai_charge, ai_move, ai_run, ai_stand, ai_walk } from "./g_ai";
import {
  M_AllowSpawn,
  M_CheckClearShot,
  M_ProjectFlashSource,
  M_SetAnimation,
  M_ShouldReactToPain,
  monster_dead,
  monster_fire_railgun,
  walkmonster_start,
} from "./g_monster";
import { fire_hit } from "./g_weapon";
import { ThrowGibs } from "./g_misc";
import { AngleVectors, vec3_normalized, vec3_sub } from "./q_vec3";
import { G_FreeEdict } from "./g_utils";
import { brandom, frandom, irandom } from "./q_std";
import { Gtime_add, Gtime_from_sec } from "./gtime";
import { monsterFlashOffset } from "./m_flash";
import { st } from "./g_spawn";

// ---------------------------------------------------------------------------
// m_gladiator.h frame index constants (98 entries, FRAME_stand1 = 0). Pure
// data -- local to this file (not referenced elsewhere in the porting
// batch), unlike m_player.ts/m_rider.ts's header-only ports.
// ---------------------------------------------------------------------------

const FRAME_stand1 = 0;
const FRAME_stand7 = 6;
const FRAME_walk1 = 7;
const FRAME_walk16 = 22;
const FRAME_run1 = 23;
const FRAME_run6 = 28;
const FRAME_melee3 = 31;
const FRAME_melee16 = 44;
const FRAME_attack1 = 46;
const FRAME_attack3 = 48;
const FRAME_attack9 = 54;
const FRAME_pain2 = 56;
const FRAME_pain5 = 59;
const FRAME_death2 = 62;
const FRAME_death22 = 82;
const FRAME_painup2 = 84;
const FRAME_painup6 = 88;

const MODEL_SCALE = 1.0;

// ---------------------------------------------------------------------------
// EXTERNAL DEPENDENCIES NOT YET PORTED -- see file header
// ---------------------------------------------------------------------------

function fire_plasma(_self: EdictT, _start: Vec3, _dir: Vec3, _damage: number, _speed: number, _damage_radius: number, _radius_damage: number): void {
  throw new Error("fire_plasma: not yet ported (xatrix mission-pack content, see xatrix/g_xatrix_weapon.cpp:280)");
}

function blocked_checkplat(_self: EdictT, _dist: number): boolean {
  throw new Error("blocked_checkplat: not yet ported (rogue mission-pack content, see rogue/g_rogue_newai.cpp:14)");
}

// ---------------------------------------------------------------------------
// PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY -- see file header
// ---------------------------------------------------------------------------

function monster_footstep(self: EdictT): void {
  if (self.groundentity !== null) self.s.event = KexEntityEventT.EV_OTHER_FOOTSTEP;
}

function M_CheckGib(self: EdictT, mod: ModT): boolean {
  if (self.deadflag) {
    if (mod.id === ModIdT.MOD_CRUSH) return true;
  }
  return self.health <= self.gib_health;
}

// ---------------------------------------------------------------------------
// local mframe_t / mmove_t helpers -- matches m_flipper.ts's precedent
// exactly (MframeT is a plain interface; MmoveT's frame-count validation
// happens in its `frame` setter).
// ---------------------------------------------------------------------------

function frame(aifunc: MframeAifuncFn | null, dist = 0, thinkfunc: MframeThinkfuncFn | null = null): MframeT {
  return { aifunc, dist, thinkfunc, lerp_frame: -1 };
}

function move(firstframe: number, lastframe: number, frames: MframeT[], endfunc: MmoveEndfuncFn | null = null): MmoveT {
  const m = new MmoveT();
  m.firstframe = firstframe;
  m.lastframe = lastframe;
  m.frame = frames;
  m.endfunc = endfunc;
  return m;
}

function angleVectorsFR(self: EdictT): { forward: Vec3; right: Vec3 } {
  const forward = vec3(0, 0, 0);
  const right = vec3(0, 0, 0);
  AngleVectors(self.s.angles, forward, right, null);
  return { forward, right };
}

function skillInt(): number {
  const c = gi.cvar("skill", "1", 0);
  return c === null ? 1 : Math.trunc(c.value);
}

let sound_pain1 = 0;
let sound_pain2 = 0;
let sound_die = 0;
let sound_die2 = 0;
let sound_gun = 0;
let sound_gunb = 0;
let sound_cleaver_swing = 0;
let sound_cleaver_hit = 0;
let sound_cleaver_miss = 0;
let sound_idle = 0;
let sound_search = 0;
let sound_sight = 0;

export const gladiator_idle = RegisterMonsterinfoIdle("gladiator_idle", (self: EdictT): void => {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_idle, 1, ATTN_IDLE, 0);
});

export const gladiator_sight = RegisterMonsterinfoSight("gladiator_sight", (self: EdictT, _other: EdictT): void => {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_sight, 1, ATTN_NORM, 0);
});

export const gladiator_search = RegisterMonsterinfoSearch("gladiator_search", (self: EdictT): void => {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_search, 1, ATTN_NORM, 0);
});

export function gladiator_cleaver_swing(self: EdictT): void {
  gi.sound(self, SoundchanT.CHAN_WEAPON, sound_cleaver_swing, 1, ATTN_NORM, 0);
}

// ---------------------------------------------------------------------------
// stand
// ---------------------------------------------------------------------------

const gladiator_frames_stand: MframeT[] = [frame(ai_stand), frame(ai_stand), frame(ai_stand), frame(ai_stand), frame(ai_stand), frame(ai_stand), frame(ai_stand)];
export const gladiator_move_stand = RegisterMmove("gladiator_move_stand", move(FRAME_stand1, FRAME_stand7, gladiator_frames_stand));

export const gladiator_stand = RegisterMonsterinfoStand("gladiator_stand", (self: EdictT): void => {
  M_SetAnimation(self, gladiator_move_stand, true);
});

// ---------------------------------------------------------------------------
// walk
// ---------------------------------------------------------------------------

const gladiator_frames_walk: MframeT[] = [
  frame(ai_walk, 15),
  frame(ai_walk, 7),
  frame(ai_walk, 6),
  frame(ai_walk, 5),
  frame(ai_walk, 2, monster_footstep),
  frame(ai_walk),
  frame(ai_walk, 2),
  frame(ai_walk, 8),
  frame(ai_walk, 12),
  frame(ai_walk, 8),
  frame(ai_walk, 5),
  frame(ai_walk, 5),
  frame(ai_walk, 2, monster_footstep),
  frame(ai_walk, 2),
  frame(ai_walk, 1),
  frame(ai_walk, 8),
];
export const gladiator_move_walk = RegisterMmove("gladiator_move_walk", move(FRAME_walk1, FRAME_walk16, gladiator_frames_walk));

export const gladiator_walk = RegisterMonsterinfoWalk("gladiator_walk", (self: EdictT): void => {
  M_SetAnimation(self, gladiator_move_walk, true);
});

// ---------------------------------------------------------------------------
// run
// ---------------------------------------------------------------------------

const gladiator_frames_run: MframeT[] = [
  frame(ai_run, 23),
  frame(ai_run, 14),
  frame(ai_run, 14, monster_footstep),
  frame(ai_run, 21),
  frame(ai_run, 12),
  frame(ai_run, 13, monster_footstep),
];
export const gladiator_move_run = RegisterMmove("gladiator_move_run", move(FRAME_run1, FRAME_run6, gladiator_frames_run));

export const gladiator_run = RegisterMonsterinfoRun("gladiator_run", (self: EdictT): void => {
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) !== 0n) M_SetAnimation(self, gladiator_move_stand, true);
  else M_SetAnimation(self, gladiator_move_run, true);
});

// ---------------------------------------------------------------------------
// melee (cleaver)
// ---------------------------------------------------------------------------

export function GladiatorMelee(self: EdictT): void {
  const aim = vec3(MELEE_DISTANCE, self.mins[0], -4);
  if (fire_hit(self, aim, irandom(20, 25), 300)) {
    gi.sound(self, SoundchanT.CHAN_AUTO, sound_cleaver_hit, 1, ATTN_NORM, 0);
  } else {
    gi.sound(self, SoundchanT.CHAN_AUTO, sound_cleaver_miss, 1, ATTN_NORM, 0);
    self.monsterinfo.melee_debounce_time = Gtime_add(level.time, Gtime_from_sec(1.5));
  }
}

const gladiator_frames_attack_melee: MframeT[] = [
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, gladiator_cleaver_swing),
  frame(ai_charge),
  frame(ai_charge, 0, GladiatorMelee),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, gladiator_cleaver_swing),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, GladiatorMelee),
  frame(ai_charge),
  frame(ai_charge),
];
export const gladiator_move_attack_melee = RegisterMmove(
  "gladiator_move_attack_melee",
  move(FRAME_melee3, FRAME_melee16, gladiator_frames_attack_melee, gladiator_run),
);

export const gladiator_melee = RegisterMonsterinfoMelee("gladiator_melee", (self: EdictT): void => {
  M_SetAnimation(self, gladiator_move_attack_melee, true);
});

// ---------------------------------------------------------------------------
// railgun attack (base gladiator)
// ---------------------------------------------------------------------------

export function GladiatorGun(self: EdictT): void {
  const { forward, right } = angleVectorsFR(self);
  const start = M_ProjectFlashSource(self, monsterFlashOffset()[MonsterMuzzleflashIdT.MZ2_GLADIATOR_RAILGUN_1], forward, right);

  // calc direction to where we targeted
  const dir = vec3_normalized(vec3_sub(self.pos1, start));

  monster_fire_railgun(self, start, dir, 50, 100, MonsterMuzzleflashIdT.MZ2_GLADIATOR_RAILGUN_1);
}

const gladiator_frames_attack_gun: MframeT[] = [
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, GladiatorGun),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, monster_footstep),
  frame(ai_charge),
];
export const gladiator_move_attack_gun = RegisterMmove("gladiator_move_attack_gun", move(FRAME_attack1, FRAME_attack9, gladiator_frames_attack_gun, gladiator_run));

// ---------------------------------------------------------------------------
// RAFAEL -- gladb plasma-gun attack (Ground Zero variant, baked into base file)
// ---------------------------------------------------------------------------

export function gladbGun(self: EdictT): void {
  const { forward, right } = angleVectorsFR(self);
  const start = M_ProjectFlashSource(self, monsterFlashOffset()[MonsterMuzzleflashIdT.MZ2_GLADIATOR_RAILGUN_1], forward, right);

  // calc direction to where we targeted
  const dir = vec3_normalized(vec3_sub(self.pos1, start));

  let damage = 35;
  let radius_damage = 45;

  if (self.s.frame > FRAME_attack3) {
    damage = Math.trunc(damage / 2);
    radius_damage = Math.trunc(radius_damage / 2);
  }

  fire_plasma(self, start, dir, damage, 725, radius_damage, radius_damage);

  // save for aiming the shot
  if (self.enemy === null) return;
  self.pos1 = vec3(self.enemy.s.origin[0], self.enemy.s.origin[1], self.enemy.s.origin[2]);
  self.pos1[2] += self.enemy.viewheight;
}

export function gladbGun_check(self: EdictT): void {
  if (skillInt() === 3) gladbGun(self);
}

const gladb_frames_attack_gun: MframeT[] = [
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, gladbGun),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, gladbGun),
  frame(ai_charge),
  frame(ai_charge),
  frame(ai_charge, 0, gladbGun_check),
];
export const gladb_move_attack_gun = RegisterMmove("gladb_move_attack_gun", move(FRAME_attack1, FRAME_attack9, gladb_frames_attack_gun, gladiator_run));

export const gladiator_attack = RegisterMonsterinfoAttack("gladiator_attack", (self: EdictT): void => {
  const enemy = self.enemy;
  if (enemy === null) return;

  // a small safe zone
  const v = vec3_sub(self.s.origin, enemy.s.origin);
  const range = Math.sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
  if (range <= MELEE_DISTANCE + 32 && self.monsterinfo.melee_debounce_time <= level.time) return;
  else if (!M_CheckClearShot(self, monsterFlashOffset()[MonsterMuzzleflashIdT.MZ2_GLADIATOR_RAILGUN_1])) return;

  // charge up the railgun -- save for aiming the shot
  self.pos1 = vec3(enemy.s.origin[0], enemy.s.origin[1], enemy.s.origin[2]);
  self.pos1[2] += enemy.viewheight;

  // RAFAEL
  if (self.style === 1) {
    gi.sound(self, SoundchanT.CHAN_WEAPON, sound_gunb, 1, ATTN_NORM, 0);
    M_SetAnimation(self, gladb_move_attack_gun, true);
  } else {
    gi.sound(self, SoundchanT.CHAN_WEAPON, sound_gun, 1, ATTN_NORM, 0);
    M_SetAnimation(self, gladiator_move_attack_gun, true);
  }
});

// ---------------------------------------------------------------------------
// pain
// ---------------------------------------------------------------------------

const gladiator_frames_pain: MframeT[] = [frame(ai_move), frame(ai_move), frame(ai_move), frame(ai_move)];
export const gladiator_move_pain = RegisterMmove("gladiator_move_pain", move(FRAME_pain2, FRAME_pain5, gladiator_frames_pain, gladiator_run));

const gladiator_frames_pain_air: MframeT[] = [frame(ai_move), frame(ai_move), frame(ai_move), frame(ai_move), frame(ai_move)];
export const gladiator_move_pain_air = RegisterMmove("gladiator_move_pain_air", move(FRAME_painup2, FRAME_painup6, gladiator_frames_pain_air, gladiator_run));

export const gladiator_pain: PainFn = RegisterPain("gladiator_pain", (self: EdictT, _other: EdictT, _kick: number, _damage: number, mod: ModT): void => {
  if (level.time < self.pain_debounce_time) {
    if (self.velocity[2] > 100 && self.monsterinfo.active_move === gladiator_move_pain) {
      M_SetAnimation(self, gladiator_move_pain_air, true);
    }
    return;
  }

  self.pain_debounce_time = Gtime_add(level.time, Gtime_from_sec(3));

  if (frandom() < 0.5) gi.sound(self, SoundchanT.CHAN_VOICE, sound_pain1, 1, ATTN_NORM, 0);
  else gi.sound(self, SoundchanT.CHAN_VOICE, sound_pain2, 1, ATTN_NORM, 0);

  if (!M_ShouldReactToPain(self, mod)) return; // no pain anims in nightmare

  if (self.velocity[2] > 100) M_SetAnimation(self, gladiator_move_pain_air, true);
  else M_SetAnimation(self, gladiator_move_pain, true);
});

export const gladiator_setskin = RegisterMonsterinfoSetskin("gladiator_setskin", (self: EdictT): void => {
  if (self.health < self.max_health / 2) self.s.skinnum |= 1;
  else self.s.skinnum &= ~1;
});

// ---------------------------------------------------------------------------
// death
// ---------------------------------------------------------------------------

export function gladiator_dead(self: EdictT): void {
  self.mins = vec3(-16, -16, -24);
  self.maxs = vec3(16, 16, -8);
  monster_dead(self);
}

const gladiator_shrink = RegisterThink("gladiator_shrink", (self: EdictT): void => {
  self.maxs[2] = 0;
  self.svflags |= SvflagsT.SVF_DEADMONSTER;
  gi.linkentity(self);
});

const gladiator_frames_death: MframeT[] = [
  frame(ai_move),
  frame(ai_move),
  frame(ai_move, 0, gladiator_shrink),
  frame(ai_move, 0, monster_footstep),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
  frame(ai_move),
];
export const gladiator_move_death = RegisterMmove("gladiator_move_death", move(FRAME_death2, FRAME_death22, gladiator_frames_death, gladiator_dead));

export const gladiator_die: DieFn = RegisterDie(
  "gladiator_die",
  (self: EdictT, _inflictor: EdictT, _attacker: EdictT, damage: number, _point: Vec3, mod: ModT): void => {
    // check for gib
    if (M_CheckGib(self, mod)) {
      gi.sound(self, SoundchanT.CHAN_VOICE, gi.soundindex("misc/udeath.wav"), 1, ATTN_NORM, 0);

      self.s.skinnum = Math.trunc(self.s.skinnum / 2);

      ThrowGibs(self, damage, [
        { count: 2, gibname: "models/objects/gibs/bone/tris.md2" },
        { count: 2, gibname: "models/objects/gibs/sm_meat/tris.md2" },
        { count: 2, gibname: "models/monsters/gladiatr/gibs/thigh.md2", type: GibTypeT.GIB_SKINNED },
        { gibname: "models/monsters/gladiatr/gibs/larm.md2", type: GibTypeT.GIB_SKINNED | GibTypeT.GIB_UPRIGHT },
        { gibname: "models/monsters/gladiatr/gibs/rarm.md2", type: GibTypeT.GIB_SKINNED | GibTypeT.GIB_UPRIGHT },
        { gibname: "models/monsters/gladiatr/gibs/chest.md2", type: GibTypeT.GIB_SKINNED },
        { gibname: "models/monsters/gladiatr/gibs/head.md2", type: GibTypeT.GIB_SKINNED | GibTypeT.GIB_HEAD },
      ]);
      self.deadflag = true;
      return;
    }

    if (self.deadflag) return;

    // regular death
    gi.sound(self, SoundchanT.CHAN_BODY, sound_die, 1, ATTN_NORM, 0);

    if (brandom()) gi.sound(self, SoundchanT.CHAN_VOICE, sound_die2, 1, ATTN_NORM, 0);

    self.deadflag = true;
    self.takedamage = true;

    M_SetAnimation(self, gladiator_move_death, true);
  },
);

// ===========
// PGM
export const gladiator_blocked = RegisterMonsterinfoBlocked("gladiator_blocked", (self: EdictT, dist: number): boolean => {
  if (blocked_checkplat(self, dist)) return true;
  return false;
});
// PGM
// ===========

/*QUAKED monster_gladiator (1 .5 0) (-32 -32 -24) (32 32 64) Ambush Trigger_Spawn Sight
 */
export function SP_monster_gladiator(self: EdictT): void {
  if (!M_AllowSpawn(self)) {
    G_FreeEdict(self);
    return;
  }

  sound_pain1 = gi.soundindex("gladiator/pain.wav");
  sound_pain2 = gi.soundindex("gladiator/gldpain2.wav");
  sound_die = gi.soundindex("gladiator/glddeth2.wav");
  sound_die2 = gi.soundindex("gladiator/death.wav");
  sound_cleaver_swing = gi.soundindex("gladiator/melee1.wav");
  sound_cleaver_hit = gi.soundindex("gladiator/melee2.wav");
  sound_cleaver_miss = gi.soundindex("gladiator/melee3.wav");
  sound_idle = gi.soundindex("gladiator/gldidle1.wav");
  sound_search = gi.soundindex("gladiator/gldsrch1.wav");
  sound_sight = gi.soundindex("gladiator/sight.wav");

  self.movetype = MovetypeT.MOVETYPE_STEP;
  self.solid = SolidT.SOLID_BBOX;
  self.s.modelindex = gi.modelindex("models/monsters/gladiatr/tris.md2");

  gi.modelindex("models/monsters/gladiatr/gibs/chest.md2");
  gi.modelindex("models/monsters/gladiatr/gibs/head.md2");
  gi.modelindex("models/monsters/gladiatr/gibs/larm.md2");
  gi.modelindex("models/monsters/gladiatr/gibs/rarm.md2");
  gi.modelindex("models/monsters/gladiatr/gibs/thigh.md2");

  // RAFAEL
  if (self.classname === "monster_gladb") {
    sound_gunb = gi.soundindex("weapons/plasshot.wav");

    self.health = Math.trunc(250 * st.health_multiplier);
    self.mass = 350;

    if (!st.keys_specified.has("power_armor_type")) self.monsterinfo.power_armor_type = ItemIdT.IT_ITEM_POWER_SHIELD;
    if (!st.keys_specified.has("power_armor_power")) self.monsterinfo.power_armor_power = 250;

    self.s.skinnum = 2;

    self.style = 1;

    self.monsterinfo.weapon_sound = gi.soundindex("weapons/phaloop.wav");
  } else {
    // RAFAEL
    sound_gun = gi.soundindex("gladiator/railgun.wav");

    self.health = Math.trunc(400 * st.health_multiplier);
    self.mass = 400;
    // RAFAEL

    self.monsterinfo.weapon_sound = gi.soundindex("weapons/rg_hum.wav");
  }
  // RAFAEL

  self.gib_health = -175;

  self.mins = vec3(-32, -32, -24);
  self.maxs = vec3(32, 32, 42);

  self.pain = gladiator_pain;
  self.die = gladiator_die;

  self.monsterinfo.stand = gladiator_stand;
  self.monsterinfo.walk = gladiator_walk;
  self.monsterinfo.run = gladiator_run;
  self.monsterinfo.dodge = null;
  self.monsterinfo.attack = gladiator_attack;
  self.monsterinfo.melee = gladiator_melee;
  self.monsterinfo.sight = gladiator_sight;
  self.monsterinfo.idle = gladiator_idle;
  self.monsterinfo.search = gladiator_search;
  self.monsterinfo.blocked = gladiator_blocked; // PGM
  self.monsterinfo.setskin = gladiator_setskin;

  gi.linkentity(self);
  M_SetAnimation(self, gladiator_move_stand, true);
  self.monsterinfo.scale = MODEL_SCALE;

  walkmonster_start(self);
}

//
// monster_gladb
// RAFAEL
//
/*QUAKED monster_gladb (1 .5 0) (-32 -32 -24) (32 32 64) Ambush Trigger_Spawn Sight
 */
export function SP_monster_gladb(self: EdictT): void {
  SP_monster_gladiator(self);
}
