// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
//
// m_gunner.c -- the GUNNER monster (2023 Quake II re-release / "KEX"
// engine). Ported from ~/Projects/quake2-rerelease-dll/rerelease/
// m_gunner.cpp (920 lines, C++17) + m_gunner.h (809 lines, frame index
// constants, "This file generated by qdata - Do NOT Modify"): the full
// fidget/stand/walk/run/runandshoot/pain/duck/attack(chaingun+grenade-arc)/
// jump/pain/death frame-animation system, gunner_pain/gunner_die/
// gunner_setskin/gunner_blocked/gunner_duck/gunner_sidestep, and the KEX
// [Paril-KEX]/[PMM] blindfire-grenade + new-duck-and-dodge additions.
// Behavioral code, ported bug-for-bug per PORTING.md.
//
// ============================================================================
// m_gunner.h's FRAME_c_* half belongs to a DIFFERENT monster
// ============================================================================
// m_gunner.h is 809 lines, not the ~80-line size every other qdata frame
// header in this porting batch has -- because the qdata batch script that
// generated it concatenated TWO monsters' frame enums into one header: the
// FRAME_stand01..FRAME_duck08 block (used by m_gunner.cpp, ported below) and
// a second FRAME_c_stand101..FRAME_c_duckdeath29 block (~330 entries) that
// is used ONLY by ~/Projects/quake2-rerelease-dll/rerelease/m_guncmdr.cpp
// (the "Gunner Commander" monster -- confirmed by
// `grep -rl FRAME_c_stand101 *.cpp *.h`: the only two hits are m_gunner.h
// itself and m_guncmdr.cpp). `monster_guncmdr` is a distinct monster
// (distinct `SP_monster_guncmdr`, not in this porting task's scope, no
// src/kexgame/m_guncmdr.ts exists) with its own future file. Per the
// "pure data -- port the whole header" precedent (m_flash.ts), the FRAME_c_*
// half would normally still get ported here since this IS m_gunner.h's
// complete content -- but doing so would leave ~330 dead exports in a file
// whose own logic never references them, and the sibling m_gladiator.ts
// unit landed in this same batch established the leaner "only declare the
// FRAME_ constants actually referenced by this monster's own .cpp" style
// (see that file's header). Followed here: the FRAME_c_* half is NOT
// transcribed into this file; it belongs to the future m_guncmdr.ts port,
// which should copy it from this same m_gunner.h source instead.
//
// ============================================================================
// EXTERNAL DEPENDENCIES NOT YET PORTED (throwing stubs, cited)
// ============================================================================
// - `blocked_checkplat(edict_t*, float)` / `blocked_checkjump(edict_t*,
//   float)`: both declared in g_local.h but their ONLY bodies in the whole
//   rerelease source tree live in
//   ~/Projects/quake2-rerelease-dll/rerelease/rogue/g_rogue_newai.cpp:14 and
//   :123 -- rogue (Ground Zero) AI content, out of scope for this base-game
//   monster porting round (no src/kexgame/g_rogue_newai.ts exists yet).
//   Every `monsterinfo.blocked` handler in the base game calls
//   `blocked_checkplat` (not gunner-specific), so `gunner_blocked` genuinely
//   throws if a plat or a jumpable gap ever blocks this monster's path
//   today -- an honest gap, not a silent behavior change, mirroring
//   g_turret.ts's own `infantry_die`-family stub precedent for the identical
//   kind of missing-content-dir gap, AND matching the identical decision the
//   sibling m_gladiator.ts unit (landed in this same batch) already made for
//   this exact function/citation. `gunner_jump`/`gunner_jump2`/
//   `gunner_jump_now`/`gunner_jump2_now`/`gunner_jump_wait_land` are still
//   ported for real below (they're only unreachable via the stubbed
//   `blocked_checkjump` path today, not deleted -- a future g_rogue_newai.ts
//   unit can wire them back up with zero changes here).
// - NOTE ON WHAT IS *NOT* STUBBED: unlike `blocked_checkplat`/
//   `blocked_checkjump`, this file DOES locally port `PredictAim`,
//   `M_CalculatePitchToFire`, `M_MonsterDodge`, `monster_duck_down`,
//   `monster_duck_hold`, `monster_duck_up`, and `monster_done_dodge` for
//   real (see "PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY" below) even
//   though every one of them is *also* only defined in
//   rogue/g_rogue_newai.cpp or rogue/g_rogue_monster.cpp in the C++ source.
//   RULING: gladiator's AI never calls these (no ranged predictive aim, no
//   duck/dodge ability), so stubbing them there was a zero-cost honest gap.
//   Gunner's entire attack repertoire (chaingun burst-fire AND grenade arcs)
//   goes through `PredictAim`/`M_CalculatePitchToFire` on every single shot,
//   and its `monsterinfo.dodge`/`.duck`/`.unduck` are wired to
//   `M_MonsterDodge`/`monster_duck_down`&friends/`monster_duck_up` in
//   `SP_monster_gunner` below -- stubbing them would make a spawned gunner
//   throw the instant it tries to fire, a categorically worse gap than
//   gladiator's narrow plat-blocking edge case. Ported for real instead,
//   each cited to its exact C++ source line. A future g_rogue_newai.ts unit
//   should replace ALL FIVE of this porting batch's per-file duplicates
//   (this file, and presumably m_soldier.ts/m_infantry.ts/m_berserk.ts/
//   m_gladiator.ts's own subset) with real imports, mirroring g_monster.ts's
//   own g_phys.ts stub-swap precedent.
//
// ============================================================================
// PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY
// ============================================================================
// - `monster_footstep(edict_t*)` (g_local.h:3282, `inline`, `[Paril-KEX]`)
//   and `M_CheckGib(edict_t*, const mod_t&)` (g_local.h:3521, `inline`):
//   both trivial one-liners, reimplemented locally rather than imported --
//   same treatment as g_turret.ts's/m_gladiator.ts's own locally-duplicated
//   small helpers.
// - `face_wall(edict_t*)` (rogue/g_rogue_newai.cpp:923): a small
//   `blocked_checkjump` helper. NOT ported -- only reachable from the
//   stubbed `blocked_checkjump`'s JUMP_JUMP_UP branch, so it would be dead
//   code today; omitted rather than transcribed unused.
// - `monster_done_dodge(edict_t*)` (rogue/g_rogue_monster.cpp:98, a THIRD
//   rogue file, distinct from g_rogue_newai.cpp): a trivial 4-line
//   `aiflags &= ~AI_DODGING` + attack_state reset. Ported for real (called
//   from `gunner_pain`/`gunner_run`/`gunner_jump`/`M_MonsterDodge` itself).
// - `PredictAim`/`G_SkillCheck`/`M_CalculatePitchToFire`/`M_MonsterDodge`/
//   `monster_duck_down`/`monster_duck_hold`/`monster_duck_up`
//   (rogue/g_rogue_newai.cpp:1083/1292/1140/1304/1424/1434/1442
//   respectively): ported for real, see the dependency note above. Skill
//   level read via `cvarOrDefault("skill", "1")`, duplicating g_ai.ts's own
//   module-private helper of the same name/behavior (not exported there).
//
// ============================================================================
// DEVIATIONS
// ============================================================================
// - `cached_soundindex` fields port as `{ index: 0 }` mutable boxes assigned
//   via a local `assignSound` helper, matching g_trigger.ts's/
//   m_gladiator.ts's `windsound`/sound-cache precedent exactly.
// - `PredictAim`'s two C++ output pointer params (`vec3_t *aimdir, vec3_t
//   *aimpoint`, either may be `nullptr`) collapse to a single return value
//   `{ aimdir: Vec3; aimpoint: Vec3 }` -- `GunnerFire` (this file's only
//   call site) always wants `aimdir` and never passes `nullptr` for it in
//   the C++, so both are always computed and the caller just reads the
//   field it needs, mirroring `AngleVectors_destructured`'s established
//   idiom for the same "C out-params, TS destructured return" shape.
// - `M_CalculatePitchToFire`'s `vec3_t &aim` is an in/out reference
//   (mutated in place on success, left untouched on failure); ported as a
//   `Vec3` (mutable `Float32Array`) mutated via `vec3_copyInto`-style
//   in-place writes, not a return value -- the direct equivalent, matching
//   `M_CheckClearShot`'s optional out-param precedent in g_monster.ts.
// - Vec3 "copy" sites use `vec3(v[0], v[1], v[2])`; `Vec3` is a mutable
//   `Float32Array` so a bare `=` would alias instead of copy, matching
//   g_turret.ts's/m_gladiator.ts's own established idiom.
// - `self.enemy` (nullable in `EdictT`) is narrowed via an explicit
//   `if (self.enemy === null) return` guard rather than a non-null
//   assertion -- no casts anywhere in this file besides `as const`.
// - `st`/`spawn_temp_t` is the real, shared singleton imported from the
//   landed g_spawn.ts (not a per-file duplicate).

import { vec3, type Vec3 } from "../shared/math";
import {
  type EdictT,
  type ModT,
  type PainFn,
  type DieFn,
  BlockedJumpResultT,
  GibTypeT,
  ModIdT,
  MonsterAiFlagsT,
  MonsterAttackStateT,
  MovetypeT,
  DUCK_INTERVAL,
  random_time,
} from "./g_local";
import type { CvarT } from "./g_local_types";
import {
  ATTN_IDLE,
  ATTN_NORM,
  ContentsT,
  CvarFlagsT,
  KexEntityEventT,
  MASK_PROJECTILE,
  MASK_SHOT,
  MASK_SOLID,
  MonsterMuzzleflashIdT,
  SolidT,
  SoundchanT,
  SurfflagsT,
  SvflagsT,
} from "../kexapi/game";
import {
  RegisterMmove,
  RegisterThink,
  RegisterPain,
  RegisterDie,
  RegisterMonsterinfoStand,
  RegisterMonsterinfoWalk,
  RegisterMonsterinfoRun,
  RegisterMonsterinfoAttack,
  RegisterMonsterinfoSight,
  RegisterMonsterinfoSearch,
  RegisterMonsterinfoSetskin,
  RegisterMonsterinfoBlocked,
  RegisterMonsterinfoDuck,
  RegisterMonsterinfoSidestep,
} from "./g_save_registry";
import { monster_duck_up, M_MonsterDodge } from "./m_soldier";
import { blocked_checkjump } from "./rogue/g_rogue_newai";
import { blocked_checkplat } from "./m_supertank";
import { MframeT, MmoveT } from "./g_local_types";
import { gi, level } from "./g_main_globals";
import { ai_charge, ai_move, ai_run, ai_stand, ai_walk, FoundTarget, range_to, visible } from "./g_ai";
import {
  M_AllowSpawn,
  M_CheckClearShot,
  M_ProjectFlashSource,
  M_SetAnimation,
  M_ShouldReactToPain,
  monster_dead,
  monster_fire_bullet,
  monster_fire_grenade,
  walkmonster_start,
} from "./g_monster";
import { ThrowGibs } from "./g_misc";
import { AngleVectors_destructured, ClipVelocity, vec3_add, vec3_dot, vec3_length, vec3_muls, vec3_normalized, vec3_sub, vectoangles, vectoyaw } from "./q_vec3";
import { G_FreeEdict } from "./g_utils";
import { brandom, crandom_open, frandom, PITCH } from "./q_std";
import { Gtime_add, Gtime_from_ms, Gtime_from_sec, type GTime } from "./gtime";
import { monsterFlashOffset } from "./m_flash";
import { st } from "./g_spawn";

// ---------------------------------------------------------------------------
// m_gunner.h frame index constants -- only the FRAME_ entries this file's
// own logic references (see file header for why the FRAME_c_* half is
// omitted). Values copied verbatim from the C anonymous enum's declaration
// order (0-based, FRAME_stand01 = 0).
// ---------------------------------------------------------------------------

// Indices below are derived by counting the anonymous enum in m_gunner.h
// sequentially from FRAME_stand01=0 (70 stand entries, then 24 walk, 8 run,
// 6 runs, 21 attak1xx, 30 attak2xx, 18 pain1xx, 8 pain2xx, 5 pain3xx, 11
// death, 8 duck, 10 jump, 6 shield [unused], 24 attak3xx) -- cross-checked
// against every MMOVE_T's row count below (MmoveT's own frame-count
// validator threw at module-load time until these were exact; a `bun -e`
// smoke import after this file was fully written confirmed all 17 tables
// pass).
const FRAME_stand01 = 0;
const FRAME_stand30 = 29;
const FRAME_stand31 = 30;
const FRAME_stand70 = 69;
const FRAME_walk07 = 76;
const FRAME_walk19 = 88;
const FRAME_run01 = 94;
const FRAME_run08 = 101;
const FRAME_runs01 = 102;
const FRAME_runs06 = 107;
const FRAME_attak101 = 108;
const FRAME_attak105 = 112;
const FRAME_attak108 = 115;
const FRAME_attak109 = 116;
const FRAME_attak111 = 118;
const FRAME_attak114 = 121;
const FRAME_attak121 = 128;
const FRAME_attak209 = 137;
const FRAME_attak215 = 143;
const FRAME_attak216 = 144;
const FRAME_attak223 = 151;
const FRAME_attak224 = 152;
const FRAME_attak230 = 158;
const FRAME_attak301 = 225;
const FRAME_attak305 = 229;
const FRAME_attak309 = 233;
const FRAME_attak312 = 236;
const FRAME_attak315 = 239;
const FRAME_attak324 = 248;
const FRAME_pain101 = 159;
const FRAME_pain118 = 176;
const FRAME_pain201 = 177;
const FRAME_pain208 = 184;
const FRAME_pain301 = 185;
const FRAME_pain305 = 189;
const FRAME_death01 = 190;
const FRAME_death11 = 200;
const FRAME_duck01 = 201;
const FRAME_duck08 = 208;
const FRAME_jump01 = 209;
const FRAME_jump10 = 218;

const MODEL_SCALE = 1.15;

// ---------------------------------------------------------------------------
// EXTERNAL DEPENDENCIES NOT YET PORTED -- see file header
// ---------------------------------------------------------------------------

// blocked_checkjump is now a real import from "./rogue/g_rogue_newai";
// blocked_checkplat is now a real import from "./m_supertank" (its real
// declared home is rogue/g_rogue_newai.cpp:14, but it is NOT re-exported
// from rogue/g_rogue_newai.ts -- see that file's header note on the
// three-module import-cycle hazard that re-export would create).

// ---------------------------------------------------------------------------
// PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY -- see file header
// ---------------------------------------------------------------------------

function monster_footstep(self: EdictT): void {
  if (self.groundentity !== null) self.s.event = KexEntityEventT.EV_OTHER_FOOTSTEP;
}

function M_CheckGib(self: EdictT, mod: ModT): boolean {
  if (self.deadflag) {
    if (mod.id === ModIdT.MOD_CRUSH) return true;
  }
  return self.health <= self.gib_health;
}

/** rogue/g_rogue_monster.cpp:98 */
function monster_done_dodge(self: EdictT): void {
  self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_DODGING;
  if (self.monsterinfo.attack_state === MonsterAttackStateT.AS_SLIDING) {
    self.monsterinfo.attack_state = MonsterAttackStateT.AS_STRAIGHT;
  }
}

function cvarOrDefault(name: string, defaultValue: string): CvarT {
  const c = gi.cvar(name, defaultValue, CvarFlagsT.CVAR_NOFLAGS);
  if (c === null) throw new Error(`gi.cvar(${name}) returned null`);
  return c;
}

/** rogue/g_rogue_newai.cpp:1083-1136. `aimdir`/`aimpoint` collapse into one
 *  destructured return -- see file header. */
function PredictAim(self: EdictT, target: EdictT | null, start: Vec3, bolt_speed: number, eye_height_in: boolean, offset: number): { aimdir: Vec3; aimpoint: Vec3 } {
  if (target === null || !target.inuse) {
    return { aimdir: vec3(0, 0, 0), aimpoint: vec3(0, 0, 0) };
  }

  let eye_height = eye_height_in;
  let dir = vec3_sub(target.s.origin, start);
  if (eye_height) dir[2] += target.viewheight;
  let dist = vec3_length(dir);

  // [Paril-KEX] if our current attempt is blocked, try the opposite one
  const tr = gi.trace(start, null, null, vec3_add(start, dir), self, MASK_PROJECTILE);

  if (tr.ent !== target) {
    eye_height = !eye_height;
    dir = vec3_sub(target.s.origin, start);
    if (eye_height) dir[2] += target.viewheight;
    dist = vec3_length(dir);
  }

  const time = bolt_speed !== 0 ? dist / bolt_speed : 0;

  let vec = vec3_add(target.s.origin, vec3_muls(target.velocity, time - offset));

  // went backwards...
  if (vec3_dot(vec3_normalized(dir), vec3_normalized(vec3_sub(vec, start))) < 0) {
    vec = vec3(target.s.origin[0], target.s.origin[1], target.s.origin[2]);
  } else {
    // if the shot is going to impact a nearby wall from our prediction, just fire it straight.
    if (gi.trace(start, null, null, vec, null, MASK_SOLID).fraction < 0.9) {
      vec = vec3(target.s.origin[0], target.s.origin[1], target.s.origin[2]);
    }
  }

  if (eye_height) vec[2] += target.viewheight;

  return { aimdir: vec3_normalized(vec3_sub(vec, start)), aimpoint: vec };
}

/** rogue/g_rogue_newai.cpp:1292-1299. */
function G_SkillCheck(skills: readonly [number, number, number, number]): boolean {
  const skillInt = Math.trunc(cvarOrDefault("skill", "1").value);
  if (skills.length < skillInt) return true;

  const skill_switch = skills[Math.max(0, Math.min(skills.length - 1, skillInt))] as number;
  return skill_switch === 1.0 ? true : frandom() < skill_switch;
}

const M_CALCPITCH_PITCHES = [-80, -70, -60, -50, -40, -30, -20, -10, -5] as const;

/** rogue/g_rogue_newai.cpp:1140-1203. `aim` is mutated in place on success
 *  (matching the C++ `vec3_t &aim` in/out reference), left untouched on
 *  failure -- see file header. */
function M_CalculatePitchToFire(
  self: EdictT,
  target: Vec3,
  start: Vec3,
  aim: Vec3,
  speed: number,
  time_remaining: number,
  mortar: boolean,
  destroy_on_touch: boolean = false,
): boolean {
  let best_pitch = 0;
  let best_dist = Infinity;

  const sim_time = 0.1;
  const pitched_aim = vectoangles(aim);

  for (const pitch of M_CALCPITCH_PITCHES) {
    if (mortar && pitch >= -30) break;

    pitched_aim[PITCH] = pitch;
    const fwd = AngleVectors_destructured(pitched_aim).forward;

    let velocity = vec3_muls(fwd, speed);
    let origin = vec3(start[0], start[1], start[2]);

    let t = time_remaining;

    while (t > 0) {
      velocity = vec3_add(velocity, vec3_muls(vec3(0, 0, -1), level.gravity * sim_time));

      const end = vec3_add(origin, vec3_muls(velocity, sim_time));
      const tr = gi.trace(origin, null, null, end, null, MASK_SHOT);

      origin = vec3(tr.endpos[0], tr.endpos[1], tr.endpos[2]);

      if (tr.fraction < 1.0) {
        if (tr.surface !== null && (tr.surface.flags & SurfflagsT.SURF_SKY) !== 0) break;

        origin = vec3_add(origin, tr.plane.normal);
        velocity = ClipVelocity(velocity, tr.plane.normal, 1.6);

        const dist = vec3_length(vec3_sub(origin, target)) ** 2;

        if (tr.ent !== null && (tr.ent === self.enemy || tr.ent.client !== null || (tr.plane.normal[2] >= 0.7 && dist < 128 * 128 && dist < best_dist))) {
          best_pitch = pitch;
          best_dist = dist;
        }

        if (destroy_on_touch || (tr.contents & (ContentsT.CONTENTS_MONSTER | ContentsT.CONTENTS_PLAYER | ContentsT.CONTENTS_DEADMONSTER)) !== 0) break;
      }

      t -= sim_time;
    }
  }

  if (Number.isFinite(best_dist)) {
    pitched_aim[PITCH] = best_pitch;
    const fwd = AngleVectors_destructured(pitched_aim).forward;
    aim[0] = fwd[0];
    aim[1] = fwd[1];
    aim[2] = fwd[2];
    return true;
  }

  return false;
}

function monster_duck_down(self: EdictT): void {
  self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_DUCKED;
  self.maxs[2] = self.monsterinfo.base_height - 32;
  self.takedamage = true;
  self.monsterinfo.next_duck_time = Gtime_add(level.time, DUCK_INTERVAL);
  gi.linkentity(self);
}

function monster_duck_hold(self: EdictT): void {
  if (level.time >= self.monsterinfo.duck_wait_time) {
    self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_HOLD_FRAME;
  } else {
    self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_HOLD_FRAME;
  }
}

// rogue/g_rogue_newai.cpp:1442-1451 (MONSTERINFO_UNDUCK) and :1304-1422
// (MONSTERINFO_DODGE) -- `monster_duck_up`/`M_MonsterDodge` are
// monster-agnostic rogue-newai infrastructure, not gunner-specific, imported
// from m_soldier.ts (their canonical, exported home in this porting batch)
// instead of being re-registered here under the same names:
// g_save_registry.ts's monsterinfo_unduck/monsterinfo_dodge registries are
// global and name-keyed, so a second local copy would throw a
// duplicate-registration error the instant more than one of
// m_soldier.ts/m_infantry.ts/m_gunner.ts loads in the same process (as
// g_spawn.ts's real monster table does, importing all three). See
// m_soldier.ts's own comments on these two exports. `G_SkillCheck`/
// `cvarOrDefault` above were used only inside the deleted local
// M_MonsterDodge body and are kept (unused) for provenance rather than
// removed, matching this porting batch's low-risk-diff convention.

// ---------------------------------------------------------------------------
// small local helpers -- duplicated per-file, see g_turret.ts/m_gladiator.ts
// precedent
// ---------------------------------------------------------------------------

interface CachedSoundindex {
  index: number;
}
function cachedSoundindex(): CachedSoundindex {
  return { index: 0 };
}
function assignSound(cached: CachedSoundindex, name: string): void {
  cached.index = gi.soundindex(name);
}
function mkframe(aifunc: MframeT["aifunc"], dist = 0, thinkfunc: MframeT["thinkfunc"] = null): MframeT {
  return { aifunc, dist, thinkfunc, lerp_frame: -1 };
}

const DEFAULT_BULLET_HSPREAD = 300;
const DEFAULT_BULLET_VSPREAD = 500;

const sound_pain = cachedSoundindex();
const sound_pain2 = cachedSoundindex();
const sound_death = cachedSoundindex();
const sound_idle = cachedSoundindex();
const sound_open = cachedSoundindex();
const sound_search = cachedSoundindex();
const sound_sight = cachedSoundindex();

function gunner_idlesound(self: EdictT): void {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_idle.index, 1, ATTN_IDLE, 0);
}

export const gunner_sight = RegisterMonsterinfoSight("gunner_sight", (self: EdictT, _other: EdictT): void => {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_sight.index, 1, ATTN_NORM, 0);
});

export const gunner_search = RegisterMonsterinfoSearch("gunner_search", (self: EdictT): void => {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_search.index, 1, ATTN_NORM, 0);
});

// ---------------------------------------------------------------------------
// fidget / stand
// ---------------------------------------------------------------------------

const gunner_frames_fidget: MframeT[] = [
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand, 0, gunner_idlesound),
  mkframe(ai_stand),

  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),

  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),

  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),

  mkframe(ai_stand),
];
export const gunner_move_fidget = RegisterMmove(
  "gunner_move_fidget",
  Object.assign(new MmoveT(), { firstframe: FRAME_stand31, lastframe: FRAME_stand70, frame: gunner_frames_fidget, endfunc: (self: EdictT) => gunner_stand(self) }),
);

function gunner_fidget(self: EdictT): void {
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) !== 0n) return;
  else if (self.enemy !== null) return;
  if (frandom() <= 0.05) M_SetAnimation(self, gunner_move_fidget, false);
}

const gunner_frames_stand: MframeT[] = [
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand, 0, gunner_fidget),

  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand, 0, gunner_fidget),

  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand),
  mkframe(ai_stand, 0, gunner_fidget),
];
export const gunner_move_stand = RegisterMmove(
  "gunner_move_stand",
  Object.assign(new MmoveT(), { firstframe: FRAME_stand01, lastframe: FRAME_stand30, frame: gunner_frames_stand, endfunc: null }),
);

export const gunner_stand = RegisterMonsterinfoStand("gunner_stand", (self: EdictT): void => {
  M_SetAnimation(self, gunner_move_stand, false);
});

// ---------------------------------------------------------------------------
// walk
// ---------------------------------------------------------------------------

const gunner_frames_walk: MframeT[] = [
  mkframe(ai_walk),
  mkframe(ai_walk, 3),
  mkframe(ai_walk, 4),
  mkframe(ai_walk, 5),
  mkframe(ai_walk, 7),
  mkframe(ai_walk, 2, monster_footstep),
  mkframe(ai_walk, 6),
  mkframe(ai_walk, 4),
  mkframe(ai_walk, 2),
  mkframe(ai_walk, 7),
  mkframe(ai_walk, 5),
  mkframe(ai_walk, 7),
  mkframe(ai_walk, 4, monster_footstep),
];
export const gunner_move_walk = RegisterMmove(
  "gunner_move_walk",
  Object.assign(new MmoveT(), { firstframe: FRAME_walk07, lastframe: FRAME_walk19, frame: gunner_frames_walk, endfunc: null }),
);

export const gunner_walk = RegisterMonsterinfoWalk("gunner_walk", (self: EdictT): void => {
  M_SetAnimation(self, gunner_move_walk, false);
});

// ---------------------------------------------------------------------------
// run / runandshoot
// ---------------------------------------------------------------------------

const gunner_frames_run: MframeT[] = [
  mkframe(ai_run, 26),
  mkframe(ai_run, 9, monster_footstep),
  mkframe(ai_run, 9),
  mkframe(ai_run, 9, monster_done_dodge),
  mkframe(ai_run, 15),
  mkframe(ai_run, 10, monster_footstep),
  mkframe(ai_run, 13),
  mkframe(ai_run, 6),
];
export const gunner_move_run = RegisterMmove(
  "gunner_move_run",
  Object.assign(new MmoveT(), { firstframe: FRAME_run01, lastframe: FRAME_run08, frame: gunner_frames_run, endfunc: null }),
);

export const gunner_run = RegisterMonsterinfoRun("gunner_run", (self: EdictT): void => {
  monster_done_dodge(self);
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) !== 0n) {
    M_SetAnimation(self, gunner_move_stand, false);
  } else {
    M_SetAnimation(self, gunner_move_run, false);
  }
});

const gunner_frames_runandshoot: MframeT[] = [
  mkframe(ai_run, 32),
  mkframe(ai_run, 15),
  mkframe(ai_run, 10),
  mkframe(ai_run, 18),
  mkframe(ai_run, 8),
  mkframe(ai_run, 20),
];
export const gunner_move_runandshoot = RegisterMmove(
  "gunner_move_runandshoot",
  Object.assign(new MmoveT(), { firstframe: FRAME_runs01, lastframe: FRAME_runs06, frame: gunner_frames_runandshoot, endfunc: null }),
);

function gunner_runandshoot(self: EdictT): void {
  M_SetAnimation(self, gunner_move_runandshoot, false);
}

// ---------------------------------------------------------------------------
// pain
// ---------------------------------------------------------------------------

const gunner_frames_pain3: MframeT[] = [mkframe(ai_move, -3), mkframe(ai_move, 1), mkframe(ai_move, 1), mkframe(ai_move), mkframe(ai_move, 1)];
export const gunner_move_pain3 = RegisterMmove(
  "gunner_move_pain3",
  Object.assign(new MmoveT(), { firstframe: FRAME_pain301, lastframe: FRAME_pain305, frame: gunner_frames_pain3, endfunc: (self: EdictT) => gunner_run(self) }),
);

const gunner_frames_pain2: MframeT[] = [
  mkframe(ai_move, -2),
  mkframe(ai_move, 11),
  mkframe(ai_move, 6, monster_footstep),
  mkframe(ai_move, 2),
  mkframe(ai_move, -1),
  mkframe(ai_move, -7),
  mkframe(ai_move, -2),
  mkframe(ai_move, -7, monster_footstep),
];
export const gunner_move_pain2 = RegisterMmove(
  "gunner_move_pain2",
  Object.assign(new MmoveT(), { firstframe: FRAME_pain201, lastframe: FRAME_pain208, frame: gunner_frames_pain2, endfunc: (self: EdictT) => gunner_run(self) }),
);

const gunner_frames_pain1: MframeT[] = [
  mkframe(ai_move, 2),
  mkframe(ai_move),
  mkframe(ai_move, -5),
  mkframe(ai_move, 3),
  mkframe(ai_move, -1, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 1),
  mkframe(ai_move, 1),
  mkframe(ai_move, 2),
  mkframe(ai_move, 1, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move, -2),
  mkframe(ai_move, -2),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
];
export const gunner_move_pain1 = RegisterMmove(
  "gunner_move_pain1",
  Object.assign(new MmoveT(), { firstframe: FRAME_pain101, lastframe: FRAME_pain118, frame: gunner_frames_pain1, endfunc: (self: EdictT) => gunner_run(self) }),
);

export const gunner_pain: PainFn = RegisterPain("gunner_pain", (self: EdictT, _other: EdictT, _kick: number, damage: number, mod: ModT): void => {
  monster_done_dodge(self);

  if (self.monsterinfo.active_move === gunner_move_jump || self.monsterinfo.active_move === gunner_move_jump2) return;

  if (level.time < self.pain_debounce_time) return;

  self.pain_debounce_time = Gtime_add(level.time, Gtime_from_sec(3));

  if (brandom()) {
    gi.sound(self, SoundchanT.CHAN_VOICE, sound_pain.index, 1, ATTN_NORM, 0);
  } else {
    gi.sound(self, SoundchanT.CHAN_VOICE, sound_pain2.index, 1, ATTN_NORM, 0);
  }

  if (!M_ShouldReactToPain(self, mod)) return; // no pain anims in nightmare

  if (damage <= 10) {
    M_SetAnimation(self, gunner_move_pain3, false);
  } else if (damage <= 25) {
    M_SetAnimation(self, gunner_move_pain2, false);
  } else {
    M_SetAnimation(self, gunner_move_pain1, false);
  }

  self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_MANUAL_STEERING;

  // PMM - clear duck flag
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_DUCKED) !== 0n) monster_duck_up(self);
});

export const gunner_setskin = RegisterMonsterinfoSetskin("gunner_setskin", (self: EdictT): void => {
  self.s.skinnum = self.health < self.max_health / 2 ? 1 : 0;
});

// ---------------------------------------------------------------------------
// death
// ---------------------------------------------------------------------------

function gunner_dead(self: EdictT): void {
  self.mins = vec3(-16, -16, -24);
  self.maxs = vec3(16, 16, -8);
  monster_dead(self);
}

function gunner_shrink(self: EdictT): void {
  self.maxs[2] = -4;
  self.svflags |= SvflagsT.SVF_DEADMONSTER;
  gi.linkentity(self);
}

const gunner_frames_death: MframeT[] = [
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move, -7, gunner_shrink),
  mkframe(ai_move, -3),
  mkframe(ai_move, -5),
  mkframe(ai_move, 8),
  mkframe(ai_move, 6),
  mkframe(ai_move, 0, monster_footstep),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const gunner_move_death = RegisterMmove(
  "gunner_move_death",
  Object.assign(new MmoveT(), { firstframe: FRAME_death01, lastframe: FRAME_death11, frame: gunner_frames_death, endfunc: (self: EdictT) => gunner_dead(self) }),
);

export const gunner_die: DieFn = RegisterDie("gunner_die", (self: EdictT, _inflictor: EdictT, _attacker: EdictT, damage: number, _point: Vec3, mod: ModT): void => {
  // check for gib
  if (M_CheckGib(self, mod)) {
    gi.sound(self, SoundchanT.CHAN_VOICE, gi.soundindex("misc/udeath.wav"), 1, ATTN_NORM, 0);

    self.s.skinnum = Math.trunc(self.s.skinnum / 2);

    ThrowGibs(self, damage, [
      { count: 2, gibname: "models/objects/gibs/bone/tris.md2" },
      { count: 2, gibname: "models/objects/gibs/sm_meat/tris.md2" },
      { gibname: "models/monsters/gunner/gibs/chest.md2", type: GibTypeT.GIB_SKINNED },
      { gibname: "models/monsters/gunner/gibs/garm.md2", type: GibTypeT.GIB_SKINNED | GibTypeT.GIB_UPRIGHT },
      { gibname: "models/monsters/gunner/gibs/gun.md2", type: GibTypeT.GIB_SKINNED | GibTypeT.GIB_UPRIGHT },
      { gibname: "models/monsters/gunner/gibs/foot.md2", type: GibTypeT.GIB_SKINNED },
      { gibname: "models/monsters/gunner/gibs/head.md2", type: GibTypeT.GIB_SKINNED | GibTypeT.GIB_HEAD },
    ]);

    self.deadflag = true;
    return;
  }

  if (self.deadflag) return;

  // regular death
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_death.index, 1, ATTN_NORM, 0);
  self.deadflag = true;
  self.takedamage = true;
  M_SetAnimation(self, gunner_move_death, false);
});

// ---------------------------------------------------------------------------
// duck (PMM - new dodge)
// ---------------------------------------------------------------------------

const gunner_frames_duck: MframeT[] = [
  mkframe(ai_move, 1, monster_duck_down),
  mkframe(ai_move, 1),
  mkframe(ai_move, 1, monster_duck_hold),
  mkframe(ai_move),
  mkframe(ai_move, -1),
  mkframe(ai_move, -1),
  mkframe(ai_move, 0, monster_duck_up),
  mkframe(ai_move, -1),
];
export const gunner_move_duck = RegisterMmove(
  "gunner_move_duck",
  Object.assign(new MmoveT(), { firstframe: FRAME_duck01, lastframe: FRAME_duck08, frame: gunner_frames_duck, endfunc: (self: EdictT) => gunner_run(self) }),
);

// ---------------------------------------------------------------------------
// chaingun attack
// ---------------------------------------------------------------------------

function gunner_opengun(self: EdictT): void {
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_open.index, 1, ATTN_IDLE, 0);
}

function GunnerFire(self: EdictT): void {
  if (self.enemy === null || !self.enemy.inuse) return;

  const flash_number: MonsterMuzzleflashIdT = MonsterMuzzleflashIdT.MZ2_GUNNER_MACHINEGUN_1 + (self.s.frame - FRAME_attak216);

  const { forward, right } = AngleVectors_destructured(self.s.angles);
  const start = M_ProjectFlashSource(self, monsterFlashOffset()[flash_number] as Vec3, forward, right);
  const { aimdir: aim } = PredictAim(self, self.enemy, start, 0, true, -0.2);
  monster_fire_bullet(self, start, aim, 3, 4, DEFAULT_BULLET_HSPREAD, DEFAULT_BULLET_VSPREAD, flash_number);
}

function gunner_grenade_check(self: EdictT): boolean {
  if (self.enemy === null) return false;

  const start = vec3(0, 0, 0);
  if (!M_CheckClearShot(self, monsterFlashOffset()[MonsterMuzzleflashIdT.MZ2_GUNNER_GRENADE_1] as Vec3, start)) return false;

  let target: Vec3;
  // check for flag telling us that we're blindfiring
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_MANUAL_STEERING) !== 0n) {
    target = self.monsterinfo.blind_fire_target;
  } else {
    target = self.enemy.s.origin;
  }

  const dir = vec3_sub(target, start);
  if (vec3_length(dir) < 100) return false;

  const aim = vec3_normalized(dir);
  return M_CalculatePitchToFire(self, target, start, aim, 600, 2.5, false);
}

function GunnerGrenade(self: EdictT): void {
  if (self.enemy === null || !self.enemy.inuse) return;

  const blindfire = (self.monsterinfo.aiflags & MonsterAiFlagsT.AI_MANUAL_STEERING) !== 0n;

  let spread: number;
  let flash_number: MonsterMuzzleflashIdT;

  if (self.s.frame === FRAME_attak105 || self.s.frame === FRAME_attak309) {
    spread = -0.1;
    flash_number = MonsterMuzzleflashIdT.MZ2_GUNNER_GRENADE_1;
  } else if (self.s.frame === FRAME_attak108 || self.s.frame === FRAME_attak312) {
    spread = -0.05;
    flash_number = MonsterMuzzleflashIdT.MZ2_GUNNER_GRENADE_2;
  } else if (self.s.frame === FRAME_attak111 || self.s.frame === FRAME_attak315) {
    spread = 0.05;
    flash_number = MonsterMuzzleflashIdT.MZ2_GUNNER_GRENADE_3;
  } else {
    // (self->s.frame == FRAME_attak114)
    self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_MANUAL_STEERING;
    spread = 0.1;
    flash_number = MonsterMuzzleflashIdT.MZ2_GUNNER_GRENADE_4;
  }

  if (self.s.frame >= FRAME_attak301 && self.s.frame <= FRAME_attak324) {
    flash_number = MonsterMuzzleflashIdT.MZ2_GUNNER_GRENADE2_1 + (MonsterMuzzleflashIdT.MZ2_GUNNER_GRENADE_4 - flash_number);
  }

  // if we're shooting blind and we still can't see our enemy
  let target: Vec3;
  if (blindfire && !visible(self, self.enemy)) {
    if (self.monsterinfo.blind_fire_target[0] === 0 && self.monsterinfo.blind_fire_target[1] === 0 && self.monsterinfo.blind_fire_target[2] === 0) return;
    target = self.monsterinfo.blind_fire_target;
  } else {
    target = self.enemy.s.origin;
  }

  const { forward, right, up } = AngleVectors_destructured(self.s.angles);
  const start = M_ProjectFlashSource(self, monsterFlashOffset()[flash_number] as Vec3, forward, right);

  let pitch = 0;
  {
    const rawAim = vec3_sub(target, self.s.origin);
    const dist = vec3_length(rawAim);
    const aimAdjusted = vec3(rawAim[0], rawAim[1], rawAim[2]);

    // aim up if they're on the same level as me and far away.
    if (dist > 512 && aimAdjusted[2] < 64 && aimAdjusted[2] > -64) {
      aimAdjusted[2] += dist - 512;
    }

    const normalized = vec3_normalized(aimAdjusted);
    pitch = normalized[2];
    if (pitch > 0.4) pitch = 0.4;
    else if (pitch < -0.5) pitch = -0.5;
  }

  let aim = vec3_add(forward, vec3_muls(right, spread));
  aim = vec3_add(aim, vec3_muls(up, pitch));

  // try search for best pitch
  if (M_CalculatePitchToFire(self, target, start, aim, 600, 2.5, false)) {
    monster_fire_grenade(self, start, aim, 50, 600, flash_number, crandom_open() * 10.0, frandom() * 10.0);
  } else {
    // normal shot
    monster_fire_grenade(self, start, aim, 50, 600, flash_number, crandom_open() * 10.0, 200.0 + crandom_open() * 10.0);
  }
}

const gunner_frames_attack_chain: MframeT[] = [
  mkframe(ai_charge, 0, gunner_opengun),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
];
export const gunner_move_attack_chain = RegisterMmove(
  "gunner_move_attack_chain",
  Object.assign(new MmoveT(), { firstframe: FRAME_attak209, lastframe: FRAME_attak215, frame: gunner_frames_attack_chain, endfunc: (self: EdictT) => gunner_fire_chain(self) }),
);

const gunner_frames_fire_chain: MframeT[] = [
  mkframe(ai_charge, 0, GunnerFire),
  mkframe(ai_charge, 0, GunnerFire),
  mkframe(ai_charge, 0, GunnerFire),
  mkframe(ai_charge, 0, GunnerFire),
  mkframe(ai_charge, 0, GunnerFire),
  mkframe(ai_charge, 0, GunnerFire),
  mkframe(ai_charge, 0, GunnerFire),
  mkframe(ai_charge, 0, GunnerFire),
];
export const gunner_move_fire_chain = RegisterMmove(
  "gunner_move_fire_chain",
  Object.assign(new MmoveT(), { firstframe: FRAME_attak216, lastframe: FRAME_attak223, frame: gunner_frames_fire_chain, endfunc: (self: EdictT) => gunner_refire_chain(self) }),
);

const gunner_frames_endfire_chain: MframeT[] = [
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, monster_footstep),
];
export const gunner_move_endfire_chain = RegisterMmove(
  "gunner_move_endfire_chain",
  Object.assign(new MmoveT(), { firstframe: FRAME_attak224, lastframe: FRAME_attak230, frame: gunner_frames_endfire_chain, endfunc: (self: EdictT) => gunner_run(self) }),
);

function gunner_blind_check(self: EdictT): void {
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_MANUAL_STEERING) !== 0n) {
    const aim = vec3_sub(self.monsterinfo.blind_fire_target, self.s.origin);
    self.ideal_yaw = vectoyaw(aim);
  }
}

const gunner_frames_attack_grenade: MframeT[] = [
  mkframe(ai_charge, 0, gunner_blind_check),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
];
export const gunner_move_attack_grenade = RegisterMmove(
  "gunner_move_attack_grenade",
  Object.assign(new MmoveT(), { firstframe: FRAME_attak101, lastframe: FRAME_attak121, frame: gunner_frames_attack_grenade, endfunc: (self: EdictT) => gunner_run(self) }),
);

const gunner_frames_attack_grenade2: MframeT[] = [
  mkframe(ai_charge, 0, gunner_blind_check),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge, 0, GunnerGrenade),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
  mkframe(ai_charge),
];
export const gunner_move_attack_grenade2 = RegisterMmove(
  "gunner_move_attack_grenade2",
  Object.assign(new MmoveT(), { firstframe: FRAME_attak305, lastframe: FRAME_attak324, frame: gunner_frames_attack_grenade2, endfunc: (self: EdictT) => gunner_run(self) }),
);

export const gunner_attack = RegisterMonsterinfoAttack("gunner_attack", (self: EdictT): void => {
  monster_done_dodge(self);

  if (self.enemy === null) return;

  // PMM
  if (self.monsterinfo.attack_state === MonsterAttackStateT.AS_BLIND) {
    if (self.timestamp > level.time) return;

    let chance: number;
    if (self.monsterinfo.blind_fire_delay < Gtime_from_sec(1)) chance = 1.0;
    else if (self.monsterinfo.blind_fire_delay < Gtime_from_sec(7.5)) chance = 0.4;
    else chance = 0.1;

    const r = frandom();

    // minimum of 4.1 seconds, plus 0-3, after the shots are done
    self.monsterinfo.blind_fire_delay = Gtime_add(Gtime_add(self.monsterinfo.blind_fire_delay, Gtime_from_ms(4100)), random_time(Gtime_from_sec(3)));

    // don't shoot at the origin
    if (self.monsterinfo.blind_fire_target[0] === 0 && self.monsterinfo.blind_fire_target[1] === 0 && self.monsterinfo.blind_fire_target[2] === 0) return;

    // don't shoot if the dice say not to
    if (r > chance) return;

    // turn on manual steering to signal both manual steering and blindfire
    self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_MANUAL_STEERING;

    if (gunner_grenade_check(self)) {
      M_SetAnimation(self, brandom() ? gunner_move_attack_grenade2 : gunner_move_attack_grenade, false);
      self.monsterinfo.attack_finished = Gtime_add(level.time, random_time(Gtime_from_sec(2)));
    } else {
      self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_MANUAL_STEERING;
    }

    self.timestamp = Gtime_add(level.time, random_time(Gtime_from_sec(2), Gtime_from_sec(3)));

    return;
  }

  // PGM - gunner needs to use his chaingun if he's being attacked by a tesla.
  if (
    self.bad_area ||
    self.timestamp > level.time ||
    (range_to(self, self.enemy) <= RANGE_NEAR * 0.35 && M_CheckClearShot(self, monsterFlashOffset()[MonsterMuzzleflashIdT.MZ2_GUNNER_MACHINEGUN_1] as Vec3))
  ) {
    M_SetAnimation(self, gunner_move_attack_chain, false);
  } else {
    if (self.timestamp <= level.time && frandom() <= 0.5 && gunner_grenade_check(self)) {
      M_SetAnimation(self, brandom() ? gunner_move_attack_grenade2 : gunner_move_attack_grenade, false);
      self.timestamp = Gtime_add(level.time, random_time(Gtime_from_sec(2), Gtime_from_sec(3)));
    } else if (M_CheckClearShot(self, monsterFlashOffset()[MonsterMuzzleflashIdT.MZ2_GUNNER_MACHINEGUN_1] as Vec3)) {
      M_SetAnimation(self, gunner_move_attack_chain, false);
    }
  }
});

function gunner_fire_chain(self: EdictT): void {
  M_SetAnimation(self, gunner_move_fire_chain, false);
}

function gunner_refire_chain(self: EdictT): void {
  if (self.enemy !== null && self.enemy.health > 0 && visible(self, self.enemy) && frandom() <= 0.5) {
    M_SetAnimation(self, gunner_move_fire_chain, false);
    return;
  }
  M_SetAnimation(self, gunner_move_endfire_chain, false);
}

// ---------------------------------------------------------------------------
// jumping (PGM)
// ---------------------------------------------------------------------------

function gunner_jump_now(self: EdictT): void {
  const { forward, up } = AngleVectors_destructured(self.s.angles);
  self.velocity = vec3_add(self.velocity, vec3_muls(forward, 100));
  self.velocity = vec3_add(self.velocity, vec3_muls(up, 300));
}

function gunner_jump2_now(self: EdictT): void {
  const { forward, up } = AngleVectors_destructured(self.s.angles);
  self.velocity = vec3_add(self.velocity, vec3_muls(forward, 150));
  self.velocity = vec3_add(self.velocity, vec3_muls(up, 400));
}

function monster_jump_finished(self: EdictT): boolean {
  const { forward } = AngleVectors_destructured(self.s.angles);
  const forward_velocity = vec3_muls(forward, vec3_dot(self.velocity, forward));

  if (vec3_length(forward_velocity) < 150) {
    const z_velocity = self.velocity[2];
    self.velocity = vec3_muls(forward, 150);
    self.velocity[2] = z_velocity;
  }

  return self.monsterinfo.jump_time < level.time;
}

function gunner_jump_wait_land(self: EdictT): void {
  if (self.groundentity === null) {
    self.monsterinfo.nextframe = self.s.frame;

    if (monster_jump_finished(self)) self.monsterinfo.nextframe = self.s.frame + 1;
  } else {
    self.monsterinfo.nextframe = self.s.frame + 1;
  }
}

const gunner_frames_jump: MframeT[] = [
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, gunner_jump_now),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, gunner_jump_wait_land),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const gunner_move_jump = RegisterMmove(
  "gunner_move_jump",
  Object.assign(new MmoveT(), { firstframe: FRAME_jump01, lastframe: FRAME_jump10, frame: gunner_frames_jump, endfunc: (self: EdictT) => gunner_run(self) }),
);

const gunner_frames_jump2: MframeT[] = [
  mkframe(ai_move, -8),
  mkframe(ai_move, -4),
  mkframe(ai_move, -4),
  mkframe(ai_move, 0, gunner_jump2_now),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move, 0, gunner_jump_wait_land),
  mkframe(ai_move),
  mkframe(ai_move),
  mkframe(ai_move),
];
export const gunner_move_jump2 = RegisterMmove(
  "gunner_move_jump2",
  Object.assign(new MmoveT(), { firstframe: FRAME_jump01, lastframe: FRAME_jump10, frame: gunner_frames_jump2, endfunc: (self: EdictT) => gunner_run(self) }),
);

function gunner_jump(self: EdictT, result: BlockedJumpResultT): void {
  if (self.enemy === null) return;

  monster_done_dodge(self);

  if (result === BlockedJumpResultT.JUMP_JUMP_UP) {
    M_SetAnimation(self, gunner_move_jump2, false);
  } else {
    M_SetAnimation(self, gunner_move_jump, false);
  }
}

// ---------------------------------------------------------------------------
// blocked / duck / sidestep (PGM/PMM)
// ---------------------------------------------------------------------------

export const gunner_blocked = RegisterMonsterinfoBlocked("gunner_blocked", (self: EdictT, dist: number): boolean => {
  if (blocked_checkplat(self, dist)) return true;

  const result = blocked_checkjump(self, dist);
  if (result !== BlockedJumpResultT.NO_JUMP) {
    if (result !== BlockedJumpResultT.JUMP_TURN) gunner_jump(self, result);
    return true;
  }

  return false;
});

export const gunner_duck = RegisterMonsterinfoDuck("gunner_duck", (self: EdictT, _eta: GTime): boolean => {
  if (self.monsterinfo.active_move === gunner_move_jump2 || self.monsterinfo.active_move === gunner_move_jump) {
    return false;
  }

  if (
    self.monsterinfo.active_move === gunner_move_attack_chain ||
    self.monsterinfo.active_move === gunner_move_fire_chain ||
    self.monsterinfo.active_move === gunner_move_attack_grenade ||
    self.monsterinfo.active_move === gunner_move_attack_grenade2
  ) {
    // if we're shooting don't dodge
    if (self.monsterinfo.unduck !== null) self.monsterinfo.unduck(self);
    return false;
  }

  if (frandom() > 0.5) GunnerGrenade(self);

  M_SetAnimation(self, gunner_move_duck, false);

  return true;
});

export const gunner_sidestep = RegisterMonsterinfoSidestep("gunner_sidestep", (self: EdictT): boolean => {
  if (self.monsterinfo.active_move === gunner_move_jump2 || self.monsterinfo.active_move === gunner_move_jump || self.monsterinfo.active_move === gunner_move_pain1) {
    return false;
  }

  if (
    self.monsterinfo.active_move === gunner_move_attack_chain ||
    self.monsterinfo.active_move === gunner_move_fire_chain ||
    self.monsterinfo.active_move === gunner_move_attack_grenade ||
    self.monsterinfo.active_move === gunner_move_attack_grenade2
  ) {
    // if we're shooting, don't dodge
    return false;
  }

  if (self.monsterinfo.active_move !== gunner_move_run) M_SetAnimation(self, gunner_move_run, false);

  return true;
});

// ---------------------------------------------------------------------------
// SP_monster_gunner
// ---------------------------------------------------------------------------

const RANGE_NEAR = 440;
const SPAWNFLAG_GUNNER_NOJUMPING = 8;

/*QUAKED monster_gunner (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight NoJumping
model="models/monsters/gunner/tris.md2"
*/
export function SP_monster_gunner(self: EdictT): void {
  if (!M_AllowSpawn(self)) {
    G_FreeEdict(self);
    return;
  }

  assignSound(sound_death, "gunner/death1.wav");
  assignSound(sound_pain, "gunner/gunpain2.wav");
  assignSound(sound_pain2, "gunner/gunpain1.wav");
  assignSound(sound_idle, "gunner/gunidle1.wav");
  assignSound(sound_open, "gunner/gunatck1.wav");
  assignSound(sound_search, "gunner/gunsrch1.wav");
  assignSound(sound_sight, "gunner/sight1.wav");

  gi.soundindex("gunner/gunatck2.wav");
  gi.soundindex("gunner/gunatck3.wav");

  self.movetype = MovetypeT.MOVETYPE_STEP;
  self.solid = SolidT.SOLID_BBOX;
  self.s.modelindex = gi.modelindex("models/monsters/gunner/tris.md2");

  gi.modelindex("models/monsters/gunner/gibs/chest.md2");
  gi.modelindex("models/monsters/gunner/gibs/foot.md2");
  gi.modelindex("models/monsters/gunner/gibs/garm.md2");
  gi.modelindex("models/monsters/gunner/gibs/gun.md2");
  gi.modelindex("models/monsters/gunner/gibs/head.md2");

  self.mins = vec3(-16, -16, -24);
  self.maxs = vec3(16, 16, 36);

  self.health = Math.trunc(175 * st.health_multiplier);
  self.gib_health = -70;
  self.mass = 200;

  self.pain = gunner_pain;
  self.die = gunner_die;

  self.monsterinfo.stand = gunner_stand;
  self.monsterinfo.walk = gunner_walk;
  self.monsterinfo.run = gunner_run;
  // pmm
  self.monsterinfo.dodge = M_MonsterDodge;
  self.monsterinfo.duck = gunner_duck;
  self.monsterinfo.unduck = monster_duck_up;
  self.monsterinfo.sidestep = gunner_sidestep;
  self.monsterinfo.blocked = gunner_blocked; // PGM
  // pmm
  self.monsterinfo.attack = gunner_attack;
  self.monsterinfo.melee = null;
  self.monsterinfo.sight = gunner_sight;
  self.monsterinfo.search = gunner_search;
  self.monsterinfo.setskin = gunner_setskin;

  gi.linkentity(self);

  M_SetAnimation(self, gunner_move_stand, false);
  self.monsterinfo.scale = MODEL_SCALE;

  // PMM
  self.monsterinfo.blindfire = true;
  self.monsterinfo.can_jump = (self.spawnflags & SPAWNFLAG_GUNNER_NOJUMPING) === 0;
  self.monsterinfo.drop_height = 192;
  self.monsterinfo.jump_height = 40;

  walkmonster_start(self);
}
