// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
//
// m_infantry.c -- INFANTRY monster (2023 Quake II re-release / "KEX"
// engine). Ported from ~/Projects/quake2-rerelease-dll/rerelease/
// m_infantry.cpp (928 lines, C++17) + m_infantry.h (280 lines, frame index
// constants "generated by ModelGen"). Combines both into one module, per
// this porting round's brief (frame constants + full behavior, one file per
// monster) -- unlike m_flash.ts/m_player.ts/m_rider.ts, which are pure
// frame-index data ports of files whose .cpp sibling has not landed yet.
// Every mframe_t table below is transcribed row-for-row against the C++
// source and constructed through the landed `MmoveT` class, whose `frame`
// setter throws if the row count doesn't match `lastframe - firstframe + 1`
// (see g_local_types.ts) -- every table in this file matches exactly; no
// `allowFrameCountMismatch` exemption was needed.
//
// ============================================================================
// EXTERNAL / CROSS-CUTTING DEPENDENCIES NOT YET PORTED (throwing stubs, cited)
// ============================================================================
// `blocked_checkjump` and `M_MonsterDodge` are declared in g_local.h but
// DEFINED in rogue/g_rogue_newai.cpp (confirmed by grep -- no such symbol
// exists anywhere in the base rerelease/*.cpp tree). Both are genuinely
// large, generic (non-monster-specific) AI subsystems shared verbatim by
// every KEX monster, not specific to infantry:
// - `blocked_jump_result_t blocked_checkjump(edict_t*, float)`
//   (rogue/g_rogue_newai.cpp:123-~230+): branches on `AI_PATHING`/
//   `nav_path`/`drop_height`/`jump_height` with several `gi.trace` calls;
//   genuinely belongs to a future `rogue/g_rogue_newai.ts` unit, matching
//   this port line's own established precedent for out-of-scope ROGUE
//   content (g_ai.ts's `monster_done_dodge` stub, g_turret.ts's
//   `infantry_*` stubs -- see below). Local throwing stub, cited.
// - `MONSTERINFO_DODGE(M_MonsterDodge)` (rogue/g_rogue_newai.cpp:1304-~1400+):
//   depends on `G_SkillCheck` (skill-cvar-gated RNG, also rogue-only) and is
//   ~100 lines of duck/sidestep decision logic. Local throwing stub, cited.
// `infantry_blocked` (MONSTERINFO_BLOCKED) calls `blocked_checkjump` as its
// primary branch and only falls back to `blocked_checkplat` (ported for
// real below -- self-contained, no nav_path dependency) if that returns
// NO_JUMP; `self.monsterinfo.dodge = M_MonsterDodge` is called from
// `infantry_pain`'s pain-debounce/no-react branches (each ~33% of the time,
// via `frandom() < 0.33`) and from `ai_run`'s own dodge integration
// (g_ai.ts). Both throw today when actually reached -- an honest
// consequence of the missing rogue unit, not a silent behavior change,
// mirroring g_turret.ts's own "SP_turret_driver... always throws today"
// precedent for the identical kind of gap. A future `rogue/g_rogue_newai.ts`
// unit should replace both stubs with real imports.
//
// `monster_done_dodge` (g_local.h decl, defined rogue/g_rogue_monster.cpp:98)
// is a 4-line function with no rogue-specific dependencies (just two
// aiflag/attack_state field writes) -- ported for REAL here (not stubbed),
// duplicating the small helper per-file exactly like g_turret.ts duplicates
// `edictFmt`/`frameTimeAsGtime`/`cvarInt`. g_ai.ts ALSO carries its own
// (unexported, throwing) stub of this same symbol at g_ai.ts:321-323; that
// is NOT swapped here since g_ai.ts is out of this unit's file scope --
// exactly the same "not swapped here" treatment g_monster.ts's own header
// gives g_utils.ts's `G_MonsterKilled` stub. A future unit should replace
// g_ai.ts's stub with a real shared import once a canonical home exists.
//
// `monster_footstep`/`M_CheckGib` are `inline` functions defined directly
// in g_local.h (g_local.h:3282, g_local.h:3521), not in any .cpp -- the
// same "PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY" situation g_monster.ts's
// own header documents for its own g_local.h inlines. Both are tiny and
// self-contained, so both are ported for real here, duplicated per-file per
// that same established precedent.
//
// `PredictAim` (rogue/g_rogue_newai.cpp:1083-1135) is also rogue-authored,
// but it is load-bearing for `InfantryMachineGun` (the monster's only
// ranged attack) and is small/self-contained (no nav_path dependency) --
// ported for REAL here rather than stubbed, since stubbing it would make
// every infantry gunshot throw.
// `monster_duck_down`/`monster_duck_hold`/`monster_duck_up`
// (rogue/g_rogue_newai.cpp:1424-1445) are likewise small and self-contained
// -- ported for real.
//
// ============================================================================
// KNOWN C++ SOURCE QUIRK, PRESERVED BUG-FOR-BUG
// ============================================================================
// `InfantryMachineGun`'s run-attack flash-number expression
// (m_infantry.cpp:287): `MZ2_INFANTRY_MACHINEGUN_14 + (self->s.frame -
// MZ2_INFANTRY_MACHINEGUN_14)` algebraically simplifies to just
// `self->s.frame` (X + (Y - X) == Y) -- almost certainly meant to read
// `MZ2_INFANTRY_MACHINEGUN_14 + (self->s.frame - FRAME_run201)` (the
// pattern the sibling death-frame branch two lines down actually uses:
// `MZ2_INFANTRY_MACHINEGUN_2 + (self->s.frame - FRAME_death211)`). Kept
// exactly as written per this porting round's bug-for-bug mandate --
// `flash_number` ends up being the raw `s.frame` value reinterpreted as a
// `monster_muzzleflash_id_t`, which happens to still land inside the
// MZ2_INFANTRY_MACHINEGUN_14..21 run range numerically close enough that it
// doesn't crash (`monster_flash_offset` has 290 entries), but is not the
// intended flash-position lookup.
//
// ============================================================================
// FRAME CONSTANTS (m_infantry.h, "generated by ModelGen - Do NOT Modify")
// ============================================================================
// Individually exported numeric constants (not a TS enum), matching this
// port line's established m_player.ts/m_rider.ts precedent. Note
// `FRAME_gun02` is index 0 (not `FRAME_stand01`) -- the C anonymous enum's
// declared order, preserved exactly.

export const FRAME_gun02 = 0;
export const FRAME_stand01 = 1;
export const FRAME_stand02 = 2;
export const FRAME_stand03 = 3;
export const FRAME_stand04 = 4;
export const FRAME_stand05 = 5;
export const FRAME_stand06 = 6;
export const FRAME_stand07 = 7;
export const FRAME_stand08 = 8;
export const FRAME_stand09 = 9;
export const FRAME_stand10 = 10;
export const FRAME_stand11 = 11;
export const FRAME_stand12 = 12;
export const FRAME_stand13 = 13;
export const FRAME_stand14 = 14;
export const FRAME_stand15 = 15;
export const FRAME_stand16 = 16;
export const FRAME_stand17 = 17;
export const FRAME_stand18 = 18;
export const FRAME_stand19 = 19;
export const FRAME_stand20 = 20;
export const FRAME_stand21 = 21;
export const FRAME_stand22 = 22;
export const FRAME_stand23 = 23;
export const FRAME_stand24 = 24;
export const FRAME_stand25 = 25;
export const FRAME_stand26 = 26;
export const FRAME_stand27 = 27;
export const FRAME_stand28 = 28;
export const FRAME_stand29 = 29;
export const FRAME_stand30 = 30;
export const FRAME_stand31 = 31;
export const FRAME_stand32 = 32;
export const FRAME_stand33 = 33;
export const FRAME_stand34 = 34;
export const FRAME_stand35 = 35;
export const FRAME_stand36 = 36;
export const FRAME_stand37 = 37;
export const FRAME_stand38 = 38;
export const FRAME_stand39 = 39;
export const FRAME_stand40 = 40;
export const FRAME_stand41 = 41;
export const FRAME_stand42 = 42;
export const FRAME_stand43 = 43;
export const FRAME_stand44 = 44;
export const FRAME_stand45 = 45;
export const FRAME_stand46 = 46;
export const FRAME_stand47 = 47;
export const FRAME_stand48 = 48;
export const FRAME_stand49 = 49;
export const FRAME_stand50 = 50;
export const FRAME_stand51 = 51;
export const FRAME_stand52 = 52;
export const FRAME_stand53 = 53;
export const FRAME_stand54 = 54;
export const FRAME_stand55 = 55;
export const FRAME_stand56 = 56;
export const FRAME_stand57 = 57;
export const FRAME_stand58 = 58;
export const FRAME_stand59 = 59;
export const FRAME_stand60 = 60;
export const FRAME_stand61 = 61;
export const FRAME_stand62 = 62;
export const FRAME_stand63 = 63;
export const FRAME_stand64 = 64;
export const FRAME_stand65 = 65;
export const FRAME_stand66 = 66;
export const FRAME_stand67 = 67;
export const FRAME_stand68 = 68;
export const FRAME_stand69 = 69;
export const FRAME_stand70 = 70;
export const FRAME_stand71 = 71;
export const FRAME_walk01 = 72;
export const FRAME_walk02 = 73;
export const FRAME_walk03 = 74;
export const FRAME_walk04 = 75;
export const FRAME_walk05 = 76;
export const FRAME_walk06 = 77;
export const FRAME_walk07 = 78;
export const FRAME_walk08 = 79;
export const FRAME_walk09 = 80;
export const FRAME_walk10 = 81;
export const FRAME_walk11 = 82;
export const FRAME_walk12 = 83;
export const FRAME_walk13 = 84;
export const FRAME_walk14 = 85;
export const FRAME_walk15 = 86;
export const FRAME_walk16 = 87;
export const FRAME_walk17 = 88;
export const FRAME_walk18 = 89;
export const FRAME_walk19 = 90;
export const FRAME_walk20 = 91;
export const FRAME_run01 = 92;
export const FRAME_run02 = 93;
export const FRAME_run03 = 94;
export const FRAME_run04 = 95;
export const FRAME_run05 = 96;
export const FRAME_run06 = 97;
export const FRAME_run07 = 98;
export const FRAME_run08 = 99;
export const FRAME_pain101 = 100;
export const FRAME_pain102 = 101;
export const FRAME_pain103 = 102;
export const FRAME_pain104 = 103;
export const FRAME_pain105 = 104;
export const FRAME_pain106 = 105;
export const FRAME_pain107 = 106;
export const FRAME_pain108 = 107;
export const FRAME_pain109 = 108;
export const FRAME_pain110 = 109;
export const FRAME_pain201 = 110;
export const FRAME_pain202 = 111;
export const FRAME_pain203 = 112;
export const FRAME_pain204 = 113;
export const FRAME_pain205 = 114;
export const FRAME_pain206 = 115;
export const FRAME_pain207 = 116;
export const FRAME_pain208 = 117;
export const FRAME_pain209 = 118;
export const FRAME_pain210 = 119;
export const FRAME_duck01 = 120;
export const FRAME_duck02 = 121;
export const FRAME_duck03 = 122;
export const FRAME_duck04 = 123;
export const FRAME_duck05 = 124;
export const FRAME_death101 = 125;
export const FRAME_death102 = 126;
export const FRAME_death103 = 127;
export const FRAME_death104 = 128;
export const FRAME_death105 = 129;
export const FRAME_death106 = 130;
export const FRAME_death107 = 131;
export const FRAME_death108 = 132;
export const FRAME_death109 = 133;
export const FRAME_death110 = 134;
export const FRAME_death111 = 135;
export const FRAME_death112 = 136;
export const FRAME_death113 = 137;
export const FRAME_death114 = 138;
export const FRAME_death115 = 139;
export const FRAME_death116 = 140;
export const FRAME_death117 = 141;
export const FRAME_death118 = 142;
export const FRAME_death119 = 143;
export const FRAME_death120 = 144;
export const FRAME_death201 = 145;
export const FRAME_death202 = 146;
export const FRAME_death203 = 147;
export const FRAME_death204 = 148;
export const FRAME_death205 = 149;
export const FRAME_death206 = 150;
export const FRAME_death207 = 151;
export const FRAME_death208 = 152;
export const FRAME_death209 = 153;
export const FRAME_death210 = 154;
export const FRAME_death211 = 155;
export const FRAME_death212 = 156;
export const FRAME_death213 = 157;
export const FRAME_death214 = 158;
export const FRAME_death215 = 159;
export const FRAME_death216 = 160;
export const FRAME_death217 = 161;
export const FRAME_death218 = 162;
export const FRAME_death219 = 163;
export const FRAME_death220 = 164;
export const FRAME_death221 = 165;
export const FRAME_death222 = 166;
export const FRAME_death223 = 167;
export const FRAME_death224 = 168;
export const FRAME_death225 = 169;
export const FRAME_death301 = 170;
export const FRAME_death302 = 171;
export const FRAME_death303 = 172;
export const FRAME_death304 = 173;
export const FRAME_death305 = 174;
export const FRAME_death306 = 175;
export const FRAME_death307 = 176;
export const FRAME_death308 = 177;
export const FRAME_death309 = 178;
export const FRAME_block01 = 179;
export const FRAME_block02 = 180;
export const FRAME_block03 = 181;
export const FRAME_block04 = 182;
export const FRAME_block05 = 183;
export const FRAME_attak101 = 184;
export const FRAME_attak102 = 185;
export const FRAME_attak103 = 186;
export const FRAME_attak104 = 187;
export const FRAME_attak105 = 188;
export const FRAME_attak106 = 189;
export const FRAME_attak107 = 190;
export const FRAME_attak108 = 191;
export const FRAME_attak109 = 192;
export const FRAME_attak110 = 193;
export const FRAME_attak111 = 194;
export const FRAME_attak112 = 195;
export const FRAME_attak113 = 196;
export const FRAME_attak114 = 197;
export const FRAME_attak115 = 198;
export const FRAME_attak201 = 199;
export const FRAME_attak202 = 200;
export const FRAME_attak203 = 201;
export const FRAME_attak204 = 202;
export const FRAME_attak205 = 203;
export const FRAME_attak206 = 204;
export const FRAME_attak207 = 205;
export const FRAME_attak208 = 206;
export const FRAME_jump01 = 207;
export const FRAME_jump02 = 208;
export const FRAME_jump03 = 209;
export const FRAME_jump04 = 210;
export const FRAME_jump05 = 211;
export const FRAME_jump06 = 212;
export const FRAME_jump07 = 213;
export const FRAME_jump08 = 214;
export const FRAME_jump09 = 215;
export const FRAME_jump10 = 216;
export const FRAME_attak301 = 217;
export const FRAME_attak302 = 218;
export const FRAME_attak303 = 219;
export const FRAME_attak304 = 220;
export const FRAME_attak305 = 221;
export const FRAME_attak306 = 222;
export const FRAME_attak307 = 223;
export const FRAME_attak308 = 224;
export const FRAME_attak309 = 225;
export const FRAME_attak310 = 226;
export const FRAME_attak311 = 227;
export const FRAME_attak312 = 228;
export const FRAME_attak313 = 229;
export const FRAME_attak314 = 230;
export const FRAME_attak315 = 231;
export const FRAME_run201 = 232;
export const FRAME_run202 = 233;
export const FRAME_run203 = 234;
export const FRAME_run204 = 235;
export const FRAME_run205 = 236;
export const FRAME_run206 = 237;
export const FRAME_run207 = 238;
export const FRAME_run208 = 239;
export const FRAME_attak401 = 240;
export const FRAME_attak402 = 241;
export const FRAME_attak403 = 242;
export const FRAME_attak404 = 243;
export const FRAME_attak405 = 244;
export const FRAME_attak406 = 245;
export const FRAME_attak407 = 246;
export const FRAME_attak408 = 247;
export const FRAME_attak409 = 248;
export const FRAME_attak410 = 249;
export const FRAME_attak411 = 250;
export const FRAME_attak412 = 251;
export const FRAME_attak413 = 252;
export const FRAME_attak414 = 253;
export const FRAME_attak415 = 254;
export const FRAME_attak416 = 255;
export const FRAME_attak417 = 256;
export const FRAME_attak418 = 257;
export const FRAME_attak419 = 258;
export const FRAME_attak420 = 259;
export const FRAME_attak421 = 260;
export const FRAME_attak422 = 261;
export const FRAME_attak423 = 262;
export const FRAME_attak424 = 263;

export const MODEL_SCALE = 1.0;

import { vec3, type Vec3 } from "../shared/math";
import { AngleVectors, vec3_add, vec3_sub, vec3_muls, vec3_normalized, vec3_length, vec3_dot } from "./q_vec3";
import { type EdictT, type MframeT, MmoveT } from "./g_local_types";
import type { PainFn, DieFn, MonsterinfoStandFn, MonsterinfoIdleFn, MonsterinfoWalkFn, MonsterinfoRunFn, MonsterinfoAttackFn, MonsterinfoSightFn, MonsterinfoSetskinFn, MonsterinfoDuckFn, MonsterinfoSidestepFn, MonsterinfoBlockedFn } from "./g_local_types";
import { type GTime, Gtime_from_ms, Gtime_from_sec, Gtime_add } from "./gtime";
import { monster_duck_up, M_MonsterDodge } from "./m_soldier";
import {
  RANGE_MELEE,
  MELEE_DISTANCE,
  DUCK_INTERVAL,
  MonsterAiFlagsT,
  CombatStyleT,
  MonsterAttackStateT,
  BlockedJumpResultT,
  MovetypeT,
  ModIdT,
  random_time,
} from "./g_local";
import { type SpawnFlags, SpawnFlags_from, SpawnFlags_has } from "./spawnflags";
import { frandom, irandom, brandom } from "./q_std";
import { gi, g_edicts, level } from "./g_main_globals";
import { st } from "./g_spawn";
import { G_FreeEdict } from "./g_utils";
import { fire_hit } from "./g_weapon";
import { T_Damage } from "./g_combat";
import {
  M_SetAnimation,
  M_AllowSpawn,
  M_CheckClearShot,
  M_ProjectFlashSource,
  M_ShouldReactToPain,
  monster_fire_bullet,
  monster_dead,
  monster_think,
  walkmonster_start,
} from "./g_monster";
import { ai_move, ai_stand, ai_walk, ai_run, ai_charge, range_to } from "./g_ai";
import { ai_check_move } from "./m_move";
import { ThrowGib, ThrowGibs, type GibDefT } from "./g_misc";
import { RegisterMmove, RegisterThink, RegisterPain, RegisterDie, RegisterMonsterinfoStand, RegisterMonsterinfoIdle, RegisterMonsterinfoWalk, RegisterMonsterinfoRun, RegisterMonsterinfoAttack, RegisterMonsterinfoSight, RegisterMonsterinfoSetskin, RegisterMonsterinfoDuck, RegisterMonsterinfoSidestep, RegisterMonsterinfoBlocked } from "./g_save_registry";
import { monsterFlashOffset } from "./m_flash";
import { SvflagsT, SolidT, SoundchanT, ATTN_NORM, ATTN_IDLE, MASK_PROJECTILE, MASK_SOLID, MASK_MONSTERSOLID, KexEntityEventT, MonsterMuzzleflashIdT, type KexTraceT, type KexEdictT, type ContentsT } from "../kexapi/game";
import type { ModT } from "./g_local_types";

// g_local.h's DEFAULT_BULLET_HSPREAD/VSPREAD -- not centralized anywhere in
// the header modules (p_weapon.ts/m_tank.ts/legacy m_soldier.ts each keep
// their own module-local copy too, per that established precedent).
const DEFAULT_BULLET_HSPREAD = 300;
const DEFAULT_BULLET_VSPREAD = 500;

// range at which we'll try to initiate a run-attack to close distance
// (m_infantry.cpp:31)
const RANGE_RUN_ATTACK = 440 * 0.75; // RANGE_NEAR * 0.75f (g_local.ts's RANGE_NEAR)

/** g_local.h:468-469's `FRAME_TIME_S`, worked around per g_phys.ts's/
 *  g_ai.ts's identical `frameTimeAsGtime()` precedent (no InitGame-set
 *  global exists yet in this port line). */
function frameTimeAsGtime(): GTime {
  return Gtime_from_ms(gi.frame_time_ms);
}

/** g_local.h:136-139 `game_import_t::traceline` -- duplicated per-file,
 *  matching g_monster.ts's own (unexported) `giTraceline` precedent (see
 *  its file header's "PLACEMENT-MISMATCH FUNCTIONS PORTED LOCALLY"). */
function giTraceline(start: Vec3, end: Vec3, passent: EdictT | null, mask: ContentsT): KexTraceT {
  return gi.trace(start, null, null, end, passent, mask);
}

/** EDICT_NUM idiom -- duplicated per-file, matching g_monster.ts's/
 *  g_phys.ts's own `traceEdict` precedent (a trace's `.ent` comes back
 *  typed as the narrower `KexEdictT`; this recovers the real `EdictT` via
 *  `g_edicts[]`). */
function traceEdict(ent: KexEdictT | null): EdictT {
  if (ent === null) return g_edicts[0];
  return g_edicts[ent.s.number];
}

// ============================================================================
// Locally-ported small cross-file dependencies (see file header)
// ============================================================================

/** g_local.h:3282 (inline). [Paril-KEX] */
function monster_footstep(self: EdictT): void {
  if (self.groundentity) self.s.event = KexEntityEventT.EV_OTHER_FOOTSTEP;
}

/** g_local.h:3521 (inline). */
function M_CheckGib(self: EdictT, mod: ModT): boolean {
  if (self.deadflag) {
    if (mod.id === ModIdT.MOD_CRUSH) return true;
  }
  return self.health <= self.gib_health;
}

/** rogue/g_rogue_monster.cpp:98. See file header -- ported for real (tiny,
 *  no rogue-specific dependencies), duplicating g_ai.ts's own (unexported,
 *  throwing) stub of the same symbol. */
function monster_done_dodge(self: EdictT): void {
  self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_DODGING;
  if (self.monsterinfo.attack_state === MonsterAttackStateT.AS_SLIDING) {
    self.monsterinfo.attack_state = MonsterAttackStateT.AS_STRAIGHT;
  }
}

/** rogue/g_rogue_newai.cpp:1424. */
function monster_duck_down(self: EdictT): void {
  self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_DUCKED;
  self.maxs[2] = self.monsterinfo.base_height - 32;
  self.takedamage = true;
  self.monsterinfo.next_duck_time = Gtime_add(level.time, DUCK_INTERVAL);
  gi.linkentity(self);
}

/** rogue/g_rogue_newai.cpp:1434. */
function monster_duck_hold(self: EdictT): void {
  if (level.time >= self.monsterinfo.duck_wait_time) {
    self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_HOLD_FRAME;
  } else {
    self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_HOLD_FRAME;
  }
}

// rogue/g_rogue_newai.cpp:~1440 (MONSTERINFO_UNDUCK) -- `monster_duck_up` is
// monster-agnostic rogue-newai infrastructure, imported from m_soldier.ts
// (its canonical, exported home in this porting batch) rather than
// re-registered here under the same name: g_save_registry.ts's
// monsterinfo_unduck registry is global and name-keyed, so a second local
// copy registered as "monster_duck_up" would throw a duplicate-registration
// error the instant both files load in the same process (as g_spawn.ts's
// real monster table does). See m_soldier.ts's own comment on this export.

/** rogue/g_rogue_newai.cpp:1083-1135. Ported for real -- see file header
 *  ("load-bearing for InfantryMachineGun"). `aimdir`/`aimpoint` mutate the
 *  passed Vec3 in place (matching AngleVectors's established
 *  reference-out-param idiom), rather than the C++ pointer-write, since a
 *  bare TS reassignment of a Vec3 parameter would not be visible to the
 *  caller. The C++ unconditionally dereferences `aimdir` when the target is
 *  missing (`*aimdir = {}`); every real call site always passes a non-null
 *  aimdir, so this port keeps that same assumption without adding a
 *  defensive null branch that isn't in the source. */
function PredictAim(
  self: EdictT,
  target: EdictT | null,
  start: Vec3,
  bolt_speed: number,
  eyeHeightIn: boolean,
  offset: number,
  aimdir: Vec3 | null,
  aimpoint: Vec3 | null,
): void {
  if (!target || !target.inuse) {
    if (aimdir) {
      aimdir[0] = 0;
      aimdir[1] = 0;
      aimdir[2] = 0;
    }
    return;
  }

  let eye_height = eyeHeightIn;
  let dir = vec3_sub(target.s.origin, start);
  if (eye_height) dir[2] += target.viewheight;
  let dist = vec3_length(dir);

  // [Paril-KEX] if our current attempt is blocked, try the opposite one
  const tr = giTraceline(start, vec3_add(start, dir), self, MASK_PROJECTILE);

  if (traceEdict(tr.ent) !== target) {
    eye_height = !eye_height;
    dir = vec3_sub(target.s.origin, start);
    if (eye_height) dir[2] += target.viewheight;
    dist = vec3_length(dir);
  }

  const time = bolt_speed !== 0 ? dist / bolt_speed : 0;

  let vec = vec3_add(target.s.origin, vec3_muls(target.velocity, time - offset));

  // went backwards...
  if (vec3_dot(vec3_normalized(dir), vec3_normalized(vec3_sub(vec, start))) < 0) {
    vec = vec3(target.s.origin[0], target.s.origin[1], target.s.origin[2]);
  } else {
    // if the shot is going to impact a nearby wall from our prediction, just fire it straight.
    if (giTraceline(start, vec, null, MASK_SOLID).fraction < 0.9) {
      vec = vec3(target.s.origin[0], target.s.origin[1], target.s.origin[2]);
    }
  }

  if (eye_height) vec[2] += target.viewheight;

  if (aimdir) {
    const ad = vec3_normalized(vec3_sub(vec, start));
    aimdir[0] = ad[0];
    aimdir[1] = ad[1];
    aimdir[2] = ad[2];
  }
  if (aimpoint) {
    aimpoint[0] = vec[0];
    aimpoint[1] = vec[1];
    aimpoint[2] = vec[2];
  }
}

/** rogue/g_rogue_newai.cpp:14-88. Ported for real -- self-contained, no
 *  nav_path dependency (unlike its sibling `blocked_checkjump`, stubbed
 *  below). `world` is `g_edicts[0]`, matching g_phys.ts's own established
 *  idiom for the same C++ global. `strncmp(classname, "func_plat", 8)`
 *  becomes `.startsWith("func_plat")` -- equivalent for every classname
 *  this codebase actually spawns ("func_plat"/"func_plat2"). */
function blocked_checkplat(self: EdictT, dist: number): boolean {
  if (!self.enemy) return false;

  let playerPosition: number;
  if (self.enemy.absmin[2] >= self.absmax[2]) playerPosition = 1;
  else if (self.enemy.absmax[2] <= self.absmin[2]) playerPosition = -1;
  else playerPosition = 0;

  if (playerPosition === 0) return false;

  let plat: EdictT | null = null;

  if (self.groundentity !== null && self.groundentity !== g_edicts[0] && (self.groundentity.classname ?? "").startsWith("func_plat")) {
    plat = self.groundentity;
  }

  if (!plat) {
    const forward = vec3(0, 0, 0);
    AngleVectors(self.s.angles, forward, null, null);
    const pt1 = vec3_add(self.s.origin, vec3_muls(forward, dist));
    const pt2 = vec3(pt1[0], pt1[1], pt1[2] - 384);

    const trace = giTraceline(pt1, pt2, self, MASK_MONSTERSOLID);
    if (trace.fraction < 1 && !trace.allsolid && !trace.startsolid && trace.ent !== null) {
      const traceEnt = traceEdict(trace.ent);
      if ((traceEnt.classname ?? "").startsWith("func_plat")) plat = traceEnt;
    }
  }

  if (plat && plat.use) {
    if (playerPosition === 1) {
      if (
        (self.groundentity === plat && plat.moveinfo.state === 1 /* STATE_BOTTOM */) ||
        (self.groundentity !== plat && plat.moveinfo.state === 0 /* STATE_TOP */)
      ) {
        plat.use(plat, self, self);
        return true;
      }
    } else if (playerPosition === -1) {
      if (
        (self.groundentity === plat && plat.moveinfo.state === 0 /* STATE_TOP */) ||
        (self.groundentity !== plat && plat.moveinfo.state === 1 /* STATE_BOTTOM */)
      ) {
        plat.use(plat, self, self);
        return true;
      }
    }
  }

  return false;
}

/** rogue/g_rogue_newai.cpp:123-~230+. See file header -- genuinely large
 *  ROGUE nav-path-integrated logic shared verbatim by every KEX monster;
 *  out of scope for this single-monster unit. Throwing stub, cited. */
function blocked_checkjump(_self: EdictT, _dist: number): BlockedJumpResultT {
  throw new Error("blocked_checkjump: not yet ported (pending rogue/g_rogue_newai.ts, see rogue/g_rogue_newai.cpp:123)");
}

// rogue/g_rogue_newai.cpp:1304-1422. Superseded: this file originally
// carried a throwing stub here ("not yet ported"), which meant infantry_pain
// would crash the instant its ~33%-chance dodge branch fired. m_soldier.ts
// ported this for real (it's monster-agnostic rogue-newai infrastructure,
// not soldier-specific) and exports it; importing it here both fixes the
// throw and avoids a duplicate "M_MonsterDodge" registration in
// g_save_registry.ts's global, name-keyed monsterinfo_dodge registry, which
// would otherwise throw the instant both files load in the same process
// (as g_spawn.ts's real monster table does). Assigned to
// `self.monsterinfo.dodge` in `SP_monster_infantry` below, matching the
// C++ source exactly.

// ============================================================================
// Sounds (cached_soundindex family -- assigned once in InfantryPrecache)
// ============================================================================

let sound_pain1 = 0;
let sound_pain2 = 0;
let sound_die1 = 0;
let sound_die2 = 0;
let sound_gunshot = 0;
let sound_weapon_cock = 0;
let sound_punch_swing = 0;
let sound_punch_hit = 0;
let sound_sight = 0;
let sound_search = 0;
let sound_idle = 0;

// ============================================================================
// STAND
// ============================================================================

const infantry_frames_stand: MframeT[] = Array.from({ length: 22 }, () => ({ aifunc: ai_stand, dist: 0, thinkfunc: null, lerp_frame: -1 }));
const infantry_move_stand = RegisterMmove("infantry_move_stand", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_stand50;
  m.lastframe = FRAME_stand71;
  m.frame = infantry_frames_stand;
  m.endfunc = null;
  return m;
})());

export const infantry_stand: MonsterinfoStandFn = RegisterMonsterinfoStand("infantry_stand", (self: EdictT): void => {
  M_SetAnimation(self, infantry_move_stand, false);
});

// ============================================================================
// FIDGET (idle)
// ============================================================================

function mk(aifunc: MframeT["aifunc"], dist = 0, thinkfunc: MframeT["thinkfunc"] = null, lerp_frame = -1): MframeT {
  return { aifunc, dist, thinkfunc, lerp_frame };
}

const infantry_frames_fidget: MframeT[] = [
  mk(ai_stand, 1),
  mk(ai_stand),
  mk(ai_stand, 1),
  mk(ai_stand, 3),
  mk(ai_stand, 6),
  mk(ai_stand, 3, monster_footstep),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand, 1),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand, 1),
  mk(ai_stand),
  mk(ai_stand, -1),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand, 1),
  mk(ai_stand),
  mk(ai_stand, -2),
  mk(ai_stand, 1),
  mk(ai_stand, 1),
  mk(ai_stand, 1),
  mk(ai_stand, -1),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand, -1),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand, -1),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand, 1),
  mk(ai_stand),
  mk(ai_stand),
  mk(ai_stand, -1),
  mk(ai_stand, -1),
  mk(ai_stand),
  mk(ai_stand, -3),
  mk(ai_stand, -2),
  mk(ai_stand, -3),
  mk(ai_stand, -3, monster_footstep),
  mk(ai_stand, -2),
];
const infantry_move_fidget = RegisterMmove("infantry_move_fidget", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_stand01;
  m.lastframe = FRAME_stand49;
  m.frame = infantry_frames_fidget;
  m.endfunc = (self) => infantry_stand(self);
  return m;
})());

const infantry_fidget: MonsterinfoIdleFn = RegisterMonsterinfoIdle("infantry_fidget", (self: EdictT): void => {
  if (self.enemy) return;

  M_SetAnimation(self, infantry_move_fidget, false);
  gi.sound(self, SoundchanT.CHAN_VOICE, sound_idle, 1, ATTN_IDLE, 0);
});

// ============================================================================
// WALK
// ============================================================================

const infantry_frames_walk: MframeT[] = [
  mk(ai_walk, 5, monster_footstep),
  mk(ai_walk, 4),
  mk(ai_walk, 4),
  mk(ai_walk, 5),
  mk(ai_walk, 4),
  mk(ai_walk, 5),
  mk(ai_walk, 6, monster_footstep),
  mk(ai_walk, 4),
  mk(ai_walk, 4),
  mk(ai_walk, 4),
  mk(ai_walk, 4),
  mk(ai_walk, 5),
];
const infantry_move_walk = RegisterMmove("infantry_move_walk", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_walk03;
  m.lastframe = FRAME_walk14;
  m.frame = infantry_frames_walk;
  m.endfunc = null;
  return m;
})());

const infantry_walk: MonsterinfoWalkFn = RegisterMonsterinfoWalk("infantry_walk", (self: EdictT): void => {
  M_SetAnimation(self, infantry_move_walk, false);
});

// ============================================================================
// RUN
// ============================================================================

const infantry_frames_run: MframeT[] = [
  mk(ai_run, 10),
  mk(ai_run, 15, monster_footstep),
  mk(ai_run, 5),
  mk(ai_run, 7, monster_done_dodge),
  mk(ai_run, 18),
  mk(ai_run, 20, monster_footstep),
  mk(ai_run, 2),
  mk(ai_run, 6),
];
const infantry_move_run = RegisterMmove("infantry_move_run", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_run01;
  m.lastframe = FRAME_run08;
  m.frame = infantry_frames_run;
  m.endfunc = null;
  return m;
})());

const infantry_run: MonsterinfoRunFn = RegisterMonsterinfoRun("infantry_run", (self: EdictT): void => {
  monster_done_dodge(self);

  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) !== 0n) {
    M_SetAnimation(self, infantry_move_stand, false);
  } else {
    M_SetAnimation(self, infantry_move_run, false);
  }
});

// ============================================================================
// PAIN
// ============================================================================

const infantry_frames_pain1: MframeT[] = [
  mk(ai_move, -3),
  mk(ai_move, -2),
  mk(ai_move, -1),
  mk(ai_move, -2),
  mk(ai_move, -1, monster_footstep),
  mk(ai_move, 1),
  mk(ai_move, -1),
  mk(ai_move, 1),
  mk(ai_move, 6),
  mk(ai_move, 2, monster_footstep),
];
const infantry_move_pain1 = RegisterMmove("infantry_move_pain1", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_pain101;
  m.lastframe = FRAME_pain110;
  m.frame = infantry_frames_pain1;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

const infantry_frames_pain2: MframeT[] = [
  mk(ai_move, -3),
  mk(ai_move, -3),
  mk(ai_move),
  mk(ai_move, -1),
  mk(ai_move, -2, monster_footstep),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move, 2),
  mk(ai_move, 5),
  mk(ai_move, 2, monster_footstep),
];
const infantry_move_pain2 = RegisterMmove("infantry_move_pain2", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_pain201;
  m.lastframe = FRAME_pain210;
  m.frame = infantry_frames_pain2;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

export const infantry_pain: PainFn = RegisterPain("infantry_pain", (self: EdictT, other: EdictT, _kick: number, _damage: number, mod: ModT): void => {
  // allow turret to pain
  if ((self.monsterinfo.active_move === infantry_move_jump || self.monsterinfo.active_move === infantry_move_jump2) && self.think === monster_think) {
    return;
  }

  monster_done_dodge(self);

  if (level.time < self.pain_debounce_time) {
    if (self.think === monster_think && frandom() < 0.33) {
      self.monsterinfo.dodge?.(self, other, frameTimeAsGtime(), null, false);
    }
    return;
  }

  self.pain_debounce_time = Gtime_add(level.time, Gtime_from_sec(3));

  const n = brandom() ? 1 : 0;

  if (n === 0) gi.sound(self, SoundchanT.CHAN_VOICE, sound_pain1, 1, ATTN_NORM, 0);
  else gi.sound(self, SoundchanT.CHAN_VOICE, sound_pain2, 1, ATTN_NORM, 0);

  if (self.think !== monster_think) return;

  if (!M_ShouldReactToPain(self, mod)) {
    if (self.think === monster_think && frandom() < 0.33) {
      self.monsterinfo.dodge?.(self, other, frameTimeAsGtime(), null, false);
    }
    return; // no pain anims in nightmare
  }

  if (n === 0) M_SetAnimation(self, infantry_move_pain1, false);
  else M_SetAnimation(self, infantry_move_pain2, false);

  // PMM - clear duck flag
  if ((self.monsterinfo.aiflags & MonsterAiFlagsT.AI_DUCKED) !== 0n) {
    monster_duck_up(self);
  }
});

export const infantry_setskin: MonsterinfoSetskinFn = RegisterMonsterinfoSetskin("infantry_setskin", (self: EdictT): void => {
  if (self.health < self.max_health / 2) self.s.skinnum = 1;
  else self.s.skinnum = 0;
});

// ============================================================================
// MACHINEGUN ATTACK
// ============================================================================

const aimangles: readonly Vec3[] = [
  vec3(0.0, 5.0, 0.0),
  vec3(10.0, 15.0, 0.0),
  vec3(20.0, 25.0, 0.0),
  vec3(25.0, 35.0, 0.0),
  vec3(30.0, 40.0, 0.0),
  vec3(30.0, 45.0, 0.0),
  vec3(25.0, 50.0, 0.0),
  vec3(20.0, 40.0, 0.0),
  vec3(15.0, 35.0, 0.0),
  vec3(40.0, 35.0, 0.0),
  vec3(70.0, 35.0, 0.0),
  vec3(90.0, 35.0, 0.0),
];

/** m_infantry.cpp:272-314. See file header's "KNOWN C++ SOURCE QUIRK" note
 *  for the run-attack flash_number expression. */
function InfantryMachineGun(self: EdictT): void {
  if (!self.enemy || !self.enemy.inuse) return; // PGM

  const is_run_attack = self.s.frame >= FRAME_run201 && self.s.frame <= FRAME_run208;

  let flash_number: number;
  let start: Vec3;
  let forward = vec3(0, 0, 0);
  let right = vec3(0, 0, 0);

  if (self.s.frame === FRAME_attak103 || self.s.frame === FRAME_attak311 || is_run_attack || self.s.frame === FRAME_attak416) {
    if (is_run_attack) {
      // See file header "KNOWN C++ SOURCE QUIRK" -- preserved bug-for-bug.
      flash_number = MonsterMuzzleflashIdT.MZ2_INFANTRY_MACHINEGUN_14 + (self.s.frame - MonsterMuzzleflashIdT.MZ2_INFANTRY_MACHINEGUN_14);
    } else if (self.s.frame === FRAME_attak416) {
      flash_number = MonsterMuzzleflashIdT.MZ2_INFANTRY_MACHINEGUN_22;
    } else {
      flash_number = MonsterMuzzleflashIdT.MZ2_INFANTRY_MACHINEGUN_1;
    }
    AngleVectors(self.s.angles, forward, right, null);
    start = M_ProjectFlashSource(self, monsterFlashOffset()[flash_number], forward, right);

    if (self.enemy) {
      PredictAim(self, self.enemy, start, 0, true, -0.2, forward, null);
    } else {
      AngleVectors(self.s.angles, forward, right, null);
    }
  } else {
    flash_number = MonsterMuzzleflashIdT.MZ2_INFANTRY_MACHINEGUN_2 + (self.s.frame - FRAME_death211);

    AngleVectors(self.s.angles, forward, right, null);
    start = M_ProjectFlashSource(self, monsterFlashOffset()[flash_number], forward, right);

    const vec = vec3_sub(self.s.angles, aimangles[flash_number - MonsterMuzzleflashIdT.MZ2_INFANTRY_MACHINEGUN_2]);
    forward = vec3(0, 0, 0);
    AngleVectors(vec, forward, null, null);
  }

  monster_fire_bullet(self, start, forward, 3, 4, DEFAULT_BULLET_HSPREAD, DEFAULT_BULLET_VSPREAD, flash_number);
}

const infantry_sight: MonsterinfoSightFn = RegisterMonsterinfoSight("infantry_sight", (self: EdictT, _other: EdictT): void => {
  if (brandom()) gi.sound(self, SoundchanT.CHAN_VOICE, sound_sight, 1, ATTN_NORM, 0);
  else gi.sound(self, SoundchanT.CHAN_VOICE, sound_search, 1, ATTN_NORM, 0);
});

// ============================================================================
// DEATH
// ============================================================================

function infantry_dead(self: EdictT): void {
  self.mins = vec3(-16, -16, -24);
  self.maxs = vec3(16, 16, -8);
  monster_dead(self);
}

function infantry_shrink(self: EdictT): void {
  self.maxs[2] = 0;
  self.svflags |= SvflagsT.SVF_DEADMONSTER;
  gi.linkentity(self);
}

const infantry_frames_death1: MframeT[] = [
  mk(ai_move, -4, null, FRAME_death102),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move, -1),
  mk(ai_move, -4, monster_footstep),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move, -1, monster_footstep),
  mk(ai_move, 3),
  mk(ai_move, 1),
  mk(ai_move, 1),
  mk(ai_move, -2),
  mk(ai_move, 2),
  mk(ai_move, 2),
  mk(ai_move, 9, (self) => {
    infantry_shrink(self);
    monster_footstep(self);
  }),
  mk(ai_move, 9),
  mk(ai_move, 5, monster_footstep),
  mk(ai_move, -3),
  mk(ai_move, -3),
];
const infantry_move_death1 = RegisterMmove("infantry_move_death1", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_death101;
  m.lastframe = FRAME_death120;
  m.frame = infantry_frames_death1;
  m.endfunc = (self) => infantry_dead(self);
  return m;
})());

// Off with his head
const infantry_frames_death2: MframeT[] = [
  mk(ai_move, 0, null, FRAME_death202),
  mk(ai_move, 1),
  mk(ai_move, 5),
  mk(ai_move, -1),
  mk(ai_move),
  mk(ai_move, 1, monster_footstep),
  mk(ai_move, 1, monster_footstep),
  mk(ai_move, 4),
  mk(ai_move, 3),
  mk(ai_move),
  mk(ai_move, -2, InfantryMachineGun),
  mk(ai_move, -2, InfantryMachineGun),
  mk(ai_move, -3, InfantryMachineGun),
  mk(ai_move, -1, InfantryMachineGun),
  mk(ai_move, -2, InfantryMachineGun),
  mk(ai_move, 0, InfantryMachineGun),
  mk(ai_move, 2, InfantryMachineGun),
  mk(ai_move, 2, InfantryMachineGun),
  mk(ai_move, 3, InfantryMachineGun),
  mk(ai_move, -10, InfantryMachineGun),
  mk(ai_move, -7, InfantryMachineGun),
  mk(ai_move, -8, InfantryMachineGun),
  mk(ai_move, -6, (self) => {
    infantry_shrink(self);
    monster_footstep(self);
  }),
  mk(ai_move, 4),
  mk(ai_move),
];
const infantry_move_death2 = RegisterMmove("infantry_move_death2", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_death201;
  m.lastframe = FRAME_death225;
  m.frame = infantry_frames_death2;
  m.endfunc = (self) => infantry_dead(self);
  return m;
})());

const infantry_frames_death3: MframeT[] = [
  mk(ai_move, 0),
  mk(ai_move),
  mk(ai_move, 0, (self) => {
    infantry_shrink(self);
    monster_footstep(self);
  }),
  mk(ai_move, -6),
  mk(ai_move, -11, (self) => {
    self.monsterinfo.nextframe = FRAME_death307;
  }),
  mk(ai_move, -3),
  mk(ai_move, -11),
  mk(ai_move, 0, monster_footstep),
  mk(ai_move),
];
const infantry_move_death3 = RegisterMmove("infantry_move_death3", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_death301;
  m.lastframe = FRAME_death309;
  m.frame = infantry_frames_death3;
  m.endfunc = (self) => infantry_dead(self);
  return m;
})());

export const infantry_die: DieFn = RegisterDie("infantry_die", (self: EdictT, inflictor: EdictT, _attacker: EdictT, damage: number, _point: Vec3, mod: ModT): void => {
  // check for gib
  if (M_CheckGib(self, mod)) {
    gi.sound(self, SoundchanT.CHAN_VOICE, gi.soundindex("misc/udeath.wav"), 1, ATTN_NORM, 0);

    const head_gib = self.monsterinfo.active_move !== infantry_move_death3 ? "models/objects/gibs/sm_meat/tris.md2" : "models/monsters/infantry/gibs/head.md2";

    self.s.skinnum = Math.trunc(self.s.skinnum / 2);

    const gibs: GibDefT[] = [
      { gibname: "models/objects/gibs/bone/tris.md2" },
      { count: 3, gibname: "models/objects/gibs/sm_meat/tris.md2" },
      { gibname: "models/monsters/infantry/gibs/chest.md2", type: 16 /* GIB_SKINNED */ },
      { gibname: "models/monsters/infantry/gibs/gun.md2", type: 16 | 32 /* GIB_SKINNED | GIB_UPRIGHT */ },
      { count: 2, gibname: "models/monsters/infantry/gibs/foot.md2", type: 16 /* GIB_SKINNED */ },
      { count: 2, gibname: "models/monsters/infantry/gibs/arm.md2", type: 16 /* GIB_SKINNED */ },
      { gibname: head_gib, type: 4 | 16 /* GIB_HEAD | GIB_SKINNED */ },
    ];
    ThrowGibs(self, damage, gibs);
    self.deadflag = true;
    return;
  }

  if (self.deadflag) return;

  // regular death
  self.deadflag = true;
  self.takedamage = true;

  const n = irandom(3);

  if (n === 0) {
    M_SetAnimation(self, infantry_move_death1, false);
    gi.sound(self, SoundchanT.CHAN_VOICE, sound_die2, 1, ATTN_NORM, 0);
  } else if (n === 1) {
    M_SetAnimation(self, infantry_move_death2, false);
    gi.sound(self, SoundchanT.CHAN_VOICE, sound_die1, 1, ATTN_NORM, 0);
  } else {
    M_SetAnimation(self, infantry_move_death3, false);
    gi.sound(self, SoundchanT.CHAN_VOICE, sound_die2, 1, ATTN_NORM, 0);
  }

  // don't always pop a head gib, it gets old
  if (n !== 2 && frandom() <= 0.25) {
    const head = ThrowGib(self, "models/monsters/infantry/gibs/head.md2", damage, 0 /* GIB_NONE */, self.s.scale);

    if (head) {
      head.s.angles = vec3(self.s.angles[0], self.s.angles[1], self.s.angles[2]);
      head.s.origin = vec3_add(self.s.origin, vec3(0, 0, 32));
      const headDir = vec3_sub(self.s.origin, inflictor.s.origin);
      const len = vec3_length(headDir);
      head.velocity = len !== 0 ? vec3_muls(headDir, 100.0 / len) : vec3(0, 0, 0);
      head.velocity[2] = 200.0;
      head.avelocity = vec3_muls(head.avelocity, 0.15);
      head.s.skinnum = 0;
      gi.linkentity(head);
    }
  }
});

// ============================================================================
// DUCK
// ============================================================================

const infantry_frames_duck: MframeT[] = [mk(ai_move, -2, monster_duck_down), mk(ai_move, -5, monster_duck_hold), mk(ai_move, 3), mk(ai_move, 4, monster_duck_up), mk(ai_move)];
const infantry_move_duck = RegisterMmove("infantry_move_duck", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_duck01;
  m.lastframe = FRAME_duck05;
  m.frame = infantry_frames_duck;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

// ============================================================================
// ATTACK 1 (cock-less, already cocked)
// ============================================================================

function infantry_set_firetime(self: EdictT): void {
  self.monsterinfo.fire_wait = Gtime_add(level.time, random_time(Gtime_from_ms(700), Gtime_from_ms(2000)));

  if (
    (self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) === 0n &&
    self.enemy &&
    range_to(self, self.enemy) >= RANGE_RUN_ATTACK &&
    ai_check_move(self, 8.0)
  ) {
    M_SetAnimation(self, infantry_move_attack4, false);
  }
}

function infantry_cock_gun(self: EdictT): void {
  gi.sound(self, SoundchanT.CHAN_WEAPON, sound_weapon_cock, 1, ATTN_NORM, 0);
  // gun cocked
  self.count = 1;
}

function infantry_fire(self: EdictT): void {
  InfantryMachineGun(self);

  // we fired, so we must cock again before firing
  self.count = 0;

  // check if we ran out of firing time
  if (self.monsterinfo.active_move === infantry_move_attack4) {
    if (level.time >= self.monsterinfo.fire_wait) {
      monster_done_dodge(self);
      M_SetAnimation(self, infantry_move_attack1, false);
      self.monsterinfo.nextframe = FRAME_attak114;
    } else if (!ai_check_move(self, 8.0)) {
      // got close to an edge
      M_SetAnimation(self, infantry_move_attack1, false);
      self.monsterinfo.nextframe = FRAME_attak103;
      monster_done_dodge(self);
      self.monsterinfo.attack_state = MonsterAttackStateT.AS_STRAIGHT;
    }
  } else if (
    (self.s.frame >= FRAME_attak101 && self.s.frame <= FRAME_attak115) ||
    (self.s.frame >= FRAME_attak301 && self.s.frame <= FRAME_attak315) ||
    (self.s.frame >= FRAME_attak401 && self.s.frame <= FRAME_attak424)
  ) {
    if (level.time >= self.monsterinfo.fire_wait) {
      self.monsterinfo.aiflags &= ~MonsterAiFlagsT.AI_HOLD_FRAME;

      if (self.s.frame === FRAME_attak416) self.monsterinfo.nextframe = FRAME_attak420;
    } else {
      self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_HOLD_FRAME;
    }
  }
}

const infantry_frames_attack1: MframeT[] = [
  mk(ai_charge),
  mk(ai_charge, 6, (self) => {
    infantry_set_firetime(self);
    monster_footstep(self);
  }),
  mk(ai_charge, 0, infantry_fire),
  mk(ai_charge),
  mk(ai_charge, 1),
  mk(ai_charge, -7),
  mk(ai_charge, -6, (self) => {
    self.monsterinfo.nextframe = FRAME_attak114;
    monster_footstep(self);
  }),
  // dead frames start
  mk(ai_charge, -1),
  mk(ai_charge, 0, infantry_cock_gun),
  mk(ai_charge),
  mk(ai_charge),
  mk(ai_charge),
  mk(ai_charge),
  // dead frames end
  mk(ai_charge, -1),
  mk(ai_charge, -1),
];
const infantry_move_attack1 = RegisterMmove("infantry_move_attack1", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_attak101;
  m.lastframe = FRAME_attak115;
  m.frame = infantry_frames_attack1;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

// old animation, full cock + shoot
const infantry_frames_attack3: MframeT[] = [
  mk(ai_charge, 4),
  mk(ai_charge, -1),
  mk(ai_charge, -1),
  mk(ai_charge, 0, infantry_cock_gun),
  mk(ai_charge, -1),
  mk(ai_charge, 1),
  mk(ai_charge, 1),
  mk(ai_charge, 2),
  mk(ai_charge, -2),
  mk(ai_charge, -3, (self) => {
    infantry_set_firetime(self);
    monster_footstep(self);
  }),
  mk(ai_charge, 1, infantry_fire),
  mk(ai_charge, 5),
  mk(ai_charge, -1),
  mk(ai_charge, -2),
  mk(ai_charge, -3),
];
const infantry_move_attack3 = RegisterMmove("infantry_move_attack3", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_attak301;
  m.lastframe = FRAME_attak315;
  m.frame = infantry_frames_attack3;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

// even older animation, full cock + shoot
const infantry_frames_attack5: MframeT[] = [
  // skipped frames
  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0),

  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0, monster_footstep),
  mk(ai_charge, 0, infantry_cock_gun),
  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0, (self) => {
    self.monsterinfo.nextframe = self.s.frame + 1;
  }),
  mk(ai_charge, 0), // skipped frame
  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0, infantry_set_firetime),
  mk(ai_charge, 0, infantry_fire),

  // skipped frames
  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0),

  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0),
  mk(ai_charge, 0, monster_footstep),
];
const infantry_move_attack5 = RegisterMmove("infantry_move_attack5", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_attak401;
  m.lastframe = FRAME_attak423;
  m.frame = infantry_frames_attack5;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

function infantry_swing(self: EdictT): void {
  gi.sound(self, SoundchanT.CHAN_WEAPON, sound_punch_swing, 1, ATTN_NORM, 0);
}

function infantry_smack(self: EdictT): void {
  const aim = vec3(MELEE_DISTANCE, 0, 0);

  if (fire_hit(self, aim, irandom(5, 10), 50)) {
    gi.sound(self, SoundchanT.CHAN_WEAPON, sound_punch_hit, 1, ATTN_NORM, 0);
  } else {
    self.monsterinfo.melee_debounce_time = Gtime_add(level.time, Gtime_from_ms(1500));
  }
}

const infantry_frames_attack2: MframeT[] = [
  mk(ai_charge, 3),
  mk(ai_charge, 6),
  mk(ai_charge, 0, infantry_swing),
  mk(ai_charge, 8, monster_footstep),
  mk(ai_charge, 5),
  mk(ai_charge, 8, infantry_smack),
  mk(ai_charge, 6),
  mk(ai_charge, 3),
];
const infantry_move_attack2 = RegisterMmove("infantry_move_attack2", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_attak201;
  m.lastframe = FRAME_attak208;
  m.frame = infantry_frames_attack2;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

// [Paril-KEX] run-attack, inspired by q2test
function infantry_attack4_refire(self: EdictT): void {
  // ran out of firing time
  if (level.time >= self.monsterinfo.fire_wait) {
    monster_done_dodge(self);
    M_SetAnimation(self, infantry_move_attack1, false);
    self.monsterinfo.nextframe = FRAME_attak114;
  } else if (
    (self.monsterinfo.aiflags & MonsterAiFlagsT.AI_STAND_GROUND) !== 0n ||
    (self.enemy && (range_to(self, self.enemy) < RANGE_RUN_ATTACK || !ai_check_move(self, 8.0)))
  ) {
    // we got too close, or we can't move forward, switch us back to regular attack
    M_SetAnimation(self, infantry_move_attack1, false);
    self.monsterinfo.nextframe = FRAME_attak103;
    monster_done_dodge(self);
    self.monsterinfo.attack_state = MonsterAttackStateT.AS_STRAIGHT;
  } else {
    self.monsterinfo.nextframe = FRAME_run201;
  }

  infantry_fire(self);
}

const infantry_frames_attack4: MframeT[] = [
  mk(ai_charge, 16, infantry_fire),
  mk(ai_charge, 16, (self) => {
    monster_footstep(self);
    infantry_fire(self);
  }),
  mk(ai_charge, 13, infantry_fire),
  mk(ai_charge, 10, infantry_fire),
  mk(ai_charge, 16, infantry_fire),
  mk(ai_charge, 16, (self) => {
    monster_footstep(self);
    infantry_fire(self);
  }),
  mk(ai_charge, 16, infantry_fire),
  mk(ai_charge, 16, infantry_attack4_refire),
];
const infantry_move_attack4 = RegisterMmove("infantry_move_attack4", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_run201;
  m.lastframe = FRAME_run208;
  m.frame = infantry_frames_attack4;
  m.endfunc = (self) => infantry_run(self);
  m.sidestep_scale = 0.5;
  return m;
})());

const infantry_attack: MonsterinfoAttackFn = RegisterMonsterinfoAttack("infantry_attack", (self: EdictT): void => {
  monster_done_dodge(self);

  if (!self.enemy) return;
  const r = range_to(self, self.enemy);

  if (r <= RANGE_MELEE && self.monsterinfo.melee_debounce_time <= level.time) {
    M_SetAnimation(self, infantry_move_attack2, false);
  } else if (M_CheckClearShot(self, monsterFlashOffset()[MonsterMuzzleflashIdT.MZ2_INFANTRY_MACHINEGUN_1])) {
    if (self.count) {
      M_SetAnimation(self, infantry_move_attack1, false);
    } else {
      M_SetAnimation(self, frandom() <= 0.1 ? infantry_move_attack5 : infantry_move_attack3, false);
      self.monsterinfo.nextframe = FRAME_attak405;
    }
  }
});

// ============================================================================
// JUMP (PGM)
// ============================================================================

function infantry_jump_now(self: EdictT): void {
  const forward = vec3(0, 0, 0);
  const up = vec3(0, 0, 0);
  AngleVectors(self.s.angles, forward, null, up);
  self.velocity = vec3_add(self.velocity, vec3_muls(forward, 100));
  self.velocity = vec3_add(self.velocity, vec3_muls(up, 300));
}

function infantry_jump2_now(self: EdictT): void {
  const forward = vec3(0, 0, 0);
  const up = vec3(0, 0, 0);
  AngleVectors(self.s.angles, forward, null, up);
  self.velocity = vec3_add(self.velocity, vec3_muls(forward, 150));
  self.velocity = vec3_add(self.velocity, vec3_muls(up, 400));
}

/** rogue/g_rogue_newai.cpp:101-116. Small and self-contained (no nav_path
 *  dependency) -- ported for real. */
function monster_jump_finished(self: EdictT): boolean {
  const forward = vec3(0, 0, 0);
  AngleVectors(self.s.angles, forward, null, null);

  const fwd_speed = vec3_dot(self.velocity, forward);

  if (Math.abs(fwd_speed) < 150) {
    const z_velocity = self.velocity[2];
    self.velocity = vec3_muls(forward, 150);
    self.velocity[2] = z_velocity;
  }

  return self.monsterinfo.jump_time < level.time;
}

function infantry_jump_wait_land(self: EdictT): void {
  if (self.groundentity === null) {
    self.monsterinfo.nextframe = self.s.frame;

    if (monster_jump_finished(self)) self.monsterinfo.nextframe = self.s.frame + 1;
  } else {
    self.monsterinfo.nextframe = self.s.frame + 1;
  }
}

const infantry_frames_jump: MframeT[] = [
  mk(ai_move),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move, 0, infantry_jump_now),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move, 0, infantry_jump_wait_land),
  mk(ai_move),
  mk(ai_move),
];
const infantry_move_jump = RegisterMmove("infantry_move_jump", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_jump01;
  m.lastframe = FRAME_jump10;
  m.frame = infantry_frames_jump;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

const infantry_frames_jump2: MframeT[] = [
  mk(ai_move, -8),
  mk(ai_move, -4),
  mk(ai_move, -4),
  mk(ai_move, 0, infantry_jump2_now),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move),
  mk(ai_move, 0, infantry_jump_wait_land),
  mk(ai_move),
  mk(ai_move),
];
const infantry_move_jump2 = RegisterMmove("infantry_move_jump2", (() => {
  const m = new MmoveT();
  m.firstframe = FRAME_jump01;
  m.lastframe = FRAME_jump10;
  m.frame = infantry_frames_jump2;
  m.endfunc = (self) => infantry_run(self);
  return m;
})());

function infantry_jump(self: EdictT, result: BlockedJumpResultT): void {
  if (!self.enemy) return;

  monster_done_dodge(self);

  if (result === BlockedJumpResultT.JUMP_JUMP_UP) M_SetAnimation(self, infantry_move_jump2, false);
  else M_SetAnimation(self, infantry_move_jump, false);
}

const infantry_blocked: MonsterinfoBlockedFn = RegisterMonsterinfoBlocked("infantry_blocked", (self: EdictT, dist: number): boolean => {
  const result = blocked_checkjump(self, dist);
  if (result !== BlockedJumpResultT.NO_JUMP) {
    if (result !== BlockedJumpResultT.JUMP_TURN) infantry_jump(self, result);
    return true;
  }

  if (blocked_checkplat(self, dist)) return true;

  return false;
});

const infantry_duck: MonsterinfoDuckFn = RegisterMonsterinfoDuck("infantry_duck", (self: EdictT, _eta: GTime): boolean => {
  // if we're jumping, don't dodge
  if (self.monsterinfo.active_move === infantry_move_jump || self.monsterinfo.active_move === infantry_move_jump2) {
    return false;
  }

  // don't duck during our firing or melee frames
  if (self.s.frame === FRAME_attak103 || self.s.frame === FRAME_attak315 || self.monsterinfo.active_move === infantry_move_attack2) {
    self.monsterinfo.unduck?.(self);
    return false;
  }

  M_SetAnimation(self, infantry_move_duck, false);

  return true;
});

const infantry_sidestep: MonsterinfoSidestepFn = RegisterMonsterinfoSidestep("infantry_sidestep", (self: EdictT): boolean => {
  // if we're jumping, don't dodge
  if (self.monsterinfo.active_move === infantry_move_jump || self.monsterinfo.active_move === infantry_move_jump2) {
    return false;
  }

  if (self.monsterinfo.active_move === infantry_move_run) return true;

  // Don't sidestep if we're already sidestepping, and def not unless we're actually shooting
  // or if we already cocked
  if (
    self.monsterinfo.active_move !== infantry_move_attack4 &&
    self.monsterinfo.next_move !== infantry_move_attack4 &&
    (self.s.frame === FRAME_attak103 || self.s.frame === FRAME_attak311 || self.s.frame === FRAME_attak416) &&
    !self.count
  ) {
    // give us a fire time boost so we don't end up firing for 1 frame
    self.monsterinfo.fire_wait = Gtime_add(self.monsterinfo.fire_wait, random_time(Gtime_from_ms(300), Gtime_from_ms(600)));

    M_SetAnimation(self, infantry_move_attack4, false);
  }

  return true;
});

/** m_infantry.cpp:849-864. Exported separately so g_turret.ts's own
 *  `InfantryPrecache` throwing stub (see its header's "EXTERNAL
 *  DEPENDENCIES NOT YET PORTED") can eventually import this real
 *  implementation. */
export function InfantryPrecache(): void {
  sound_pain1 = gi.soundindex("infantry/infpain1.wav");
  sound_pain2 = gi.soundindex("infantry/infpain2.wav");
  sound_die1 = gi.soundindex("infantry/infdeth1.wav");
  sound_die2 = gi.soundindex("infantry/infdeth2.wav");

  sound_gunshot = gi.soundindex("infantry/infatck1.wav");
  sound_weapon_cock = gi.soundindex("infantry/infatck3.wav");
  sound_punch_swing = gi.soundindex("infantry/infatck2.wav");
  sound_punch_hit = gi.soundindex("infantry/melee2.wav");

  sound_sight = gi.soundindex("infantry/infsght1.wav");
  sound_search = gi.soundindex("infantry/infsrch1.wav");
  sound_idle = gi.soundindex("infantry/infidle1.wav");
}

const SPAWNFLAG_INFANTRY_NOJUMPING: SpawnFlags = SpawnFlags_from(8);

/**
 * QUAKED monster_infantry (1 .5 0) (-16 -16 -24) (16 16 32) Ambush
 * Trigger_Spawn Sight NoJumping
 *
 * m_infantry.cpp:868-928.
 */
export function SP_monster_infantry(self: EdictT): void {
  if (!M_AllowSpawn(self)) {
    G_FreeEdict(self);
    return;
  }

  InfantryPrecache();

  self.monsterinfo.aiflags |= MonsterAiFlagsT.AI_STINKY;

  self.movetype = MovetypeT.MOVETYPE_STEP;
  self.solid = SolidT.SOLID_BBOX;
  self.s.modelindex = gi.modelindex("models/monsters/infantry/tris.md2");

  gi.modelindex("models/monsters/infantry/gibs/head.md2");
  gi.modelindex("models/monsters/infantry/gibs/chest.md2");
  gi.modelindex("models/monsters/infantry/gibs/gun.md2");
  gi.modelindex("models/monsters/infantry/gibs/arm.md2");
  gi.modelindex("models/monsters/infantry/gibs/foot.md2");

  self.mins = vec3(-16, -16, -24);
  self.maxs = vec3(16, 16, 32);

  self.health = Math.trunc(100 * st.health_multiplier);
  self.gib_health = -65;
  self.mass = 200;

  self.pain = infantry_pain;
  self.die = infantry_die;

  self.monsterinfo.combat_style = CombatStyleT.COMBAT_MIXED;

  self.monsterinfo.stand = infantry_stand;
  self.monsterinfo.walk = infantry_walk;
  self.monsterinfo.run = infantry_run;
  // pmm
  self.monsterinfo.dodge = M_MonsterDodge;
  self.monsterinfo.duck = infantry_duck;
  self.monsterinfo.unduck = monster_duck_up;
  self.monsterinfo.sidestep = infantry_sidestep;
  self.monsterinfo.blocked = infantry_blocked;
  // pmm
  self.monsterinfo.attack = infantry_attack;
  self.monsterinfo.melee = null;
  self.monsterinfo.sight = infantry_sight;
  self.monsterinfo.idle = infantry_fidget;
  self.monsterinfo.setskin = infantry_setskin;

  gi.linkentity(self);

  M_SetAnimation(self, infantry_move_stand, false);
  self.monsterinfo.scale = MODEL_SCALE;
  self.monsterinfo.can_jump = !SpawnFlags_has(self.spawnflags, SPAWNFLAG_INFANTRY_NOJUMPING);
  self.monsterinfo.drop_height = 192;
  self.monsterinfo.jump_height = 40;

  walkmonster_start(self);
}
