// Copyright (c) ZeniMax Media Inc.
// Licensed under the GNU General Public License 2.0.
//
// m_rider.h (2023 Quake II re-release / "KEX" engine, 71 lines). Ported
// from ~/Projects/quake2-rerelease-dll/rerelease/m_rider.h.
//
// "This file generated by ModelGen - Do NOT Modify" (C source comment,
// preserved for provenance). Frame index constants for the boss3/rider
// model, in the exact enum declaration order (FRAME_stand201 = 0,
// incrementing by 1 per member, same as the C anonymous enum -- the frame
// number embedded in each name starts at 201, not the array index, which
// starts at 0). Pure data -- no logic ported here.
//
// Representation follows src/ctf/m_player_frames.ts's precedent
// (individually exported numeric constants, one per enumerator, rather
// than a TS `enum`), matching m_player.ts in this same directory.

export const FRAME_stand201 = 0;
export const FRAME_stand202 = 1;
export const FRAME_stand203 = 2;
export const FRAME_stand204 = 3;
export const FRAME_stand205 = 4;
export const FRAME_stand206 = 5;
export const FRAME_stand207 = 6;
export const FRAME_stand208 = 7;
export const FRAME_stand209 = 8;
export const FRAME_stand210 = 9;
export const FRAME_stand211 = 10;
export const FRAME_stand212 = 11;
export const FRAME_stand213 = 12;
export const FRAME_stand214 = 13;
export const FRAME_stand215 = 14;
export const FRAME_stand216 = 15;
export const FRAME_stand217 = 16;
export const FRAME_stand218 = 17;
export const FRAME_stand219 = 18;
export const FRAME_stand220 = 19;
export const FRAME_stand221 = 20;
export const FRAME_stand222 = 21;
export const FRAME_stand223 = 22;
export const FRAME_stand224 = 23;
export const FRAME_stand225 = 24;
export const FRAME_stand226 = 25;
export const FRAME_stand227 = 26;
export const FRAME_stand228 = 27;
export const FRAME_stand229 = 28;
export const FRAME_stand230 = 29;
export const FRAME_stand231 = 30;
export const FRAME_stand232 = 31;
export const FRAME_stand233 = 32;
export const FRAME_stand234 = 33;
export const FRAME_stand235 = 34;
export const FRAME_stand236 = 35;
export const FRAME_stand237 = 36;
export const FRAME_stand238 = 37;
export const FRAME_stand239 = 38;
export const FRAME_stand240 = 39;
export const FRAME_stand241 = 40;
export const FRAME_stand242 = 41;
export const FRAME_stand243 = 42;
export const FRAME_stand244 = 43;
export const FRAME_stand245 = 44;
export const FRAME_stand246 = 45;
export const FRAME_stand247 = 46;
export const FRAME_stand248 = 47;
export const FRAME_stand249 = 48;
export const FRAME_stand250 = 49;
export const FRAME_stand251 = 50;
export const FRAME_stand252 = 51;
export const FRAME_stand253 = 52;
export const FRAME_stand254 = 53;
export const FRAME_stand255 = 54;
export const FRAME_stand256 = 55;
export const FRAME_stand257 = 56;
export const FRAME_stand258 = 57;
export const FRAME_stand259 = 58;
export const FRAME_stand260 = 59;

export const MODEL_SCALE = 1.0;
